In [1]:
import pandas as pd

df = pd.read_csv("../data/twcs.csv", nrows=1000)

df.head()

,tweet_id,author_id,inbound,created_at,text,response_tweet_id,in_response_to_tweet_id
0,1,sprintcare,False,Tue Oct 31 22:10:47 +0000 2017,@115712 I understand. I would like to assist y...,2,3.0
1,2,115712,True,Tue Oct 31 22:11:45 +0000 2017,@sprintcare and how do you propose we do that,NaN,1.0
2,3,115712,True,Tue Oct 31 22:08:27 +0000 2017,@sprintcare I have sent several private messag...,1,4.0
3,4,sprintcare,False,Tue Oct 31 21:54:49 +0000 2017,@115712 Please send us a Private Message so th...,3,5.0
4,5,115712,True,Tue Oct 31 21:49:35 +0000 2017,@sprintcare I did.,4,6.0

In [2]:
df.columns

Index(['tweet_id', 'author_id', 'inbound', 'created_at', 'text',
       'response_tweet_id', 'in_response_to_tweet_id'],
      dtype='str')

In [3]:
df.shape

(1000, 7)

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 7 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   tweet_id                 1000 non-null   int64
 1   author_id                1000 non-null   str
 2   inbound                  1000 non-null   bool
 3   created_at               1000 non-null   str
 4   text                     1000 non-null   str
 5   response_tweet_id        679 non-null    str
 6   in_response_to_tweet_id  747 non-null    float64
dtypes: bool(1), float64(1), int64(1), str(4)
memory usage: 48.0 KB

In [5]:
df[df["inbound"] == False].head(20)

,tweet_id,author_id,inbound,created_at,text,response_tweet_id,in_response_to_tweet_id
0,1,sprintcare,False,Tue Oct 31 22:10:47 +0000 2017,@115712 I understand. I would like to assist y...,2,3.0
3,4,sprintcare,False,Tue Oct 31 21:54:49 +0000 2017,@115712 Please send us a Private Message so th...,3,5.0
5,6,sprintcare,False,Tue Oct 31 21:46:24 +0000 2017,@115712 Can you please send us a private messa...,"5,7",8.0
7,11,sprintcare,False,Tue Oct 31 22:10:35 +0000 2017,@115713 This is saddening to hear. Please shoo...,NaN,12.0
9,15,sprintcare,False,Tue Oct 31 20:03:31 +0000 2017,@115713 We understand your concerns and we'd l...,12,16.0
11,17,sprintcare,False,Tue Oct 31 19:59:13 +0000 2017,@115713 H there! We'd definitely like to work ...,16,18.0
13,19,sprintcare,False,Tue Oct 31 22:10:10 +0000 2017,@115715 Please send me a private message so th...,NaN,20.0
15,21,Ask_Spectrum,False,Tue Oct 31 22:14:37 +0000 2017,@115716 What information is incorrect? ^JK,"22,23",24.0
17,25,Ask_Spectrum,False,Tue Oct 31 22:18:28 +0000 2017,@115716 Our department is part of the corporat...,26,22.0
19,27,Ask_Spectrum,False,Tue Oct 31 22:21:26 +0000 2017,@115716 No thank you. ^JK,NaN,26.0
22,28,Ask_Spectrum,False,Tue Oct 31 22:05:37 +0000 2017,@115716 The information pertaining to the acco...,24,29.0
24,30,Ask_Spectrum,False,Tue Oct 31 22:12:09 +0000 2017,"@115717 Hello, My apologies for any frustratio...",NaN,31.0
26,32,Ask_Spectrum,False,Tue Oct 31 22:10:08 +0000 2017,@115718 I apologize for the inconvenience. I w...,NaN,33.0
28,34,VerizonSupport,False,Tue Oct 31 22:13:33 +0000 2017,@115719 Help has arrived! We are sorry to see ...,35,36.0
30,37,VerizonSupport,False,Tue Oct 31 22:52:00 +0000 2017,@115719 Awesome! If you ever need us we are ju...,NaN,35.0
32,38,VerizonSupport,False,Tue Oct 31 22:13:30 +0000 2017,@115720 Have your friend message us.\n^ACM,NaN,39.0
34,40,VerizonSupport,False,Tue Oct 31 22:12:00 +0000 2017,@115721 Please follow and DM us so that we can...,41,42.0
36,43,VerizonSupport,False,Tue Oct 31 22:29:00 +0000 2017,@115721 We would not be able to verify anythin...,44,41.0
38,45,VerizonSupport,False,Tue Oct 31 22:36:29 +0000 2017,@115721 We can use the order number to locate ...,NaN,44.0
44,50,VerizonSupport,False,Tue Oct 31 22:07:30 +0000 2017,@115723 Is the light on top red?\n^JAY,NaN,51.0

In [6]:
df[df["inbound"] == True].head(20)

,tweet_id,author_id,inbound,created_at,text,response_tweet_id,in_response_to_tweet_id
1,2,115712,True,Tue Oct 31 22:11:45 +0000 2017,@sprintcare and how do you propose we do that,NaN,1.0
2,3,115712,True,Tue Oct 31 22:08:27 +0000 2017,@sprintcare I have sent several private messag...,1,4.0
4,5,115712,True,Tue Oct 31 21:49:35 +0000 2017,@sprintcare I did.,4,6.0
6,8,115712,True,Tue Oct 31 21:45:10 +0000 2017,@sprintcare is the worst customer service,"9,6,10",NaN
8,12,115713,True,Tue Oct 31 22:04:47 +0000 2017,@sprintcare You gonna magically change your co...,"11,13,14",15.0
10,16,115713,True,Tue Oct 31 20:00:43 +0000 2017,@sprintcare Since I signed up with you....Sinc...,15,17.0
12,18,115713,True,Tue Oct 31 19:56:01 +0000 2017,@115714 y’all lie about your “great” connectio...,17,NaN
14,20,115715,True,Tue Oct 31 22:03:34 +0000 2017,"@115714 whenever I contact customer support, t...",19,NaN
16,22,115716,True,Tue Oct 31 22:16:48 +0000 2017,@Ask_Spectrum Would you like me to email you a...,25,21.0
18,26,115716,True,Tue Oct 31 22:19:56 +0000 2017,@Ask_Spectrum I received this from your corpor...,27,25.0
20,23,115716,True,Tue Oct 31 22:16:05 +0000 2017,@Ask_Spectrum The correct way to do it is via ...,NaN,21.0
21,24,115716,True,Tue Oct 31 22:13:02 +0000 2017,@Ask_Spectrum That is INCORRECT information I ...,21,28.0
23,29,115716,True,Tue Oct 31 22:01:35 +0000 2017,actually that's a broken link you sent me and ...,28,NaN
25,31,115717,True,Tue Oct 31 22:06:54 +0000 2017,"Yo @Ask_Spectrum, your customer service reps a...",30,NaN
27,33,115718,True,Tue Oct 31 22:06:56 +0000 2017,My picture on @Ask_Spectrum pretty much every ...,32,NaN
29,35,115719,True,Tue Oct 31 22:49:16 +0000 2017,@VerizonSupport I finally got someone that hel...,37,34.0
31,36,115719,True,Tue Oct 31 22:10:46 +0000 2017,somebody from @VerizonSupport please help meee...,34,NaN
33,39,115720,True,Tue Oct 31 22:12:16 +0000 2017,@VerizonSupport My friend is without internet ...,38,NaN
35,41,115721,True,Tue Oct 31 22:24:55 +0000 2017,@VerizonSupport What else can I provide? They ...,43,40.0
37,44,115721,True,Tue Oct 31 22:32:06 +0000 2017,@VerizonSupport How? I have my phone number an...,45,43.0

In [7]:
df["inbound"].value_counts()

inbound
True     539
False    461
Name: count, dtype: int64

In [8]:
import pandas as pd

brands = ["Uber_Support", "SpotifyCares", "AppleSupport", "AmazonHelp"]

brand_counts = {brand: 0 for brand in brands}

for chunk in pd.read_csv("../data/twcs.csv", chunksize=100_000):
    brand_rows = chunk[
        (chunk["inbound"] == False) &
        (chunk["author_id"].isin(brands))
    ]
    
    counts = brand_rows["author_id"].value_counts()
    
    for brand in brands:
        brand_counts[brand] += counts.get(brand, 0)

brand_counts

{'Uber_Support': np.int64(56270),
 'SpotifyCares': np.int64(43265),
 'AppleSupport': np.int64(106860),
 'AmazonHelp': np.int64(169840)}

In [11]:
uber = df[
    (df["author_id"] == "Uber_Support") &
    (df["inbound"] == False)
]

uber[[
    "tweet_id",
    "author_id",
    "inbound",
    "text",
    "response_tweet_id",
    "in_response_to_tweet_id"
]].head(20)

,tweet_id,author_id,inbound,text,response_tweet_id,in_response_to_tweet_id
463,768,Uber_Support,False,@115872 Happy to follow up! Contact us via htt...,"769,770",771.0
465,770,Uber_Support,False,@115872 We apologize for the trouble! Send us ...,NaN,768.0
467,772,Uber_Support,False,@115874 We're here to help! Send us a note her...,NaN,773.0
469,774,Uber_Support,False,"@115875 We’re here to help, Travis! Send us a ...",NaN,775.0
471,776,Uber_Support,False,@115876 For more info about UberEats availabil...,NaN,777.0
473,778,Uber_Support,False,@115878 We have received your DM and will foll...,779,780.0
476,781,Uber_Support,False,@115878 We're sorry to hear this was your expe...,780,782.0
478,783,Uber_Support,False,@115880 We're sorry to hear this was your expe...,NaN,784.0

In [12]:
uber_samples = []

for chunk in pd.read_csv("../data/twcs.csv", chunksize=100_000):
    
    matches = chunk[
        (chunk["author_id"] == "Uber_Support") &
        (chunk["inbound"] == False)
    ]
    
    if len(matches) > 0:
        uber_samples.append(matches)

uber_df = pd.concat(uber_samples, ignore_index=True)

print("Uber brand responses:", len(uber_df))

Uber brand responses: 56270

In [13]:
uber_df.head(20)

,tweet_id,author_id,inbound,created_at,text,response_tweet_id,in_response_to_tweet_id
0,768,Uber_Support,False,Tue Oct 31 22:28:17 +0000 2017,@115872 Happy to follow up! Contact us via htt...,"769,770",771.0
1,770,Uber_Support,False,Tue Oct 31 22:31:08 +0000 2017,@115872 We apologize for the trouble! Send us ...,NaN,768.0
2,772,Uber_Support,False,Tue Oct 31 22:25:26 +0000 2017,@115874 We're here to help! Send us a note her...,NaN,773.0
3,774,Uber_Support,False,Tue Oct 31 22:19:18 +0000 2017,"@115875 We’re here to help, Travis! Send us a ...",NaN,775.0
4,776,Uber_Support,False,Tue Oct 31 22:17:58 +0000 2017,@115876 For more info about UberEats availabil...,NaN,777.0
5,778,Uber_Support,False,Tue Oct 31 22:17:41 +0000 2017,@115878 We have received your DM and will foll...,779,780.0
6,781,Uber_Support,False,Tue Oct 31 21:49:36 +0000 2017,@115878 We're sorry to hear this was your expe...,780,782.0
7,783,Uber_Support,False,Tue Oct 31 22:15:25 +0000 2017,@115880 We're sorry to hear this was your expe...,NaN,784.0
8,1792,Uber_Support,False,Tue Oct 31 22:41:33 +0000 2017,@116108 Here to help! Send us a note via https...,1793,1794.0
9,1795,Uber_Support,False,Tue Oct 31 23:49:04 +0000 2017,@116108 We're here to help! Send us a DM with ...,NaN,1793.0
10,1796,Uber_Support,False,Tue Oct 31 22:40:29 +0000 2017,@116109 We have followed up via DM.,NaN,1797.0
11,1798,Uber_Support,False,Tue Oct 31 22:37:04 +0000 2017,@116110 Here to help! Send us a note via https...,1799,1800.0
12,1801,Uber_Support,False,Tue Oct 31 22:36:51 +0000 2017,@116111 Here to help! Send us a note via https...,1802,1803.0
13,1804,Uber_Support,False,Tue Oct 31 23:18:23 +0000 2017,@116111 We're currently reviewing your email a...,1805,1802.0
14,1806,Uber_Support,False,Tue Oct 31 22:34:31 +0000 2017,@116112 We're sorry to hear this was your expe...,NaN,1807.0
15,1808,Uber_Support,False,Tue Oct 31 22:32:09 +0000 2017,@116113 Please DM us with your account email a...,NaN,1809.0
16,1810,Uber_Support,False,Tue Oct 31 21:55:48 +0000 2017,@116113 Sorry to hear this was your experience...,"1811,1809",1812.0
17,1864,Uber_Support,False,Fri Dec 01 06:47:07 +0000 2017,@116127 Here to help! Please DM (direct messag...,1865,1866.0
18,2096,Uber_Support,False,Fri Dec 01 06:46:09 +0000 2017,@116168 Happy to further assist you. Can you p...,2097,2098.0
19,2099,Uber_Support,False,Fri Dec 01 12:15:57 +0000 2017,"@116168 Hi, Singh. Please send us a DM with yo...",NaN,2097.0

In [14]:
# Get the IDs of customer tweets that Uber responded to
customer_tweet_ids = set(
    uber_df["in_response_to_tweet_id"]
    .dropna()
    .astype(int)
)

print("Customer tweets we want:", len(customer_tweet_ids))

Customer tweets we want: 55283

In [15]:
uber_customers = []

for chunk in pd.read_csv("../data/twcs.csv", chunksize=100_000):
    
    matches = chunk[
        (chunk["inbound"] == True) &
        (chunk["tweet_id"].isin(customer_tweet_ids))
    ]
    
    if len(matches) > 0:
        uber_customers.append(matches)

uber_customers = pd.concat(uber_customers, ignore_index=True)

print("Customer tweets found:", len(uber_customers))

Customer tweets found: 55182

In [16]:
uber_pairs = uber_df.merge(
    uber_customers[["tweet_id", "text"]],
    left_on="in_response_to_tweet_id",
    right_on="tweet_id",
    how="inner",
    suffixes=("_uber", "_customer")
)

uber_pairs[[
    "tweet_id_customer",
    "text_customer",
    "tweet_id_uber",
    "text_uber"
]].head(20)

,tweet_id_customer,text_customer,tweet_id_uber,text_uber
0,771,@115873 you need to correct false charges from...,768,@115872 Happy to follow up! Contact us via htt...
1,773,@115873 my driver just drove me to the departm...,772,@115874 We're here to help! Send us a note her...
2,775,@Uber_Support I’m not getting your texts. http...,774,"@115875 We’re here to help, Travis! Send us a ..."
3,777,@115877 got this threw my door today went to o...,776,@115876 For more info about UberEats availabil...
4,780,@Uber_Support Why is there no phone number ?? ...,778,@115878 We have received your DM and will foll...
5,782,Literally stranded because of @115873 and beca...,781,@115878 We're sorry to hear this was your expe...
6,784,1 hour+ inside an old Altima that smells and h...,783,@115880 We're sorry to hear this was your expe...
7,1794,@115873 wtf is this.. every time I try to use ...,1792,@116108 Here to help! Send us a note via https...
8,1793,@Uber_Support I did. No response.,1795,@116108 We're here to help! Send us a DM with ...
9,1797,@115877 your app and website still don’t work,1796,@116109 We have followed up via DM.
10,1800,@115873 hi just for a ride and it seemed to th...,1798,@116110 Here to help! Send us a note via https...
11,1803,Bruh can someone at @115873 @Uber_Support get ...,1801,@116111 Here to help! Send us a note via https...
12,1802,@Uber_Support I already dm y'all about 30 mins...,1804,@116111 We're currently reviewing your email a...
13,1807,.@Uber_Support My driver broke down. Any tips ...,1806,@116112 We're sorry to hear this was your expe...
14,1809,@Uber_Support i do not see we're the trid if i...,1808,@116113 Please DM us with your account email a...
15,1812,@115873 worst most unprofessional driver ever ...,1810,@116113 Sorry to hear this was your experience...
16,1866,@Uber_Support I have submitted complain agains...,1864,@116127 Here to help! Please DM (direct messag...
17,2098,kya khassi support hai yaar @Uber_Support. i a...,2096,@116168 Happy to further assist you. Can you p...
18,2097,@Uber_Support done please check,2099,"@116168 Hi, Singh. Please send us a DM with yo..."
19,2125,@Uber_Support After contacting you concerning...,2124,@116175 Hello! Thanks for your patience. Pleas...

In [17]:
print("Uber response pairs:", len(uber_pairs))
print()

print("Customer tweets with matched Uber response:",
      uber_pairs["text_customer"].notna().sum())

print()

print("Average customer message length:",
      uber_pairs["text_customer"].str.len().mean())

print()

print("Average Uber response length:",
      uber_pairs["text_uber"].str.len().mean())

Uber response pairs: 56160

Customer tweets with matched Uber response: 56160

Average customer message length: 120.22101139601139

Average Uber response length: 110.07929131054131

In [18]:
uber_pairs[
    ["text_customer", "text_uber"]
].sample(20, random_state=42).to_string(index=False)

"                                                                                                                                                                                                                                                         text_customer                                                                                                                                                                                                                                                                         text_uber\n                                                                                                                                                                                        @Uber_Support My colleague has completed 75 trips and no credit has been added                                                                                                                                @561172 Hi. Please check out the following page to learn more, and to contact us directly so we can investigate further:  https://t.co/zs35E3F6G9.\n                                                                                                                                                                                                                                @115873 cant book a ride when u need.😑                                                                                                                                 @388763 Sorry to hear about the trouble. You can send us a note here; https://t.co/xMxswVLBKT and our team will get in touch to help you further.\n                                                                                                                 @115877 @115873 So to conclude this hangry rant, the avocado on my order had browned by the time it got here from 4 blocks away after a 1 hour drive.                                                                                                                                                                                         @119366 Sorry to hear about this! Send us a DM with your email address so we can connect.\n                                                                                                                                                     @115873 yooooo. Uber drivers using intimidation to get tips on the app and cash. Thanks for ruining my night out.                                                                                                                                                                          @255464 We take this very seriously. Please send us a DM with your email address so we can connect ASAP.\n                                                                                                                                                                         @115873 help ASAP lost my wallet in my ride 10 minutes ago please call me DM me for my number                                                                                                                                                                                              @240248 Here to help! Get in contact with your driver here: https://t.co/rOtqyWhDC1.\n                                                                                                                                                                                                          @Uber_Support how to report problems faced by me while login                                                                                                                                                                                             @441814 Please send us specific details of your concern, so we can better assist you.\n                                                                                                                          @131077 @131077 sorry but this is urgent someone is using my detaila/account for fraud via Uber I've tried emailing but no response. HELP !!                                                                                                                                                             @176874 Oh no! Thanks for bringing this to our attention. DM us your account email along with details for assistance.\n                                      @116288 @115873 @Uber_Support - I took Uber but my driver did not stop the ride and now my bill is 5 times of the estimated bill.I tried to contact Uber via support but did not get reply since 2 days. https://t.co/PupMJm5XsB                                                                                                                                                                                @412365 Hi, Shreya! Here to help. Kindly send us your email address via DM so our team can assist.\n                                                                                                                                                                                                                                  @Uber_Support ironically, it's #IDPD @255907 Hello, Rico. Our team has followed up with you via email regarding this matter. Our responses can be found both in-app via the Help tab and within the email address associated with your account. Please reply there directly and we will be sure to follow up with you.\n                                                                                                                                                                            @Uber_Support I have sent you my details. This is unbelievable! Not the first time either.                                                                                                                                                                                                @273095 Hello, Jovi! Thanks for your patience. Please check your DM for our reply.\n                                                                                                                           @Uber_Support Never Go with Uber, Drivers are cancelling the scheduled trips as well in the last minute.. Terrrible exp with so much loss..                                                                                                                                                                                                                                   @297558 We just got back to you via DM, Rajani.\n                                                                                                                                                     @Uber_Support I already did that! More then once and also like a month ago! And still no reply from Uber support!                                                                                                                                                                                                                           @128734 We've responded via DM, please follow up there.\n                                                                                                                                                                                                    @115873 See how your driver runs away !!!! https://t.co/QZ6M1vWQtb                                                                                                                                                                                           @552561 Here to help! Send us a note via https://t.co/593jusCquh to assist you further.\n                                                                                                                                                      @115873 please remove the 1k charge on my account. The driver never showed up and I didn't take the ride. Thanks                                                                                                                                                                                  @294430 Here to help! Send us a note here, https://t.co/OhfgxSAY58, and our team will follow up.\n                                                                                                                                              @Uber_Support I already did twice. I guess it'll be @115879 from now on. I would like a refund asap. Terrible experience                                                                                                                                                                      @307137 We're happy to connect, Scott. Please DM us the email on your account and we'll be in touch shortly.\n@Uber_Support It’s not my account I don’t have an Uber account I am speaking to you on behalf of my friend.  She gave me the drivers information I wanted to bring this up to you. Can I give u the drivers information? I did a full background check on your driver.       @673176 Thanks for getting back with us, Heather. Please note, due to our Privacy Policy, we will need your friend to reach out to us. Please have her DM us or send us a note at https://t.co/ZKiiZxW1QJ and we'll follow up. We'll be keeping an eye out for her message.\n                                                                                                                                          @Uber_Support hey my mom left her phone in a car from early this morning and doesn’t have a way to get it back. Can you help                                                                                                                                  @583673 Due to our privacy policy, we will have to speak directly to the account holder. Please have them contact us via https://t.co/rOtqyWzf0B\n                                                                                                                                                                                            @119720 it seems I am region blocked to California.....but I’m near DC...😮                                                                                                                               @177417 Let's take a look. DM the email address to your Uber account so we can connect. In the meantime, make sure to reset your location services.\n                                                                                                                                                                                      @Uber_Support Driver details attached in the screen shot https://t.co/HVIZT1rfWW     @241215 Thanks for reaching out. We definitely take this very seriously and want to make sure that your concerns are addressed. Please send us a note through https://t.co/z8NNR5nPpN so we can help.This will allow the appropriate team to reply to it as soon as possible.\n                                                                                                                          @Uber_Support PLEASE I HAVE REACH THE MEXICO TEAM WITH NO RESPONSE SINCE 2 WEEKS AGO. I REALLY NEED MY INVOCIE TODAY FROM A TRIP AND NO HELP                                                                                                                                                                                          @728988 Happy to help! Send us a DM with your email address and our team will follow up."

In [19]:
sample = uber_pairs[["text_customer", "text_uber"]].sample(10, random_state=42)

for i, row in sample.iterrows():
    print(f"\n--- Example ---")
    print("CUSTOMER:", row["text_customer"])
    print("UBER:", row["text_uber"])

--- Example ---
CUSTOMER: @Uber_Support My colleague has completed 75 trips and no credit has been added
UBER: @561172 Hi. Please check out the following page to learn more, and to contact us directly so we can investigate further:  https://t.co/zs35E3F6G9.

--- Example ---
CUSTOMER: @115873 cant book a ride when u need.😑
UBER: @388763 Sorry to hear about the trouble. You can send us a note here; https://t.co/xMxswVLBKT and our team will get in touch to help you further.

--- Example ---
CUSTOMER: @115877 @115873 So to conclude this hangry rant, the avocado on my order had browned by the time it got here from 4 blocks away after a 1 hour drive.
UBER: @119366 Sorry to hear about this! Send us a DM with your email address so we can connect.

--- Example ---
CUSTOMER: @115873 yooooo. Uber drivers using intimidation to get tips on the app and cash. Thanks for ruining my night out.
UBER: @255464 We take this very seriously. Please send us a DM with your email address so we can connect ASAP.

--- Example ---
CUSTOMER: @115873 help ASAP lost my wallet in my ride 10 minutes ago please call me DM me for my number
UBER: @240248 Here to help! Get in contact with your driver here: https://t.co/rOtqyWhDC1.

--- Example ---
CUSTOMER: @Uber_Support how to report problems faced by me while login
UBER: @441814 Please send us specific details of your concern, so we can better assist you.

--- Example ---
CUSTOMER: @131077 @131077 sorry but this is urgent someone is using my detaila/account for fraud via Uber I've tried emailing but no response. HELP !!
UBER: @176874 Oh no! Thanks for bringing this to our attention. DM us your account email along with details for assistance.

--- Example ---
CUSTOMER: @116288 @115873 @Uber_Support - I took Uber but my driver did not stop the ride and now my bill is 5 times of the estimated bill.I tried to contact Uber via support but did not get reply since 2 days. https://t.co/PupMJm5XsB
UBER: @412365 Hi, Shreya! Here to help. Kindly send us your email address via DM so our team can assist.

--- Example ---
CUSTOMER: @Uber_Support ironically, it's #IDPD
UBER: @255907 Hello, Rico. Our team has followed up with you via email regarding this matter. Our responses can be found both in-app via the Help tab and within the email address associated with your account. Please reply there directly and we will be sure to follow up with you.

--- Example ---
CUSTOMER: @Uber_Support I have sent you my details. This is unbelievable! Not the first time either.
UBER: @273095 Hello, Jovi! Thanks for your patience. Please check your DM for our reply.

In [20]:
# Create a sample of Uber conversations for intent discovery

intent_sample = (
    uber_pairs[
        ["text_customer", "text_uber"]
    ]
    .dropna()
    .sample(300, random_state=42)
    .reset_index(drop=True)
)

print("Sample size:", len(intent_sample))

Sample size: 300

In [21]:
intent_sample.to_csv(
    "../data/uber_intent_sample.csv",
    index=False
)

print("Saved to ../data/uber_intent_sample.csv")

Saved to ../data/uber_intent_sample.csv

In [22]:
for i, row in intent_sample.head(30).iterrows():
    print(f"\n{'='*70}")
    print(f"EXAMPLE {i+1}")
    print("CUSTOMER:", row["text_customer"])
    print("UBER:", row["text_uber"])

======================================================================
EXAMPLE 1
CUSTOMER: @Uber_Support My colleague has completed 75 trips and no credit has been added
UBER: @561172 Hi. Please check out the following page to learn more, and to contact us directly so we can investigate further:  https://t.co/zs35E3F6G9.

======================================================================
EXAMPLE 2
CUSTOMER: @115873 cant book a ride when u need.😑
UBER: @388763 Sorry to hear about the trouble. You can send us a note here; https://t.co/xMxswVLBKT and our team will get in touch to help you further.

======================================================================
EXAMPLE 3
CUSTOMER: @115877 @115873 So to conclude this hangry rant, the avocado on my order had browned by the time it got here from 4 blocks away after a 1 hour drive.
UBER: @119366 Sorry to hear about this! Send us a DM with your email address so we can connect.

======================================================================
EXAMPLE 4
CUSTOMER: @115873 yooooo. Uber drivers using intimidation to get tips on the app and cash. Thanks for ruining my night out.
UBER: @255464 We take this very seriously. Please send us a DM with your email address so we can connect ASAP.

======================================================================
EXAMPLE 5
CUSTOMER: @115873 help ASAP lost my wallet in my ride 10 minutes ago please call me DM me for my number
UBER: @240248 Here to help! Get in contact with your driver here: https://t.co/rOtqyWhDC1.

======================================================================
EXAMPLE 6
CUSTOMER: @Uber_Support how to report problems faced by me while login
UBER: @441814 Please send us specific details of your concern, so we can better assist you.

======================================================================
EXAMPLE 7
CUSTOMER: @131077 @131077 sorry but this is urgent someone is using my detaila/account for fraud via Uber I've tried emailing but no response. HELP !!
UBER: @176874 Oh no! Thanks for bringing this to our attention. DM us your account email along with details for assistance.

======================================================================
EXAMPLE 8
CUSTOMER: @116288 @115873 @Uber_Support - I took Uber but my driver did not stop the ride and now my bill is 5 times of the estimated bill.I tried to contact Uber via support but did not get reply since 2 days. https://t.co/PupMJm5XsB
UBER: @412365 Hi, Shreya! Here to help. Kindly send us your email address via DM so our team can assist.

======================================================================
EXAMPLE 9
CUSTOMER: @Uber_Support ironically, it's #IDPD
UBER: @255907 Hello, Rico. Our team has followed up with you via email regarding this matter. Our responses can be found both in-app via the Help tab and within the email address associated with your account. Please reply there directly and we will be sure to follow up with you.

======================================================================
EXAMPLE 10
CUSTOMER: @Uber_Support I have sent you my details. This is unbelievable! Not the first time either.
UBER: @273095 Hello, Jovi! Thanks for your patience. Please check your DM for our reply.

======================================================================
EXAMPLE 11
CUSTOMER: @Uber_Support Never Go with Uber, Drivers are cancelling the scheduled trips as well in the last minute.. Terrrible exp with so much loss..
UBER: @297558 We just got back to you via DM, Rajani.

======================================================================
EXAMPLE 12
CUSTOMER: @Uber_Support I already did that! More then once and also like a month ago! And still no reply from Uber support!
UBER: @128734 We've responded via DM, please follow up there.

======================================================================
EXAMPLE 13
CUSTOMER: @115873 See how your driver runs away !!!! https://t.co/QZ6M1vWQtb
UBER: @552561 Here to help! Send us a note via https://t.co/593jusCquh to assist you further.

======================================================================
EXAMPLE 14
CUSTOMER: @115873 please remove the 1k charge on my account. The driver never showed up and I didn't take the ride. Thanks
UBER: @294430 Here to help! Send us a note here, https://t.co/OhfgxSAY58, and our team will follow up.

======================================================================
EXAMPLE 15
CUSTOMER: @Uber_Support I already did twice. I guess it'll be @115879 from now on. I would like a refund asap. Terrible experience
UBER: @307137 We're happy to connect, Scott. Please DM us the email on your account and we'll be in touch shortly.

======================================================================
EXAMPLE 16
CUSTOMER: @Uber_Support It’s not my account I don’t have an Uber account I am speaking to you on behalf of my friend.  She gave me the drivers information I wanted to bring this up to you. Can I give u the drivers information? I did a full background check on your driver.
UBER: @673176 Thanks for getting back with us, Heather. Please note, due to our Privacy Policy, we will need your friend to reach out to us. Please have her DM us or send us a note at https://t.co/ZKiiZxW1QJ and we'll follow up. We'll be keeping an eye out for her message.

======================================================================
EXAMPLE 17
CUSTOMER: @Uber_Support hey my mom left her phone in a car from early this morning and doesn’t have a way to get it back. Can you help
UBER: @583673 Due to our privacy policy, we will have to speak directly to the account holder. Please have them contact us via https://t.co/rOtqyWzf0B

======================================================================
EXAMPLE 18
CUSTOMER: @119720 it seems I am region blocked to California.....but I’m near DC...😮
UBER: @177417 Let's take a look. DM the email address to your Uber account so we can connect. In the meantime, make sure to reset your location services.

======================================================================
EXAMPLE 19
CUSTOMER: @Uber_Support Driver details attached in the screen shot https://t.co/HVIZT1rfWW
UBER: @241215 Thanks for reaching out. We definitely take this very seriously and want to make sure that your concerns are addressed. Please send us a note through https://t.co/z8NNR5nPpN so we can help.This will allow the appropriate team to reply to it as soon as possible.

======================================================================
EXAMPLE 20
CUSTOMER: @Uber_Support PLEASE I HAVE REACH THE MEXICO TEAM WITH NO RESPONSE SINCE 2 WEEKS AGO. I REALLY NEED MY INVOCIE TODAY FROM A TRIP AND NO HELP
UBER: @728988 Happy to help! Send us a DM with your email address and our team will follow up.

======================================================================
EXAMPLE 21
CUSTOMER: @Uber_Support still no response
UBER: @248093 We've sent you a DM.

======================================================================
EXAMPLE 22
CUSTOMER: @Uber_Support I am having an issue with 2-factor Auth. I am not getting calls or texts to the number my account should be tied to.
UBER: @498013 Happy to take a closer look! Send us a DM with your email address with details so we can follow up.

======================================================================
EXAMPLE 23
CUSTOMER: @Uber_Support Do you know when Uber will add long travel time charge to San Francisco ?
UBER: @263143 Here to help! Please visit this link for more info; https://t.co/OXEdfVITnf.

======================================================================
EXAMPLE 24
CUSTOMER: @Uber_Support I would like a refund because my driver just went back and forth and I spent at least 10 minutes waiting before I cancelled. He never even got close to picking me up. https://t.co/0dGiygomdJ
UBER: @691541 Here to help. Send us a note at https://t.co/e8HVorX5rh so our team can connect.

======================================================================
EXAMPLE 25
CUSTOMER: @Uber_Support No one has got in contact with me yet
UBER: @122613 Thank you for your continued patience we are reviewing your message and will be in touch soon.

======================================================================
EXAMPLE 26
CUSTOMER: @115873 waiting patiently at LHRT5. 3 different car cancellations.Drivers are uber scamming hoping that I will cancel and pay fee-I'm waiting!
UBER: @229330 Here to help! Contact us via https://t.co/e8HVorX5rh so we can connect.

======================================================================
EXAMPLE 27
CUSTOMER: Hi @Uber_Support seems an issue with ur payment system and no way to contact you on the app. Shall we fix here?
UBER: @231882 Will you please DM us with your email address associated with your account and the details of your concern? We'll look into it.

======================================================================
EXAMPLE 28
CUSTOMER: @115873 total fare &amp;amount reflecting in receipt both are different for 3 rides, got virtual credits which were never deducted from total fare
UBER: @723209 We're here to help! Please send us a note via https://t.co/1xM0TILvAI so we can take a closer look.

======================================================================
EXAMPLE 29
CUSTOMER: @Uber_Support This is the only thing you say! You don't resolve the problem!
UBER: @415493 We've sent you a DM.

======================================================================
EXAMPLE 30
CUSTOMER: @Uber_Support I tried doing what you asked howere it didn't work because the phone I was using didn't match what I have on my uber account.
UBER: @378640 We're so sorry for the trouble you're having. Send us a DM with your email address so we can follow up.

In [23]:
# Check the most common words in Uber customer messages

from collections import Counter
import re

all_text = " ".join(
    uber_pairs["text_customer"]
    .dropna()
    .astype(str)
    .tolist()
).lower()

words = re.findall(r"\b[a-z]{3,}\b", all_text)

word_counts = Counter(words)

word_counts.most_common(30)

[('the', 30613),
 ('and', 21720),
 ('for', 15076),
 ('you', 14996),
 ('uber', 12293),
 ('driver', 11974),
 ('this', 9290),
 ('not', 9196),
 ('can', 9181),
 ('your', 8995),
 ('have', 8854),
 ('was', 8179),
 ('https', 7552),
 ('that', 7544),
 ('with', 6862),
 ('but', 6449),
 ('get', 6098),
 ('help', 5947),
 ('ride', 5561),
 ('from', 5263),
 ('app', 5221),
 ('please', 5010),
 ('account', 4849),
 ('how', 4677),
 ('just', 4668),
 ('when', 4530),
 ('charged', 4458),
 ('why', 4337),
 ('what', 3997),
 ('been', 3981)]

In [24]:
# Load the 300-example sample we created

import pandas as pd

sample = pd.read_csv("../data/uber_intent_sample.csv")

print("Sample shape:", sample.shape)
print("\nColumns:")
print(sample.columns.tolist())

print("\nFirst 20 customer messages:")
for i, row in sample.head(20).iterrows():
    print(f"\n{i+1}. {row['text_customer']}")

Sample shape: (300, 2)

Columns:
['text_customer', 'text_uber']

First 20 customer messages:

1. @Uber_Support My colleague has completed 75 trips and no credit has been added

2. @115873 cant book a ride when u need.😑

3. @115877 @115873 So to conclude this hangry rant, the avocado on my order had browned by the time it got here from 4 blocks away after a 1 hour drive.

4. @115873 yooooo. Uber drivers using intimidation to get tips on the app and cash. Thanks for ruining my night out.

5. @115873 help ASAP lost my wallet in my ride 10 minutes ago please call me DM me for my number

6. @Uber_Support how to report problems faced by me while login

7. @131077 @131077 sorry but this is urgent someone is using my detaila/account for fraud via Uber I've tried emailing but no response. HELP !!

8. @116288 @115873 @Uber_Support - I took Uber but my driver did not stop the ride and now my bill is 5 times of the estimated bill.I tried to contact Uber via support but did not get reply since 2 days. https://t.co/PupMJm5XsB

9. @Uber_Support ironically, it's #IDPD

10. @Uber_Support I have sent you my details. This is unbelievable! Not the first time either.

11. @Uber_Support Never Go with Uber, Drivers are cancelling the scheduled trips as well in the last minute.. Terrrible exp with so much loss..

12. @Uber_Support I already did that! More then once and also like a month ago! And still no reply from Uber support!

13. @115873 See how your driver runs away !!!! https://t.co/QZ6M1vWQtb

14. @115873 please remove the 1k charge on my account. The driver never showed up and I didn't take the ride. Thanks

15. @Uber_Support I already did twice. I guess it'll be @115879 from now on. I would like a refund asap. Terrible experience

16. @Uber_Support It’s not my account I don’t have an Uber account I am speaking to you on behalf of my friend.  She gave me the drivers information I wanted to bring this up to you. Can I give u the drivers information? I did a full background check on your driver.

17. @Uber_Support hey my mom left her phone in a car from early this morning and doesn’t have a way to get it back. Can you help

18. @119720 it seems I am region blocked to California.....but I’m near DC...😮

19. @Uber_Support Driver details attached in the screen shot https://t.co/HVIZT1rfWW

20. @Uber_Support PLEASE I HAVE REACH THE MEXICO TEAM WITH NO RESPONSE SINCE 2 WEEKS AGO. I REALLY NEED MY INVOCIE TODAY FROM A TRIP AND NO HELP

In [25]:
labels = [
    "promotion_credit",
    "ride_booking",
    "uber_eats",
    "driver_issue",
    "lost_item",
    "account_login",
    "fraud_security",
    "fare_charge",
    "other",
    "support_followup",
    "ride_cancellation",
    "support_followup",
    "driver_issue",
    "fare_charge",
    "refund",
    "account_privacy",
    "lost_item",
    "location_issue",
    "driver_issue"
]

# Add labels to the first 19 rows
sample.loc[:18, "intent"] = labels

# Check
print(sample[["text_customer", "intent"]].head(19).to_string(index=False))

                                                                                                                                                                                                                                                         text_customer            intent
                                                                                                                                                                                        @Uber_Support My colleague has completed 75 trips and no credit has been added  promotion_credit
                                                                                                                                                                                                                                @115873 cant book a ride when u need.😑      ride_booking
                                                                                                                 @115877 @115873 So to conclude this hangry rant, the avocado on my order had browned by the time it got here from 4 blocks away after a 1 hour drive.         uber_eats
                                                                                                                                                     @115873 yooooo. Uber drivers using intimidation to get tips on the app and cash. Thanks for ruining my night out.      driver_issue
                                                                                                                                                                         @115873 help ASAP lost my wallet in my ride 10 minutes ago please call me DM me for my number         lost_item
                                                                                                                                                                                                          @Uber_Support how to report problems faced by me while login     account_login
                                                                                                                          @131077 @131077 sorry but this is urgent someone is using my detaila/account for fraud via Uber I've tried emailing but no response. HELP !!    fraud_security
                                      @116288 @115873 @Uber_Support - I took Uber but my driver did not stop the ride and now my bill is 5 times of the estimated bill.I tried to contact Uber via support but did not get reply since 2 days. https://t.co/PupMJm5XsB       fare_charge
                                                                                                                                                                                                                                  @Uber_Support ironically, it's #IDPD             other
                                                                                                                                                                            @Uber_Support I have sent you my details. This is unbelievable! Not the first time either.  support_followup
                                                                                                                           @Uber_Support Never Go with Uber, Drivers are cancelling the scheduled trips as well in the last minute.. Terrrible exp with so much loss.. ride_cancellation
                                                                                                                                                     @Uber_Support I already did that! More then once and also like a month ago! And still no reply from Uber support!  support_followup
                                                                                                                                                                                                    @115873 See how your driver runs away !!!! https://t.co/QZ6M1vWQtb      driver_issue
                                                                                                                                                      @115873 please remove the 1k charge on my account. The driver never showed up and I didn't take the ride. Thanks       fare_charge
                                                                                                                                              @Uber_Support I already did twice. I guess it'll be @115879 from now on. I would like a refund asap. Terrible experience            refund
@Uber_Support It’s not my account I don’t have an Uber account I am speaking to you on behalf of my friend.  She gave me the drivers information I wanted to bring this up to you. Can I give u the drivers information? I did a full background check on your driver.   account_privacy
                                                                                                                                          @Uber_Support hey my mom left her phone in a car from early this morning and doesn’t have a way to get it back. Can you help         lost_item
                                                                                                                                                                                            @119720 it seems I am region blocked to California.....but I’m near DC...😮    location_issue
                                                                                                                                                                                      @Uber_Support Driver details attached in the screen shot https://t.co/HVIZT1rfWW      driver_issue

In [30]:
# Interactive intent labelling tool

intents = [
    "promotion_credit",
    "ride_booking",
    "uber_eats",
    "driver_issue",
    "lost_item",
    "account_login",
    "fraud_security",
    "fare_charge",
    "support_followup",
    "ride_cancellation",
    "refund",
    "account_privacy",
    "location_issue",
    "driver_metrics",
    "other"
]

# Start from the first unlabeled row
for i in range(len(sample)):

    # Skip rows we've already labelled
    if pd.notna(sample.loc[i, "intent"]):
        continue

    print("\n" + "=" * 80)
    print(f"Example {i+1} of {len(sample)}")
    print("=" * 80)
    print("\nCUSTOMER:")
    print(sample.loc[i, "text_customer"])

    print("\nChoose an intent:")
    for n, intent in enumerate(intents, 1):
        print(f"{n}. {intent}")

    choice = input("\nEnter number (or 'q' to stop): ")

    if choice.lower() == "q":
        break

    try:
        choice = int(choice)

        if 1 <= choice <= len(intents):
            sample.loc[i, "intent"] = intents[choice - 1]
            print(f"✓ Labelled as: {intents[choice - 1]}")
        else:
            print("Invalid choice. Try again.")

    except ValueError:
        print("Please enter a number.")

In [27]:
# Make the 300-example sample reproducibly split into
# development and golden evaluation sets.

sample = sample.sample(frac=1, random_state=42).reset_index(drop=True)

dev_set = sample.iloc[:100].copy()
golden_set = sample.iloc[100:300].copy()

print("Development set:", len(dev_set))
print("Golden evaluation set:", len(golden_set))

Development set: 100
Golden evaluation set: 200

In [28]:
dev_set.to_csv("../data/uber_dev_set.csv", index=False)

golden_set.to_csv("../data/uber_golden_set.csv", index=False)

print("Saved both datasets.")

Saved both datasets.

In [31]:
for i in range(len(dev_set)):

    print("\n" + "=" * 70)
    print(f"Example {i+1}/{len(dev_set)}")
    print("=" * 70)

    print("\nCUSTOMER:")
    print(dev_set.loc[i, "text_customer"])

    print("\nChoose intent:")
    for j, intent in enumerate(intents, 1):
        print(f"{j}. {intent}")

    choice = int(input("\nYour choice: "))

    dev_set.loc[i, "intent"] = intents[choice - 1]

dev_set.to_csv("../data/uber_dev_set.csv", index=False)

======================================================================
Example 1/100
======================================================================

CUSTOMER:
@131434 @Uber_Support can you help on this?

Choose intent:
1. promotion_credit
2. ride_booking
3. uber_eats
4. driver_issue
5. lost_item
6. account_login
7. fraud_security
8. fare_charge
9. support_followup
10. ride_cancellation
11. refund
12. account_privacy
13. location_issue
14. driver_metrics
15. other

======================================================================
Example 2/100
======================================================================

CUSTOMER:
@Uber_Support how do I delete my account? Looked everywhere and couldn't find the option

Choose intent:
1. promotion_credit
2. ride_booking
3. uber_eats
4. driver_issue
5. lost_item
6. account_login
7. fraud_security
8. fare_charge
9. support_followup
10. ride_cancellation
11. refund
12. account_privacy
13. location_issue
14. driver_metrics
15. other

======================================================================
Example 3/100
======================================================================

CUSTOMER:
@Uber_Support How is it that I take a few days off and my acceptance rate goes down 4 points????

Choose intent:
1. promotion_credit
2. ride_booking
3. uber_eats
4. driver_issue
5. lost_item
6. account_login
7. fraud_security
8. fare_charge
9. support_followup
10. ride_cancellation
11. refund
12. account_privacy
13. location_issue
14. driver_metrics
15. other

======================================================================
Example 4/100
======================================================================

CUSTOMER:
@Uber_Support I have sent you my details. This is unbelievable! Not the first time either.

Choose intent:
1. promotion_credit
2. ride_booking
3. uber_eats
4. driver_issue
5. lost_item
6. account_login
7. fraud_security
8. fare_charge
9. support_followup
10. ride_cancellation
11. refund
12. account_privacy
13. location_issue
14. driver_metrics
15. other

======================================================================
Example 5/100
======================================================================

CUSTOMER:
@115873 no longer value for money ride

Choose intent:
1. promotion_credit
2. ride_booking
3. uber_eats
4. driver_issue
5. lost_item
6. account_login
7. fraud_security
8. fare_charge
9. support_followup
10. ride_cancellation
11. refund
12. account_privacy
13. location_issue
14. driver_metrics
15. other

======================================================================
Example 6/100
======================================================================

CUSTOMER:
@Uber_Support £70 for 2 wrappers on the floor of the car is an absolute DISGRACE ? Surely this just not cause the car to be ‘cleaned’ https://t.co/NA0kXxhBMa

Choose intent:
1. promotion_credit
2. ride_booking
3. uber_eats
4. driver_issue
5. lost_item
6. account_login
7. fraud_security
8. fare_charge
9. support_followup
10. ride_cancellation
11. refund
12. account_privacy
13. location_issue
14. driver_metrics
15. other

======================================================================
Example 7/100
======================================================================

CUSTOMER:
@Uber_Support While I book the cab charges was showing 125 after completing the trip it's showing 188 # why you people cheated customers# I Will never go

Choose intent:
1. promotion_credit
2. ride_booking
3. uber_eats
4. driver_issue
5. lost_item
6. account_login
7. fraud_security
8. fare_charge
9. support_followup
10. ride_cancellation
11. refund
12. account_privacy
13. location_issue
14. driver_metrics
15. other

======================================================================
Example 8/100
======================================================================

CUSTOMER:
@Uber_Support is there any expected time for the @115877 app to be back up?

Choose intent:
1. promotion_credit
2. ride_booking
3. uber_eats
4. driver_issue
5. lost_item
6. account_login
7. fraud_security
8. fare_charge
9. support_followup
10. ride_cancellation
11. refund
12. account_privacy
13. location_issue
14. driver_metrics
15. other

======================================================================
Example 9/100
======================================================================

CUSTOMER:
@Uber_Support how to report problems faced by me while login

Choose intent:
1. promotion_credit
2. ride_booking
3. uber_eats
4. driver_issue
5. lost_item
6. account_login
7. fraud_security
8. fare_charge
9. support_followup
10. ride_cancellation
11. refund
12. account_privacy
13. location_issue
14. driver_metrics
15. other

======================================================================
Example 10/100
======================================================================

CUSTOMER:
Ran around like a headless chicken to get ready, only to watch your @115873 car reverse away from your house on the wee map. #2017Life

Choose intent:
1. promotion_credit
2. ride_booking
3. uber_eats
4. driver_issue
5. lost_item
6. account_login
7. fraud_security
8. fare_charge
9. support_followup
10. ride_cancellation
11. refund
12. account_privacy
13. location_issue
14. driver_metrics
15. other

======================================================================
Example 11/100
======================================================================

CUSTOMER:
Left my whole wallet in an @115873 and my driver verfied to Uber that she found it but hasn’t called me and won’t pick up the phone 🙃🙃

Choose intent:
1. promotion_credit
2. ride_booking
3. uber_eats
4. driver_issue
5. lost_item
6. account_login
7. fraud_security
8. fare_charge
9. support_followup
10. ride_cancellation
11. refund
12. account_privacy
13. location_issue
14. driver_metrics
15. other

======================================================================
Example 12/100
======================================================================

CUSTOMER:
@Uber_Support .. Shocked to see that in Kolkata, we need to bear the parking fee at Howrah Station. #NotHappy .. I would rather have boarded the yellow Taxi.

Choose intent:
1. promotion_credit
2. ride_booking
3. uber_eats
4. driver_issue
5. lost_item
6. account_login
7. fraud_security
8. fare_charge
9. support_followup
10. ride_cancellation
11. refund
12. account_privacy
13. location_issue
14. driver_metrics
15. other

======================================================================
Example 13/100
======================================================================

CUSTOMER:
While driving for @115873 I found a checkbook with a blank check and an iPhone. @115873 helped me  return the items to the owners.  #service

Choose intent:
1. promotion_credit
2. ride_booking
3. uber_eats
4. driver_issue
5. lost_item
6. account_login
7. fraud_security
8. fare_charge
9. support_followup
10. ride_cancellation
11. refund
12. account_privacy
13. location_issue
14. driver_metrics
15. other

======================================================================
Example 14/100
======================================================================

CUSTOMER:
@Uber_Support Did you even take time to see my issue or no?

Choose intent:
1. promotion_credit
2. ride_booking
3. uber_eats
4. driver_issue
5. lost_item
6. account_login
7. fraud_security
8. fare_charge
9. support_followup
10. ride_cancellation
11. refund
12. account_privacy
13. location_issue
14. driver_metrics
15. other

======================================================================
Example 15/100
======================================================================

CUSTOMER:
@Uber_Support my instant pay is not working. It is giving me an error message that says I need to make over 25 trips. I have some 200

Choose intent:
1. promotion_credit
2. ride_booking
3. uber_eats
4. driver_issue
5. lost_item
6. account_login
7. fraud_security
8. fare_charge
9. support_followup
10. ride_cancellation
11. refund
12. account_privacy
13. location_issue
14. driver_metrics
15. other

======================================================================
Example 16/100
======================================================================

CUSTOMER:
@Uber_Support - The driver drove away with my suitcase in the boot and this is what you call premier service? Since it impossible to contact you folks am resorting to this https://t.co/0vVZw3mskS

Choose intent:
1. promotion_credit
2. ride_booking
3. uber_eats
4. driver_issue
5. lost_item
6. account_login
7. fraud_security
8. fare_charge
9. support_followup
10. ride_cancellation
11. refund
12. account_privacy
13. location_issue
14. driver_metrics
15. other

======================================================================
Example 17/100
======================================================================

CUSTOMER:
@Uber_Support took a cab y'day Eve, while booking after promo code fare showed 79, was charged 101.why the difference.pls refund excess amt. Escalated on app as well. M9810105767, Ajay

Choose intent:
1. promotion_credit
2. ride_booking
3. uber_eats
4. driver_issue
5. lost_item
6. account_login
7. fraud_security
8. fare_charge
9. support_followup
10. ride_cancellation
11. refund
12. account_privacy
13. location_issue
14. driver_metrics
15. other

======================================================================
Example 18/100
======================================================================

CUSTOMER:
@Uber_Support I lost my phone in my Uber last night and can't get hold of my driver because I need to provide a phone number which is in it.

Choose intent:
1. promotion_credit
2. ride_booking
3. uber_eats
4. driver_issue
5. lost_item
6. account_login
7. fraud_security
8. fare_charge
9. support_followup
10. ride_cancellation
11. refund
12. account_privacy
13. location_issue
14. driver_metrics
15. other

======================================================================
Example 19/100
======================================================================

CUSTOMER:
@Uber_Support drvrs need 2 be educated on airport pickup, @ DFW drvr called 2 ask what terminal and what gate b4 moving, I told the app that

Choose intent:
1. promotion_credit
2. ride_booking
3. uber_eats
4. driver_issue
5. lost_item
6. account_login
7. fraud_security
8. fare_charge
9. support_followup
10. ride_cancellation
11. refund
12. account_privacy
13. location_issue
14. driver_metrics
15. other

======================================================================
Example 20/100
======================================================================

CUSTOMER:
@Uber_Support How do you determine nearby as in "driver completing ride nearby?" Last might my driver was completing a ride almost a mile away but was allowed to accept my ride request.

Choose intent:
1. promotion_credit
2. ride_booking
3. uber_eats
4. driver_issue
5. lost_item
6. account_login
7. fraud_security
8. fare_charge
9. support_followup
10. ride_cancellation
11. refund
12. account_privacy
13. location_issue
14. driver_metrics
15. other

======================================================================
Example 21/100
======================================================================

CUSTOMER:
@Uber_Support I need help with my account but don't know where to go to get answers.   My account is showing my car info twice- when I try to log in it tells me items have expired when they haven't.  What do I do?

Choose intent:
1. promotion_credit
2. ride_booking
3. uber_eats
4. driver_issue
5. lost_item
6. account_login
7. fraud_security
8. fare_charge
9. support_followup
10. ride_cancellation
11. refund
12. account_privacy
13. location_issue
14. driver_metrics
15. other

======================================================================
Example 22/100
======================================================================

CUSTOMER:
@115877  charged my account, cancelled my order and still no refund !

Choose intent:
1. promotion_credit
2. ride_booking
3. uber_eats
4. driver_issue
5. lost_item
6. account_login
7. fraud_security
8. fare_charge
9. support_followup
10. ride_cancellation
11. refund
12. account_privacy
13. location_issue
14. driver_metrics
15. other

======================================================================
Example 23/100
======================================================================

CUSTOMER:
@528920 @115873 says it'll be there in 5 mins, the driver decides to leave after failing to find the spot I told him I'd be (and he confirmed he'd be there)

Choose intent:
1. promotion_credit
2. ride_booking
3. uber_eats
4. driver_issue
5. lost_item
6. account_login
7. fraud_security
8. fare_charge
9. support_followup
10. ride_cancellation
11. refund
12. account_privacy
13. location_issue
14. driver_metrics
15. other

======================================================================
Example 24/100
======================================================================

CUSTOMER:
@Uber_Support I do truly understand...absolutely..but I really would like to know their email address so I can make sure it is not blocked or spammed

Choose intent:
1. promotion_credit
2. ride_booking
3. uber_eats
4. driver_issue
5. lost_item
6. account_login
7. fraud_security
8. fare_charge
9. support_followup
10. ride_cancellation
11. refund
12. account_privacy
13. location_issue
14. driver_metrics
15. other

======================================================================
Example 25/100
======================================================================

CUSTOMER:
@Uber_Support What happened no one support me till now I'm very sorry to see uber do that type of behave with customer ola company is far better than you in supporting matter 2 nd month is going on I didn't get payment from uber

Choose intent:
1. promotion_credit
2. ride_booking
3. uber_eats
4. driver_issue
5. lost_item
6. account_login
7. fraud_security
8. fare_charge
9. support_followup
10. ride_cancellation
11. refund
12. account_privacy
13. location_issue
14. driver_metrics
15. other

======================================================================
Example 26/100
======================================================================

CUSTOMER:
@Uber_Support Ive been having issues with a driver who is literally driving away from the pick up, a phone number and the UK support isn't eveb bothering to reply :)

Choose intent:
1. promotion_credit
2. ride_booking
3. uber_eats
4. driver_issue
5. lost_item
6. account_login
7. fraud_security
8. fare_charge
9. support_followup
10. ride_cancellation
11. refund
12. account_privacy
13. location_issue
14. driver_metrics
15. other

======================================================================
Example 27/100
======================================================================

CUSTOMER:
. @115873 drivers are the worse. https://t.co/yHfBb1EtOL

Choose intent:
1. promotion_credit
2. ride_booking
3. uber_eats
4. driver_issue
5. lost_item
6. account_login
7. fraud_security
8. fare_charge
9. support_followup
10. ride_cancellation
11. refund
12. account_privacy
13. location_issue
14. driver_metrics
15. other

======================================================================
Example 28/100
======================================================================

CUSTOMER:
@Uber_Support I got locked out of my old account and Your system won't let me use my card on the new account. Help :(

Choose intent:
1. promotion_credit
2. ride_booking
3. uber_eats
4. driver_issue
5. lost_item
6. account_login
7. fraud_security
8. fare_charge
9. support_followup
10. ride_cancellation
11. refund
12. account_privacy
13. location_issue
14. driver_metrics
15. other

======================================================================
Example 29/100
======================================================================

CUSTOMER:
@Uber_Support I have a balance on my account that I cannot transfer to my bank account or debit card can someone help me please, I haven't gotten a response since 11/27/17

Choose intent:
1. promotion_credit
2. ride_booking
3. uber_eats
4. driver_issue
5. lost_item
6. account_login
7. fraud_security
8. fare_charge
9. support_followup
10. ride_cancellation
11. refund
12. account_privacy
13. location_issue
14. driver_metrics
15. other

======================================================================
Example 30/100
======================================================================

CUSTOMER:
@Uber_Support https://t.co/FTlKBpVhfS

Choose intent:
1. promotion_credit
2. ride_booking
3. uber_eats
4. driver_issue
5. lost_item
6. account_login
7. fraud_security
8. fare_charge
9. support_followup
10. ride_cancellation
11. refund
12. account_privacy
13. location_issue
14. driver_metrics
15. other

======================================================================
Example 31/100
======================================================================

CUSTOMER:
@119720 it seems I am region blocked to California.....but I’m near DC...😮

Choose intent:
1. promotion_credit
2. ride_booking
3. uber_eats
4. driver_issue
5. lost_item
6. account_login
7. fraud_security
8. fare_charge
9. support_followup
10. ride_cancellation
11. refund
12. account_privacy
13. location_issue
14. driver_metrics
15. other

======================================================================
Example 32/100
======================================================================

CUSTOMER:
We are going to St. Lukes for my Aunt’s PET SCAN but your driver didn’t bother to call us what happened. Calling #LTFRB @115873 @Uber_Support https://t.co/uzefvadH8j

Choose intent:
1. promotion_credit
2. ride_booking
3. uber_eats
4. driver_issue
5. lost_item
6. account_login
7. fraud_security
8. fare_charge
9. support_followup
10. ride_cancellation
11. refund
12. account_privacy
13. location_issue
14. driver_metrics
15. other

======================================================================
Example 33/100
======================================================================

CUSTOMER:
@Uber_Support I'm in Las Vegas how do I get an Uber Pass?

Choose intent:
1. promotion_credit
2. ride_booking
3. uber_eats
4. driver_issue
5. lost_item
6. account_login
7. fraud_security
8. fare_charge
9. support_followup
10. ride_cancellation
11. refund
12. account_privacy
13. location_issue
14. driver_metrics
15. other

======================================================================
Example 34/100
======================================================================

CUSTOMER:
@Uber_Support No one has got in contact with me yet

Choose intent:
1. promotion_credit
2. ride_booking
3. uber_eats
4. driver_issue
5. lost_item
6. account_login
7. fraud_security
8. fare_charge
9. support_followup
10. ride_cancellation
11. refund
12. account_privacy
13. location_issue
14. driver_metrics
15. other

======================================================================
Example 35/100
======================================================================

CUSTOMER:
@Uber_Support  i already made the payment on one of my trip via Paytm to driver and it still shows me that you haven't made the payment

Choose intent:
1. promotion_credit
2. ride_booking
3. uber_eats
4. driver_issue
5. lost_item
6. account_login
7. fraud_security
8. fare_charge
9. support_followup
10. ride_cancellation
11. refund
12. account_privacy
13. location_issue
14. driver_metrics
15. other

======================================================================
Example 36/100
======================================================================

CUSTOMER:
@Uber_Support I didn't get any acknowledgement for the request that I submitted shall I expect reply from you

Choose intent:
1. promotion_credit
2. ride_booking
3. uber_eats
4. driver_issue
5. lost_item
6. account_login
7. fraud_security
8. fare_charge
9. support_followup
10. ride_cancellation
11. refund
12. account_privacy
13. location_issue
14. driver_metrics

In [32]:
dev_set.to_csv("../data/uber_dev_set.csv", index=False)

In [33]:
print(dev_set["intent"].value_counts())

intent
support_followup     24
fare_charge          15
driver_issue         14
uber_eats             9
lost_item             8
account_login         6
other                 6
ride_booking          5
location_issue        3
driver_metrics        2
promotion_credit      2
fraud_security        2
ride_cancellation     2
refund                2
Name: count, dtype: int64

In [34]:
intent_mapping = {
    "promotion_credit": "benefits_other",
    "ride_booking": "ride_booking_cancellation",
    "uber_eats": "uber_eats",
    "driver_issue": "driver_issue",
    "lost_item": "lost_item",
    "account_login": "account_access_security",
    "fraud_security": "account_access_security",
    "fare_charge": "fare_charge",
    "support_followup": "support_followup",
    "ride_cancellation": "ride_booking_cancellation",
    "refund": "refund",
    "account_privacy": "account_access_security",
    "location_issue": "location_app_issue",
    "driver_metrics": "driver_metrics",
    "other": "benefits_other"
}

dev_set["intent_final"] = dev_set["intent"].map(intent_mapping)

print(dev_set["intent_final"].value_counts())

intent_final
support_followup             24
fare_charge                  15
driver_issue                 14
uber_eats                     9
account_access_security       8
benefits_other                8
lost_item                     8
ride_booking_cancellation     7
location_app_issue            3
driver_metrics                2
refund                        2
Name: count, dtype: int64

In [35]:
dev_set.to_csv("../data/uber_dev_set.csv", index=False)

In [36]:
print(dev_set[["text_customer", "intent", "intent_final"]].head(20))

                                        text_customer            intent  \
0         @131434 @Uber_Support can you help on this?  support_followup
1   @Uber_Support how do I delete my account? Look...     account_login
2   @Uber_Support How is it that I take a few days...    driver_metrics
3   @Uber_Support I have sent you my details. This...  support_followup
4              @115873 no longer value for money ride       fare_charge
5   @Uber_Support £70 for 2 wrappers on the floor ...       fare_charge
6   @Uber_Support While I book the cab charges was...       fare_charge
7   @Uber_Support is there any expected time for t...             other
8   @Uber_Support how to report problems faced by ...     account_login
9   Ran around like a headless chicken to get read...      driver_issue
10  Left my whole wallet in an @115873 and my driv...      driver_issue
11  @Uber_Support .. Shocked to see that in Kolkat...       fare_charge
12  While driving for @115873 I found a checkbook ...         lost_item
13  @Uber_Support Did you even take time to see my...  support_followup
14  @Uber_Support my instant pay is not working. I...    driver_metrics
15  @Uber_Support - The driver drove away with my ...         lost_item
16  @Uber_Support took a cab y'day Eve, while book...         lost_item
17  @Uber_Support I lost my phone in my Uber last ...         lost_item
18  @Uber_Support drvrs need 2 be educated on airp...      driver_issue
19  @Uber_Support How do you determine nearby as i...      ride_booking

                 intent_final
0            support_followup
1     account_access_security
2              driver_metrics
3            support_followup
4                 fare_charge
5                 fare_charge
6                 fare_charge
7              benefits_other
8     account_access_security
9                driver_issue
10               driver_issue
11                fare_charge
12                  lost_item
13           support_followup
14             driver_metrics
15                  lost_item
16                  lost_item
17                  lost_item
18               driver_issue
19  ride_booking_cancellation

In [37]:
print(dev_set["intent_final"].value_counts())

intent_final
support_followup             24
fare_charge                  15
driver_issue                 14
uber_eats                     9
account_access_security       8
benefits_other                8
lost_item                     8
ride_booking_cancellation     7
location_app_issue            3
driver_metrics                2
refund                        2
Name: count, dtype: int64

In [38]:
dev_set["intent"] = dev_set["intent_final"]
dev_set = dev_set.drop(columns=["intent_final"])

dev_set.to_csv("../data/uber_dev_set.csv", index=False)

In [39]:
print(dev_set.columns)
print(dev_set["intent"].value_counts())

Index(['text_customer', 'text_uber', 'intent'], dtype='str')
intent
support_followup             24
fare_charge                  15
driver_issue                 14
uber_eats                     9
account_access_security       8
benefits_other                8
lost_item                     8
ride_booking_cancellation     7
location_app_issue            3
driver_metrics                2
refund                        2
Name: count, dtype: int64

In [40]:
# Get customer tweets that have a matched Uber response
golden_pool = uber_pairs[
    ["text_customer", "text_uber"]
].dropna().drop_duplicates(subset=["text_customer"])

# Remove anything already used in the dev set
golden_pool = golden_pool[
    ~golden_pool["text_customer"].isin(dev_set["text_customer"])
]

# Randomly select 200 fresh examples
golden_set = golden_pool.sample(
    n=200,
    random_state=123
).reset_index(drop=True)

print("Golden set shape:", golden_set.shape)
print(golden_set.head())

Golden set shape: (200, 2)
                                       text_customer  \
0  @Uber_Support Yo what’s with this $300 charge?...
1  @Uber_Support The link takes me to driver supp...
2  @Uber_Support Cancellation is fine. He didn't ...
3  @115873 can someone please explain to me how I...
4  @Uber_Support why is it that I get fined $5 if...

                                           text_uber
0  @233326 We apologize for the trouble! Send us ...
1  @694280 Sorry for that, Olivia! Please send us...
2  @650736 Please connect with us at https://t.co...
3  @396222 We're here to help. We just sent you a...
4  @376388 Here to help! Please send us a note vi...

In [41]:
golden_set["intent"] = ""
golden_set["escalate"] = ""

In [42]:
golden_set.to_csv(
    "../data/uber_golden_set.csv",
    index=False
)

In [43]:
intents_final = [
    "support_followup",
    "fare_charge",
    "driver_issue",
    "uber_eats",
    "lost_item",
    "account_access_security",
    "benefits_other",
    "ride_booking_cancellation",
    "location_app_issue",
    "driver_metrics",
    "refund"
]

In [44]:
print(intents_final)
print(len(intents_final))

['support_followup', 'fare_charge', 'driver_issue', 'uber_eats', 'lost_item', 'account_access_security', 'benefits_other', 'ride_booking_cancellation', 'location_app_issue', 'driver_metrics', 'refund']
11

In [46]:
golden_set["escalate"] = golden_set["escalate"].astype(object)

In [47]:
for i in range(len(golden_set)):

    print("\n" + "=" * 70)
    print(f"Example {i+1}/{len(golden_set)}")
    print("=" * 70)

    print("\nCUSTOMER:")
    print(golden_set.loc[i, "text_customer"])

    print("\nChoose intent:")
    for j, intent in enumerate(intents_final, 1):
        print(f"{j}. {intent}")

    choice = int(input("\nIntent: "))
    golden_set.loc[i, "intent"] = intents_final[choice - 1]

    escalation = input("Escalate? (y/n): ").strip().lower()

    while escalation not in ["y", "n"]:
        escalation = input("Please enter y or n: ").strip().lower()

    golden_set.loc[i, "escalate"] = escalation == "y"

golden_set.to_csv("../data/uber_golden_set.csv", index=False)

======================================================================
Example 1/200
======================================================================

CUSTOMER:
@Uber_Support Yo what’s with this $300 charge? I needed an Uber and this Uber driver never even showed to pick me up? How am I getting charged for 1. A ride I never took &amp; 2. A mess I couldn’t have made. Tried to make a simple correction and then y’all charged me more?? https://t.co/DUtC7SKKut

Choose intent:
1. support_followup
2. fare_charge
3. driver_issue
4. uber_eats
5. lost_item
6. account_access_security
7. benefits_other
8. ride_booking_cancellation
9. location_app_issue
10. driver_metrics
11. refund

======================================================================
Example 2/200
======================================================================

CUSTOMER:
@Uber_Support The link takes me to driver support?

Choose intent:
1. support_followup
2. fare_charge
3. driver_issue
4. uber_eats
5. lost_item
6. account_access_security
7. benefits_other
8. ride_booking_cancellation
9. location_app_issue
10. driver_metrics
11. refund

======================================================================
Example 3/200
======================================================================

CUSTOMER:
@Uber_Support Cancellation is fine. He didn't even brother to notify me . I called him myself.

Choose intent:
1. support_followup
2. fare_charge
3. driver_issue
4. uber_eats
5. lost_item
6. account_access_security
7. benefits_other
8. ride_booking_cancellation
9. location_app_issue
10. driver_metrics
11. refund

======================================================================
Example 4/200
======================================================================

CUSTOMER:
@115873 can someone please explain to me how I can get ahold of uber I tried to email I'm not getting any responses back at all

Choose intent:
1. support_followup
2. fare_charge
3. driver_issue
4. uber_eats
5. lost_item
6. account_access_security
7. benefits_other
8. ride_booking_cancellation
9. location_app_issue
10. driver_metrics
11. refund

======================================================================
Example 5/200
======================================================================

CUSTOMER:
@Uber_Support why is it that I get fined $5 if I cancel an Uber but get nothing in return when one wastes 15 minutes of my time...

Choose intent:
1. support_followup
2. fare_charge
3. driver_issue
4. uber_eats
5. lost_item
6. account_access_security
7. benefits_other
8. ride_booking_cancellation
9. location_app_issue
10. driver_metrics
11. refund

======================================================================
Example 6/200
======================================================================

CUSTOMER:
@162763 @115877 @148768 same!!! three ppl in my office have had it cancelled :/

Choose intent:
1. support_followup
2. fare_charge
3. driver_issue
4. uber_eats
5. lost_item
6. account_access_security
7. benefits_other
8. ride_booking_cancellation
9. location_app_issue
10. driver_metrics
11. refund

======================================================================
Example 7/200
======================================================================

CUSTOMER:
@Uber_Support What's a good EMAIL addy to reach out for support for an issue I cant find amongst the options on web or app please? Thanks!

Choose intent:
1. support_followup
2. fare_charge
3. driver_issue
4. uber_eats
5. lost_item
6. account_access_security
7. benefits_other
8. ride_booking_cancellation
9. location_app_issue
10. driver_metrics
11. refund

======================================================================
Example 8/200
======================================================================

CUSTOMER:
@115877 Justice https://t.co/paIRt3qAIf

Choose intent:
1. support_followup
2. fare_charge
3. driver_issue
4. uber_eats
5. lost_item
6. account_access_security
7. benefits_other
8. ride_booking_cancellation
9. location_app_issue
10. driver_metrics
11. refund

======================================================================
Example 9/200
======================================================================

CUSTOMER:
I had an awful experience with @115873 tonight, @Uber_Support. A driver left me stood out in the rain for ages, ignored my attempts to contact him and then cancelled my ride -- AND *I* GET A £4 BLOODY CANCELLATION FEE?! Absolutely unfair.

Choose intent:
1. support_followup
2. fare_charge
3. driver_issue
4. uber_eats
5. lost_item
6. account_access_security
7. benefits_other
8. ride_booking_cancellation
9. location_app_issue
10. driver_metrics
11. refund

======================================================================
Example 10/200
======================================================================

CUSTOMER:
@Uber_Support @115873  How is this fare to a customer... to charge them $180.66 for a 10 min ride... the original price was $11.33... https://t.co/fPUPOYffNX

Choose intent:
1. support_followup
2. fare_charge
3. driver_issue
4. uber_eats
5. lost_item
6. account_access_security
7. benefits_other
8. ride_booking_cancellation
9. location_app_issue
10. driver_metrics
11. refund

======================================================================
Example 11/200
======================================================================

CUSTOMER:
@Uber_Support My black food bag got stolen. Went all the way to remote roseville mn greenlight and greeter said they never carried them.

Choose intent:
1. support_followup
2. fare_charge
3. driver_issue
4. uber_eats
5. lost_item
6. account_access_security
7. benefits_other
8. ride_booking_cancellation
9. location_app_issue
10. driver_metrics
11. refund

======================================================================
Example 12/200
======================================================================

CUSTOMER:
@Uber_Support Thats not an acceptable answer to an ongoing critical safety issue. This happens thousands of times a day just on the Boston region.

Choose intent:
1. support_followup
2. fare_charge
3. driver_issue
4. uber_eats
5. lost_item
6. account_access_security
7. benefits_other
8. ride_booking_cancellation
9. location_app_issue
10. driver_metrics
11. refund

======================================================================
Example 13/200
======================================================================

CUSTOMER:
@115873 outrageous you have just charged me 5 pounds for a cancelled ride and we will waiting for you!

Choose intent:
1. support_followup
2. fare_charge
3. driver_issue
4. uber_eats
5. lost_item
6. account_access_security
7. benefits_other
8. ride_booking_cancellation
9. location_app_issue
10. driver_metrics
11. refund

======================================================================
Example 14/200
======================================================================

CUSTOMER:
Wish I could give Uber drivers 5 stars while simultaneously giving the @Uber_Support app a 0 star rating for giving the wrong directions 🙄

Choose intent:
1. support_followup
2. fare_charge
3. driver_issue
4. uber_eats
5. lost_item
6. account_access_security
7. benefits_other
8. ride_booking_cancellation
9. location_app_issue
10. driver_metrics
11. refund

======================================================================
Example 15/200
======================================================================

CUSTOMER:
@Uber_Support, Can't log into my or husband's account because neither your SMS or Voice 2 Factor are working. Now what?

Choose intent:
1. support_followup
2. fare_charge
3. driver_issue
4. uber_eats
5. lost_item
6. account_access_security
7. benefits_other
8. ride_booking_cancellation
9. location_app_issue
10. driver_metrics
11. refund

======================================================================
Example 16/200
======================================================================

CUSTOMER:
@Uber_Support hi I received the Ride Pass email and have used it in the past but it is not showing in the app

Choose intent:
1. support_followup
2. fare_charge
3. driver_issue
4. uber_eats
5. lost_item
6. account_access_security
7. benefits_other
8. ride_booking_cancellation
9. location_app_issue
10. driver_metrics
11. refund

======================================================================
Example 17/200
======================================================================

CUSTOMER:
Waiting 15 min for an @115873 at LGA? Wtf?? Might as well just grab a taxi... #NYC

Choose intent:
1. support_followup
2. fare_charge
3. driver_issue
4. uber_eats
5. lost_item
6. account_access_security
7. benefits_other
8. ride_booking_cancellation
9. location_app_issue
10. driver_metrics
11. refund

======================================================================
Example 18/200
======================================================================

CUSTOMER:
@Uber_Support We tried @9150 o'clock. Little upset it wasn't working for an hour.

Choose intent:
1. support_followup
2. fare_charge
3. driver_issue
4. uber_eats
5. lost_item
6. account_access_security
7. benefits_other
8. ride_booking_cancellation
9. location_app_issue
10. driver_metrics
11. refund

======================================================================
Example 19/200
======================================================================

CUSTOMER:
@Uber_Support I got a thank you for advising you of the issue with my ride.I guess that's it.If only you were @115821-they know support.

Choose intent:
1. support_followup
2. fare_charge
3. driver_issue
4. uber_eats
5. lost_item
6. account_access_security
7. benefits_other
8. ride_booking_cancellation
9. location_app_issue
10. driver_metrics
11. refund

======================================================================
Example 20/200
======================================================================

CUSTOMER:
@Uber_Support
i received an email saying my insurance I applied with is expired. Like i told the representative yesterday, that is the EFFECTIVE date not the expiration date

Choose intent:
1. support_followup
2. fare_charge
3. driver_issue
4. uber_eats
5. lost_item
6. account_access_security
7. benefits_other
8. ride_booking_cancellation
9. location_app_issue
10. driver_metrics
11. refund

======================================================================
Example 21/200
======================================================================

CUSTOMER:
@Uber_Support I am not able to request a ride.My mail is __email__ message directing me to contact uber help. https://t.co/JZCRpsBGnn

Choose intent:
1. support_followup
2. fare_charge
3. driver_issue
4. uber_eats
5. lost_item
6. account_access_security
7. benefits_other
8. ride_booking_cancellation
9. location_app_issue
10. driver_metrics
11. refund

======================================================================
Example 22/200
======================================================================

CUSTOMER:
@Uber_Support I tried going on the link and it's just very confusing and overwhelming for me... I've been online for FOUR hours destination set to the airport... last rider I got was going the complete opposite direction so I had to cancel for him. https://t.co/rJt0LGEHjX

Choose intent:
1. support_followup
2. fare_charge
3. driver_issue
4. uber_eats
5. lost_item
6. account_access_security
7. benefits_other
8. ride_booking_cancellation
9. location_app_issue
10. driver_metrics
11. refund

======================================================================
Example 23/200
======================================================================

CUSTOMER:
@115873 did you decide to loot hyderabad today?have identified 3 cases where u over charged customers today..and what is this new trend of sending a message like u may be charged high and driver will inform?after the trip starts?no traffic jam no waiting no longer route

Choose intent:
1. support_followup
2. fare_charge
3. driver_issue
4. uber_eats
5. lost_item
6. account_access_security
7. benefits_other
8. ride_booking_cancellation
9. location_app_issue
10. driver_metrics
11. refund

======================================================================
Example 24/200
======================================================================

CUSTOMER:
@Uber_Support Ok I have done, but last time I was hacked that support team didn't get back to me for over a week, whilst someone ubered around Glasgow.

Choose intent:
1. support_followup
2. fare_charge
3. driver_issue
4. uber_eats
5. lost_item
6. account_access_security
7. benefits_other
8. ride_booking_cancellation
9. location_app_issue
10. driver_metrics
11. refund

======================================================================
Example 25/200
======================================================================

CUSTOMER:
@115873 @Uber_Support
__email__
Not able to book a ride. Always pop-up a message that visit https://t.co/7lQbjedBQa.
It didn't give me solution. Please aolve my issue asap.
Thanks Team @115873

Choose intent:
1. support_followup
2. fare_charge
3. driver_issue
4. uber_eats
5. lost_item
6. account_access_security
7. benefits_other
8. ride_booking_cancellation
9. location_app_issue
10. driver_metrics
11. refund

======================================================================
Example 26/200
======================================================================

CUSTOMER:
@115877 I need a contact number to make a complaint

Choose intent:
1. support_followup
2. fare_charge
3. driver_issue
4. uber_eats
5. lost_item
6. account_access_security
7. benefits_other
8. ride_booking_cancellation
9. location_app_issue
10. driver_metrics
11. refund

======================================================================
Example 27/200
======================================================================

CUSTOMER:
@115873 has the worst customer service

Choose intent:
1. support_followup
2. fare_charge
3. driver_issue
4. uber_eats
5. lost_item
6. account_access_security
7. benefits_other
8. ride_booking_cancellation
9. location_app_issue
10. driver_metrics
11. refund

======================================================================
Example 28/200
======================================================================

CUSTOMER:
@Uber_Support I deleted all forms of payment and just left gift card as only form of payment so hopefully that will resolve the problem. Thanks

Choose intent:
1. support_followup
2. fare_charge
3. driver_issue
4. uber_eats
5. lost_item
6. account_access_security
7. benefits_other
8. ride_booking_cancellation
9. location_app_issue
10. driver_metrics
11. refund

======================================================================
Example 29/200
======================================================================

CUSTOMER:
So my @115873 driver just got a tude with me bc I have the window down. It smells of shit in here. &amp; I didn’t even complain

Choose intent:
1. support_followup
2. fare_charge
3. driver_issue
4. uber_eats
5. lost_item
6. account_access_security
7. benefits_other
8. ride_booking_cancellation
9. location_app_issue
10. driver_metrics
11. refund

======================================================================
Example 30/200
======================================================================

CUSTOMER:
@Uber_Support My @115877 order just arrived. When I sat down to eat it, another driver called telling me they had my order. Did the vendor fill the order twice or am I gonna be charged twice? What's up with that?

Choose intent:
1. support_followup
2. fare_charge
3. driver_issue
4. uber_eats
5. lost_item
6. account_access_security
7. benefits_other
8. ride_booking_cancellation
9. location_app_issue
10. driver_metrics
11. refund

======================================================================
Example 31/200
======================================================================

CUSTOMER:
@115873 and their Support is... uugghhh @uber_support
maybe I am having incorrect expectations from their support team.

Choose intent:
1. support_followup
2. fare_charge
3. driver_issue
4. uber_eats
5. lost_item
6. account_access_security
7. benefits_other
8. ride_booking_cancellation
9. location_app_issue
10. driver_metrics
11. refund

======================================================================
Example 32/200
======================================================================

CUSTOMER:
@Uber_Support Thanks for telling me what I already knew with that useless support reply &amp; uninformative link. Way to screw up your promo, @175881.

Choose intent:
1. support_followup
2. fare_charge
3. driver_issue
4. uber_eats
5. lost_item
6. account_access_security
7. benefits_other
8. ride_booking_cancellation
9. location_app_issue
10. driver_metrics
11. refund

======================================================================
Example 33/200
======================================================================

CUSTOMER:
@Uber_Support Account holder does not know too much about Internet or technology. Doesn’t remember password or have access to e-mail account. I am assisting her as her brother.

Choose intent:
1. support_followup
2. fare_charge
3. driver_issue
4. uber_eats
5. lost_item
6. account_access_security
7. benefits_other
8. ride_booking_cancellation
9. location_app_issue
10. driver_metrics
11. refund

======================================================================
Example 34/200
======================================================================

CUSTOMER:
@Uber_Support Already raised a case there..pls chk and revert on priority

Choose intent:
1. support_followup
2. fare_charge
3. driver_issue
4. uber_eats
5. lost_item
6. account_access_security
7. benefits_other
8. ride_booking_cancellation
9. location_app_issue
10. driver_metrics
11. refund

======================================================================
Example 35/200
======================================================================

CUSTOMER:
@Uber_Support I sent you my email as DM as you requested so you could follow up. But you have chosen not to

Choose intent:
1. support_followup
2. fare_charge
3. driver_issue
4. uber_eats
5. lost_item
6. account_access_security
7. benefits_other
8. ride_booking_cancellation
9. location_app_issue
10. driver_metrics
11. refund

======================================================================
Example 36/200
======================================================================

CUSTOMER:
@115873 my #uber driver pulled his penis out of his pants and just #peed in a cup WHILE driving!!!!!! I was just #sexuallyassaulted in an uber

Choose intent:
1. support_followup
2. fare_charge
3. driver_issue
4. uber_eats
5. lost_item
6. account_access_security
7. benefits_other
8. ride_booking_cancellation
9. location_app_issue
10. driver_metrics
11. refund

======================================================================
Example 37/200
======================================================================

CUSTOMER:
@Uber_Support can you guys just cancel that order?

Choose intent:
1. support_followup
2. fare_charge
3. driver_issue
4. uber_eats
5. lost_item
6. account_access_security
7. benefits_other
8. ride_booking_cancellation
9. location_app_issue
10. driver_metrics
11. refund

======================================================================
Example 38/200
======================================================================

CUSTOMER:
@115877 The app and the site are down.

Choose intent:
1. support_followup
2. fare_charge
3. driver_issue
4. uber_eats
5. lost_item
6. account_access_security
7. benefits_other
8. ride_booking_cancellation
9. location_app_issue
10. driver_metrics
11. refund

======================================================================
Example 39/200
======================================================================

CUSTOMER:

ValueError: invalid literal for int() with base 10: ''

In [48]:
golden_set.to_csv("../data/uber_golden_set.csv", index=False)

In [49]:
print(golden_set["intent"].replace("", pd.NA).notna().sum())

49

In [50]:
for i in range(len(golden_set)):

    # Skip already labeled examples
    if pd.notna(golden_set.loc[i, "intent"]) and golden_set.loc[i, "intent"] != "":
        continue

    print("\n" + "=" * 70)
    print(f"Example {i+1}/{len(golden_set)}")
    print("=" * 70)

    print("\nCUSTOMER:")
    print(golden_set.loc[i, "text_customer"])

    print("\nChoose intent:")
    for j, intent in enumerate(intents_final, 1):
        print(f"{j}. {intent}")

    while True:
        choice = input("\nIntent: ").strip()

        if choice.isdigit() and 1 <= int(choice) <= len(intents_final):
            choice = int(choice)
            break

        print("Please enter a number from 1 to 11.")

    golden_set.loc[i, "intent"] = intents_final[choice - 1]

    while True:
        escalation = input("Escalate? (y/n): ").strip().lower()

        if escalation in ["y", "n"]:
            break

        print("Please enter y or n.")

    golden_set.loc[i, "escalate"] = escalation == "y"

    # Save after every example
    golden_set.to_csv("../data/uber_golden_set.csv", index=False)

======================================================================
Example 50/200
======================================================================

CUSTOMER:
@115877 @119983 @115873 Received completely wrong order. Complained twice.
Le Uber be like : Thank you for your feedback.
Such a great customer care.
Order 384E6

Choose intent:
1. support_followup
2. fare_charge
3. driver_issue
4. uber_eats
5. lost_item
6. account_access_security
7. benefits_other
8. ride_booking_cancellation
9. location_app_issue
10. driver_metrics
11. refund

======================================================================
Example 51/200
======================================================================

CUSTOMER:
@115873 driver stole my iphone. Tracked for a minute. He turned the phone off and wont answer his phone. Help https://t.co/OBg3jv0DkJ

Choose intent:
1. support_followup
2. fare_charge
3. driver_issue
4. uber_eats
5. lost_item
6. account_access_security
7. benefits_other
8. ride_booking_cancellation
9. location_app_issue
10. driver_metrics
11. refund

======================================================================
Example 52/200
======================================================================

CUSTOMER:
@115873 Can you please make sure your drivers understand how GPS works. My one hour and 30 min ride turn into 3 hours.😭😭😭😡

Choose intent:
1. support_followup
2. fare_charge
3. driver_issue
4. uber_eats
5. lost_item
6. account_access_security
7. benefits_other
8. ride_booking_cancellation
9. location_app_issue
10. driver_metrics
11. refund

======================================================================
Example 53/200
======================================================================

CUSTOMER:
Highly disappointed with @115873 @Uber_Support. This is the third time, I filed a complaint against their driver but never got any support/help/reply.
 Yesterday I stucked with the wrong driver who allowed someone to accompany him &amp; took wrong route to GNH, Gurgaon.

Choose intent:
1. support_followup
2. fare_charge
3. driver_issue
4. uber_eats
5. lost_item
6. account_access_security
7. benefits_other
8. ride_booking_cancellation
9. location_app_issue
10. driver_metrics
11. refund

======================================================================
Example 54/200
======================================================================

CUSTOMER:
@Uber_Support I live in Albuquerque, NM. How can I add Uber Español to my passenger options? Thanks!

Choose intent:
1. support_followup
2. fare_charge
3. driver_issue
4. uber_eats
5. lost_item
6. account_access_security
7. benefits_other
8. ride_booking_cancellation
9. location_app_issue
10. driver_metrics
11. refund
Please enter a number from 1 to 11.

======================================================================
Example 55/200
======================================================================

CUSTOMER:
Fuck Uber and everything they represent!! @115873 how does a 5 cancellations and supposedly 3mins away! You what fuck your app

Choose intent:
1. support_followup
2. fare_charge
3. driver_issue
4. uber_eats
5. lost_item
6. account_access_security
7. benefits_other
8. ride_booking_cancellation
9. location_app_issue
10. driver_metrics
11. refund

======================================================================
Example 56/200
======================================================================

CUSTOMER:
@Uber_Support we need a way to complain about drivers who accept the trip, talk to us and don't turn up

Choose intent:
1. support_followup
2. fare_charge
3. driver_issue
4. uber_eats
5. lost_item
6. account_access_security
7. benefits_other
8. ride_booking_cancellation
9. location_app_issue
10. driver_metrics
11. refund

======================================================================
Example 57/200
======================================================================

CUSTOMER:
@435368 @115873 Dont expect anything back from @115873 they said they were outside my house to pick me up when they clearly werent then charged me £6

Choose intent:
1. support_followup
2. fare_charge
3. driver_issue
4. uber_eats
5. lost_item
6. account_access_security
7. benefits_other
8. ride_booking_cancellation
9. location_app_issue
10. driver_metrics
11. refund

======================================================================
Example 58/200
======================================================================

CUSTOMER:
@Uber_Support See @1143  system there system is so transparent.

Choose intent:
1. support_followup
2. fare_charge
3. driver_issue
4. uber_eats
5. lost_item
6. account_access_security
7. benefits_other
8. ride_booking_cancellation
9. location_app_issue
10. driver_metrics
11. refund

======================================================================
Example 59/200
======================================================================

CUSTOMER:
@Uber_Support Unfortunately that's not quite it - can we ask about a particular driver? We got an unreasonable 2/5

Choose intent:
1. support_followup
2. fare_charge
3. driver_issue
4. uber_eats
5. lost_item
6. account_access_security
7. benefits_other
8. ride_booking_cancellation
9. location_app_issue
10. driver_metrics
11. refund

======================================================================
Example 60/200
======================================================================

CUSTOMER:
@115877 @64394 Ordered at 4 got a driver at 5 and cancelled shortly after what’s happening here? https://t.co/vaawOF9XzE

Choose intent:
1. support_followup
2. fare_charge
3. driver_issue
4. uber_eats
5. lost_item
6. account_access_security
7. benefits_other
8. ride_booking_cancellation
9. location_app_issue
10. driver_metrics
11. refund

======================================================================
Example 61/200
======================================================================

CUSTOMER:
@Uber_Support  it says my car is not eligible for rides in Harrisburg PA.?????

Choose intent:
1. support_followup
2. fare_charge
3. driver_issue
4. uber_eats
5. lost_item
6. account_access_security
7. benefits_other
8. ride_booking_cancellation
9. location_app_issue
10. driver_metrics
11. refund

======================================================================
Example 62/200
======================================================================

CUSTOMER:
Hi @115877 I think my driver had a 40 minute nap in between pickup and delivery. How hard do you work these guys? Jk he was awful.

Choose intent:
1. support_followup
2. fare_charge
3. driver_issue
4. uber_eats
5. lost_item
6. account_access_security
7. benefits_other
8. ride_booking_cancellation
9. location_app_issue
10. driver_metrics
11. refund

======================================================================
Example 63/200
======================================================================

CUSTOMER:
I woke up to the most absurd response from @115873 @Uber_Support @115877 and their suggestion was I trouble shoot the app when it didn’t work properly AFTER they forgot half my food order. https://t.co/d6QMVzH15O

Choose intent:
1. support_followup
2. fare_charge
3. driver_issue
4. uber_eats
5. lost_item
6. account_access_security
7. benefits_other
8. ride_booking_cancellation
9. location_app_issue
10. driver_metrics
11. refund

======================================================================
Example 64/200
======================================================================

CUSTOMER:
@Uber_Support None of the issues that faced are listed on your support portal, so it doesn't help in any manner.

Choose intent:
1. support_followup
2. fare_charge
3. driver_issue
4. uber_eats
5. lost_item
6. account_access_security
7. benefits_other
8. ride_booking_cancellation
9. location_app_issue
10. driver_metrics
11. refund

======================================================================
Example 65/200
======================================================================

CUSTOMER:
@Uber_Support Through what app? Why is there no number I can call you on and why can't anyone give me a call?

Choose intent:
1. support_followup
2. fare_charge
3. driver_issue
4. uber_eats
5. lost_item
6. account_access_security
7. benefits_other
8. ride_booking_cancellation
9. location_app_issue
10. driver_metrics
11. refund

======================================================================
Example 66/200
======================================================================

CUSTOMER:
@115877 can't find the free food bit anywhere in my app? Can't find my code anywhere for my boyfriend who's a new user to use it.

Choose intent:
1. support_followup
2. fare_charge
3. driver_issue
4. uber_eats
5. lost_item
6. account_access_security
7. benefits_other
8. ride_booking_cancellation
9. location_app_issue
10. driver_metrics
11. refund

======================================================================
Example 67/200
======================================================================

CUSTOMER:
@115873 I had an issue with a recent trip and no one the help topics address the issue and there wasnt an option to write a comment under the

Choose intent:
1. support_followup
2. fare_charge
3. driver_issue
4. uber_eats
5. lost_item
6. account_access_security
7. benefits_other
8. ride_booking_cancellation
9. location_app_issue
10. driver_metrics
11. refund

======================================================================
Example 68/200
======================================================================

CUSTOMER:
@Uber_Support I honestly haven't experienced worse customer service: 18 fraudulent journeys in India were made from from Oct 2 to 4 (I was in France at the time) means that £162.18 has been debited. Still no refund despite 10 emails to Uber CS. @76474 can you help?

Choose intent:
1. support_followup
2. fare_charge
3. driver_issue
4. uber_eats
5. lost_item
6. account_access_security
7. benefits_other
8. ride_booking_cancellation
9. location_app_issue
10. driver_metrics
11. refund

======================================================================
Example 69/200
======================================================================

CUSTOMER:
@115877 my order #0DF35 is taking ages. They cancelled the last order as well so we have been waiting over 2 hours! Can you sort please?

Choose intent:
1. support_followup
2. fare_charge
3. driver_issue
4. uber_eats
5. lost_item
6. account_access_security
7. benefits_other
8. ride_booking_cancellation
9. location_app_issue
10. driver_metrics
11. refund

======================================================================
Example 70/200
======================================================================

CUSTOMER:
@Uber_Support My email address is __email__. you can pull out my contact details from there and contact me.

Choose intent:
1. support_followup
2. fare_charge
3. driver_issue
4. uber_eats
5. lost_item
6. account_access_security
7. benefits_other
8. ride_booking_cancellation
9. location_app_issue
10. driver_metrics
11. refund

======================================================================
Example 71/200
======================================================================

CUSTOMER:
@Uber_Support I’ve signed up and there’s no issue link

Choose intent:
1. support_followup
2. fare_charge
3. driver_issue
4. uber_eats
5. lost_item
6. account_access_security
7. benefits_other
8. ride_booking_cancellation
9. location_app_issue
10. driver_metrics
11. refund

======================================================================
Example 72/200
======================================================================

CUSTOMER:
soggy nuggets and missing a drink @McDonalds and @115877 sort your shit out

Choose intent:
1. support_followup
2. fare_charge
3. driver_issue
4. uber_eats
5. lost_item
6. account_access_security
7. benefits_other
8. ride_booking_cancellation
9. location_app_issue
10. driver_metrics
11. refund

======================================================================
Example 73/200
======================================================================

CUSTOMER:
@115873 driver got it wrong 4 times when picking me up. I had to cancel the trip when he kept driving away. How do i get a refund?

Choose intent:
1. support_followup
2. fare_charge
3. driver_issue
4. uber_eats
5. lost_item
6. account_access_security
7. benefits_other
8. ride_booking_cancellation
9. location_app_issue
10. driver_metrics
11. refund

======================================================================
Example 74/200
======================================================================

CUSTOMER:
@115873 you have charged my friend double for no reason what so ever in Miami on Wednesday - no explanation. We want this sorted please.

Choose intent:
1. support_followup
2. fare_charge
3. driver_issue
4. uber_eats
5. lost_item
6. account_access_security
7. benefits_other
8. ride_booking_cancellation
9. location_app_issue
10. driver_metrics
11. refund

======================================================================
Example 75/200
======================================================================

CUSTOMER:
@115877 I have been waiting for my order which was supposed to arrive at in 15 minutes from time I placed it. The time keeps changing. How do I cancel this order as I doubt I will get my food?

Choose intent:
1. support_followup
2. fare_charge
3. driver_issue
4. uber_eats
5. lost_item
6. account_access_security
7. benefits_other
8. ride_booking_cancellation
9. location_app_issue
10. driver_metrics
11. refund

======================================================================
Example 76/200
======================================================================

CUSTOMER:
@115873 just got super unreliable the customer service is terrible lyft is sounding more like a better choice

Choose intent:
1. support_followup
2. fare_charge
3. driver_issue
4. uber_eats
5. lost_item
6. account_access_security
7. benefits_other
8. ride_booking_cancellation
9. location_app_issue
10. driver_metrics
11. refund

======================================================================
Example 77/200
======================================================================

CUSTOMER:
@Uber_Support
Uber celebrating 3 years in Kochi, India and messaged us that there are offers for lesser kilometre when you ride. Check the prices below for 5.5 kilometres uber service
You guys are fraud n cheat https://t.co/XrUyad2CDn

Choose intent:
1. support_followup
2. fare_charge
3. driver_issue
4. uber_eats
5. lost_item
6. account_access_security
7. benefits_other
8. ride_booking_cancellation
9. location_app_issue
10. driver_metrics
11. refund

======================================================================
Example 78/200
======================================================================

CUSTOMER:
@Uber_Support Tried getting an UBER home from Dulles airport last night at 11:30.  2 different drivers called/texted to ask my destination.  One cancelled immediately.  On the second one, I refused to tell him, and he simply stayed where he was for 15 minutes until I gave up.

Choose intent:
1. support_followup
2. fare_charge
3. driver_issue
4. uber_eats
5. lost_item
6. account_access_security
7. benefits_other
8. ride_booking_cancellation
9. location_app_issue
10. driver_metrics
11. refund

======================================================================
Example 79/200
======================================================================

CUSTOMER:
@Uber_Support got a password reset mail. Didn't trigger it, but did get a new phone. URL appears legit. Was this you?

Choose intent:
1. support_followup
2. fare_charge
3. driver_issue
4. uber_eats
5. lost_item
6. account_access_security
7. benefits_other
8. ride_booking_cancellation
9. location_app_issue
10. driver_metrics
11. refund

======================================================================
Example 80/200
======================================================================

CUSTOMER:
@Uber_Support __email__
Rajat Gupta
Phone no. - 9629343477
Please check it what's the problem and please rectify it.

Choose intent:
1. support_followup
2. fare_charge
3. driver_issue
4. uber_eats
5. lost_item
6. account_access_security
7. benefits_other
8. ride_booking_cancellation
9. location_app_issue
10. driver_metrics
11. refund

======================================================================
Example 81/200
======================================================================

CUSTOMER:
@115873 I have communication issues almost every single time I get an uber. If my driver can't clearly talk to me then they shouldn't drive

Choose intent:
1. support_followup
2. fare_charge
3. driver_issue
4. uber_eats
5. lost_item
6. account_access_security
7. benefits_other
8. ride_booking_cancellation
9. location_app_issue
10. driver_metrics
11. refund

======================================================================
Example 82/200
======================================================================

CUSTOMER:
@Uber_Support I left my glasses in the car last night and I just can't get through to the driver. Please help. I can't see 😭😭😭😭

Choose intent:
1. support_followup
2. fare_charge
3. driver_issue
4. uber_eats
5. lost_item
6. account_access_security
7. benefits_other
8. ride_booking_cancellation
9. location_app_issue
10. driver_metrics
11. refund

======================================================================
Example 83/200
======================================================================

CUSTOMER:
@115873 my friend @786179 was just abandoned by his uber driver terrible employee will never be using your service

Choose intent:
1. support_followup
2. fare_charge
3. driver_issue
4. uber_eats
5. lost_item
6. account_access_security
7. benefits_other
8. ride_booking_cancellation
9. location_app_issue
10. driver_metrics
11. refund

======================================================================
Example 84/200
======================================================================

CUSTOMER:
So you get charged for cancelling if a driver is on the way, but it's alright for a driver to cancel on you if you've been waiting? @115873 🤔

Choose intent:
1. support_followup
2. fare_charge
3. driver_issue
4. uber_eats
5. lost_item
6. account_access_security
7. benefits_other
8. ride_booking_cancellation
9. location_app_issue
10. driver_metrics
11. refund

======================================================================
Example 85/200
======================================================================

CUSTOMER:
@Uber_Support I already did. It said I'll get a confirmation email, but I didn't get any and no one contacted me.

Choose intent:
1. support_followup
2. fare_charge
3. driver_issue
4. uber_eats
5. lost_item
6. account_access_security
7. benefits_other
8. ride_booking_cancellation
9. location_app_issue
10. driver_metrics
11. refund

======================================================================
Example 86/200
======================================================================

CUSTOMER:
@Uber_Support Obviously you don't care 😂

Choose intent:
1. support_followup
2. fare_charge
3. driver_issue
4. uber_eats
5. lost_item
6. account_access_security
7. benefits_other
8. ride_booking_cancellation
9. location_app_issue
10. driver_metrics
11. refund

======================================================================
Example 87/200
======================================================================

CUSTOMER:
@148768 @115877 Can we get some free donughnuts in W11? Were close to the westfield store!

Choose intent:
1. support_followup
2. fare_charge
3. driver_issue
4. uber_eats
5. lost_item
6. account_access_security
7. benefits_other
8. ride_booking_cancellation
9. location_app_issue
10. driver_metrics
11. refund

======================================================================
Example 88/200

In [51]:
print("Golden set:", golden_set.shape)

print("\nIntent distribution:")
print(golden_set["intent"].value_counts())

print("\nEscalation distribution:")
print(golden_set["escalate"].value_counts())

print("\nMissing values:")
print(golden_set[["intent", "escalate"]].isna().sum())

Golden set: (200, 4)

Intent distribution:
intent
support_followup             60
driver_issue                 36
uber_eats                    26
ride_booking_cancellation    21
account_access_security      19
fare_charge                  15
benefits_other                8
lost_item                     5
driver_metrics                5
refund                        3
location_app_issue            2
Name: count, dtype: int64

Escalation distribution:
escalate
False    115
True      85
Name: count, dtype: int64

Missing values:
intent      0
escalate    0
dtype: int64

In [52]:
golden_set.to_csv("../data/uber_golden_set.csv", index=False)

In [53]:
majority_intent = dev_set["intent"].value_counts().idxmax()

print("Majority intent:", majority_intent)

Majority intent: support_followup

In [54]:
from sklearn.metrics import accuracy_score, f1_score

y_true = golden_set["intent"]

y_pred = [majority_intent] * len(golden_set)

accuracy = accuracy_score(y_true, y_pred)
macro_f1 = f1_score(y_true, y_pred, average="macro", zero_division=0)

print("Majority Baseline")
print("-----------------")
print("Accuracy:", round(accuracy, 3))
print("Macro F1:", round(macro_f1, 3))

Majority Baseline
-----------------
Accuracy: 0.3
Macro F1: 0.042

In [55]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score, f1_score, classification_report

# Training data
X_train = dev_set["text_customer"]
y_train = dev_set["intent"]

# Golden evaluation data
X_test = golden_set["text_customer"]
y_test = golden_set["intent"]

# TF-IDF + Logistic Regression
baseline_model = Pipeline([
    ("tfidf", TfidfVectorizer(
        lowercase=True,
        ngram_range=(1, 2),
        min_df=1,
        max_features=10000
    )),
    ("classifier", LogisticRegression(
        max_iter=1000,
        class_weight="balanced"
    ))
])

# Train
baseline_model.fit(X_train, y_train)

# Predict
y_pred = baseline_model.predict(X_test)

# Evaluate
accuracy = accuracy_score(y_test, y_pred)
macro_f1 = f1_score(y_test, y_pred, average="macro", zero_division=0)

print("TF-IDF + Logistic Regression")
print("--------------------------------")
print("Accuracy:", round(accuracy, 3))
print("Macro F1:", round(macro_f1, 3))

print("\nPer-intent results:")
print(classification_report(
    y_test,
    y_pred,
    zero_division=0
))

TF-IDF + Logistic Regression
--------------------------------
Accuracy: 0.455
Macro F1: 0.296

Per-intent results:
                           precision    recall  f1-score   support

  account_access_security       0.50      0.37      0.42        19
           benefits_other       0.12      0.12      0.12         8
             driver_issue       0.42      0.47      0.45        36
           driver_metrics       0.00      0.00      0.00         5
              fare_charge       0.13      0.20      0.16        15
       location_app_issue       0.00      0.00      0.00         2
                lost_item       0.15      0.60      0.24         5
                   refund       0.50      0.33      0.40         3
ride_booking_cancellation       0.17      0.10      0.12        21
         support_followup       0.78      0.67      0.72        60
                uber_eats       0.59      0.65      0.62        26

                 accuracy                           0.46       200
                macro avg       0.31      0.32      0.30       200
             weighted avg       0.48      0.46      0.46       200

In [56]:
# Customer messages used in the golden evaluation set
golden_customers = set(golden_set["text_customer"])

# Remove golden examples from the historical retrieval data
retrieval_corpus = uber_pairs[
    ~uber_pairs["text_customer"].isin(golden_customers)
].copy()

print("Original pairs:", len(uber_pairs))
print("Retrieval corpus:", len(retrieval_corpus))
print("Golden examples excluded:", len(uber_pairs) - len(retrieval_corpus))

Original pairs: 56160
Retrieval corpus: 55956
Golden examples excluded: 204

In [57]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

retriever_vectorizer = TfidfVectorizer(
    lowercase=True,
    stop_words="english",
    ngram_range=(1, 2),
    max_features=50000
)

retriever_matrix = retriever_vectorizer.fit_transform(
    retrieval_corpus["text_customer"]
)

print("Retrieval matrix shape:", retriever_matrix.shape)

Retrieval matrix shape: (55956, 50000)

In [58]:
def retrieve_similar_cases(query, top_k=3):

    query_vector = retriever_vectorizer.transform([query])

    similarities = cosine_similarity(
        query_vector,
        retriever_matrix
    ).flatten()

    top_indices = similarities.argsort()[-top_k:][::-1]

    results = retrieval_corpus.iloc[top_indices].copy()
    results["similarity"] = similarities[top_indices]

    return results

In [59]:
query = "My driver cancelled my ride three times"

results = retrieve_similar_cases(query, top_k=3)

for _, row in results.iterrows():
    print("\n" + "=" * 70)
    print("SIMILARITY:", round(row["similarity"], 3))
    print("CUSTOMER:", row["text_customer"])
    print("UBER RESPONSE:", row["text_uber"])

======================================================================
SIMILARITY: 0.526
CUSTOMER: .@115873 my driver, not me, cancelled my ride but I was still charged. What’s that about?
UBER RESPONSE: @704475 Here to help! Please send us a note via  https://t.co/h840Iouehc  so our team can connect.

======================================================================
SIMILARITY: 0.445
CUSTOMER: @Uber_Support I can't fill a complaint because the driver cancelled the ride
UBER RESPONSE: @439854 Sorry to hear about that! Can you please contact us via https://t.co/593jusCquh so our team can connect?

======================================================================
SIMILARITY: 0.432
CUSTOMER: This is a joke @115873 you’ve cancelled my ride 3 times. It’s 1am you shouldn’t do this, my ride is now 12 minutes away... what
UBER RESPONSE: @324146 Here to help. Send us a note at https://t.co/e8HVorX5rh so our team can connect.

In [66]:
print("1. Starting...")

import os
from dotenv import load_dotenv
from groq import Groq

print("2. Imports done")

load_dotenv()

key = os.getenv("GROQ_API_KEY")
print("3. API key found:", key is not None)

groq_client = Groq(api_key=key)

print("4. Client created")
print("5. Sending request...")

response = groq_client.chat.completions.create(
    model="openai/gpt-oss-20b",
    messages=[
        {
            "role": "user",
            "content": "Say hello in one sentence."
        }
    ],
    max_tokens=50
)

print("6. Response received")
print(response.choices[0].message.content)

1. Starting...
2. Imports done
3. API key found: True
4. Client created
5. Sending request...
6. Response received
Hello, I’m delighted to connect with you today!

In [71]:
import sys
import os

sys.path.append(os.path.abspath(".."))

In [72]:
from src.llm import generate_llm_response

result = generate_llm_response(
    "A customer says: 'My driver cancelled my ride three times.' "
    "Write a short professional support response."
)

print(result)

Hi [Customer Name],

I’m really sorry to hear that your driver cancelled the ride three times. That’s definitely not the experience we want for you.

Could you please let me know the date and time of the trip, and if you have the trip ID or any confirmation number? I’ll investigate the issue right away and make sure you’re compensated for the inconvenience—whether that’s a refund, a credit, or a priority booking for your next ride.

Thank you for your patience, and I’ll get back to you as soon as I have an update.

Best regards,
[Your Name]
Customer Support Team

In [74]:
import importlib
import src.llm

importlib.reload(src.llm)

In [76]:
print("A")

import src.llm
print("B")

import importlib
importlib.reload(src.llm)
print("C")

print("Does function exist:", hasattr(src.llm, "classify_intent"))
print("Functions:", [x for x in dir(src.llm) if not x.startswith("_")])

A
B
C
Does function exist: True
Functions: ['Groq', 'MODEL', 'classify_intent', 'client', 'generate_llm_response', 'load_dotenv', 'os']

In [90]:
import importlib
import src.llm

importlib.reload(src.llm)

from src.llm import classify_intent

print(classify_intent("My driver cancelled my ride three times"))

driver_issue

In [84]:
import pandas as pd
import time

test_10 = golden_set.head(10).copy()

predictions = []

for i, message in enumerate(test_10["text_customer"]):
    try:
        prediction = classify_intent(message)
        predictions.append(prediction)
        print(f"{i+1}/10 → {prediction}")
    except Exception as e:
        print(f"{i+1}/10 → ERROR: {e}")
        predictions.append("ERROR")

    time.sleep(1)

test_10["predicted_intent"] = predictions

print("\nDone!")

1/10 → fare_charge
2/10 → support_followup
3/10 → ride_booking_cancellation
4/10 → support_followup
5/10 → ride_booking_cancellation
6/10 → ride_booking_cancellation
7/10 → support_followup
8/10 → benefits_other
9/10 → benefits_other
10/10 → fare_charge

Done!

In [85]:
valid_intents = {
    "support_followup",
    "fare_charge",
    "driver_issue",
    "uber_eats",
    "lost_item",
    "account_access_security",
    "benefits_other",
    "ride_booking_cancellation",
    "location_app_issue",
    "driver_metrics",
    "refund"
}

print(test_10["predicted_intent"].isin(valid_intents).value_counts())

predicted_intent
True    10
Name: count, dtype: int64

In [91]:
message = """I had an awful experience with @115873 tonight, @Uber_Support.
A driver left me stood out in the rain for ages, ignored my attempts to
contact him and then cancelled my ride -- AND I GET A £4 BLOODY
CANCELLATION FEE?! Absolutely unfair."""

print(classify_intent(message))

driver_issue

In [92]:
test_10 = golden_set.head(10).copy()

predictions = []

for i, message in enumerate(test_10["text_customer"]):
    prediction = classify_intent(message)
    predictions.append(prediction)
    print(f"{i+1}/10 → Human: {test_10.iloc[i]['intent']} | LLM: {prediction}")

test_10["predicted_intent"] = predictions

1/10 → Human: fare_charge | LLM: refund
2/10 → Human: support_followup | LLM: support_followup
3/10 → Human: ride_booking_cancellation | LLM: driver_issue
4/10 → Human: support_followup | LLM: support_followup
5/10 → Human: ride_booking_cancellation | LLM: fare_charge
6/10 → Human: ride_booking_cancellation | LLM: ride_booking_cancellation
7/10 → Human: support_followup | LLM: support_followup
8/10 → Human: support_followup | LLM: benefits_other
9/10 → Human: driver_issue | LLM: driver_issue
10/10 → Human: fare_charge | LLM: fare_charge

In [93]:
correct = (
    test_10["intent"] == test_10["predicted_intent"]
).sum()

print(f"\nCorrect: {correct}/10")
print(f"Accuracy: {correct / 10:.1%}")

Correct: 6/10
Accuracy: 60.0%

In [94]:
import time
import pandas as pd

golden_eval = golden_set.copy()

predictions = []

for i, message in enumerate(golden_eval["text_customer"]):

    try:
        prediction = classify_intent(message)
        predictions.append(prediction)

        print(
            f"{i+1}/200 → "
            f"Human: {golden_eval.iloc[i]['intent']} | "
            f"LLM: {prediction}"
        )

    except Exception as e:
        print(f"{i+1}/200 → ERROR: {e}")
        predictions.append("ERROR")

    time.sleep(1)

golden_eval["predicted_intent"] = predictions

golden_eval.to_csv(
    "../data/llm_golden_predictions.csv",
    index=False
)

print("\nEvaluation complete!")

1/200 → Human: fare_charge | LLM: refund
2/200 → Human: support_followup | LLM: support_followup
3/200 → Human: ride_booking_cancellation | LLM: driver_issue
4/200 → Human: support_followup | LLM: support_followup
5/200 → Human: ride_booking_cancellation | LLM: fare_charge
6/200 → Human: ride_booking_cancellation | LLM: ride_booking_cancellation
7/200 → Human: support_followup | LLM: support_followup
8/200 → Human: support_followup | LLM: benefits_other
9/200 → Human: driver_issue | LLM: driver_issue
10/200 → Human: fare_charge | LLM: fare_charge
11/200 → Human: lost_item | LLM: lost_item
12/200 → Human: uber_eats | LLM: driver_issue
13/200 → Human: ride_booking_cancellation | LLM: fare_charge
14/200 → Human: support_followup | LLM: location_app_issue
15/200 → Human: support_followup | LLM: account_access_security
16/200 → Human: support_followup | LLM: benefits_other
17/200 → Human: ride_booking_cancellation | LLM: driver_issue
18/200 → Human: support_followup | LLM: benefits_other
19/200 → Human: support_followup | LLM: support_followup
20/200 → Human: support_followup | LLM: benefits_other
21/200 → Human: ride_booking_cancellation | LLM: ride_booking_cancellation
22/200 → Human: ride_booking_cancellation | LLM: benefits_other
23/200 → Human: driver_issue | LLM: fare_charge
24/200 → Human: account_access_security | LLM: account_access_security
25/200 → Human: ride_booking_cancellation | LLM: location_app_issue
26/200 → Human: support_followup | LLM: support_followup
27/200 → Human: support_followup | LLM: support_followup
28/200 → Human: benefits_other | LLM: benefits_other
29/200 → Human: driver_issue | LLM: driver_issue
30/200 → Human: uber_eats | LLM: benefits_other
31/200 → Human: support_followup | LLM: support_followup
32/200 → Human: support_followup | LLM: benefits_other
33/200 → Human: account_access_security | LLM: account_access_security
34/200 → Human: support_followup | LLM: support_followup
35/200 → Human: support_followup | LLM: support_followup
36/200 → Human: driver_issue | LLM: driver_issue
37/200 → Human: uber_eats | LLM: benefits_other
38/200 → Human: account_access_security | LLM: location_app_issue
39/200 → Human: fare_charge | LLM: fare_charge
40/200 → Human: refund | LLM: refund
41/200 → Human: driver_issue | LLM: driver_issue
42/200 → Human: support_followup | LLM: benefits_other
43/200 → Human: benefits_other | LLM: benefits_other
44/200 → Human: support_followup | LLM: benefits_other
45/200 → Human: support_followup | LLM: support_followup
46/200 → Human: support_followup | LLM: support_followup
47/200 → Human: support_followup | LLM: benefits_other
48/200 → Human: support_followup | LLM: support_followup
49/200 → Human: driver_issue | LLM: location_app_issue
50/200 → Human: uber_eats | LLM: uber_eats
51/200 → Human: driver_issue | LLM: lost_item
52/200 → Human: driver_issue | LLM: driver_issue
53/200 → Human: driver_issue | LLM: driver_issue
54/200 → Human: support_followup | LLM: benefits_other
55/200 → Human: ride_booking_cancellation | LLM: driver_issue
56/200 → Human: driver_issue | LLM: driver_issue
57/200 → Human: driver_issue | LLM: fare_charge
58/200 → Human: support_followup | LLM: benefits_other
59/200 → Human: support_followup | LLM: driver_issue
60/200 → Human: ride_booking_cancellation | LLM: driver_issue
61/200 → Human: location_app_issue | LLM: driver_issue
62/200 → Human: uber_eats | LLM: driver_issue
63/200 → Human: uber_eats | LLM: uber_eats
64/200 → Human: support_followup | LLM: support_followup
65/200 → Human: support_followup | LLM: support_followup
66/200 → Human: uber_eats | LLM: uber_eats
67/200 → Human: ride_booking_cancellation | LLM: support_followup
68/200 → Human: account_access_security | LLM: refund
69/200 → Human: uber_eats | LLM: uber_eats
70/200 → Human: support_followup | LLM: support_followup
71/200 → Human: support_followup | LLM: support_followup
72/200 → Human: uber_eats | LLM: uber_eats
73/200 → Human: refund | LLM: driver_issue
74/200 → Human: fare_charge | LLM: fare_charge
75/200 → Human: uber_eats | LLM: uber_eats
76/200 → Human: support_followup | LLM: support_followup
77/200 → Human: fare_charge | LLM: fare_charge
78/200 → Human: driver_issue | LLM: driver_issue
79/200 → Human: support_followup | LLM: account_access_security
80/200 → Human: support_followup | LLM: benefits_other
81/200 → Human: driver_issue | LLM: driver_issue
82/200 → Human: lost_item | LLM: lost_item
83/200 → Human: driver_issue | LLM: driver_issue
84/200 → Human: ride_booking_cancellation | LLM: fare_charge
85/200 → Human: support_followup | LLM: support_followup
86/200 → Human: support_followup | LLM: support_followup
87/200 → Human: uber_eats | LLM: benefits_other
88/200 → Human: lost_item | LLM: lost_item
89/200 → Human: ride_booking_cancellation | LLM: location_app_issue
90/200 → Human: support_followup | LLM: support_followup
91/200 → Human: support_followup | LLM: benefits_other
92/200 → Human: uber_eats | LLM: uber_eats
93/200 → Human: driver_issue | LLM: driver_issue
94/200 → Human: benefits_other | LLM: driver_issue
95/200 → Human: benefits_other | LLM: benefits_other
96/200 → Human: uber_eats | LLM: benefits_other
97/200 → Human: ride_booking_cancellation | LLM: location_app_issue
98/200 → Human: ride_booking_cancellation | LLM: driver_issue
99/200 → Human: ride_booking_cancellation | LLM: driver_issue
100/200 → Human: support_followup | LLM: benefits_other
101/200 → Human: support_followup | LLM: fare_charge
102/200 → Human: support_followup | LLM: benefits_other
103/200 → Human: driver_metrics | LLM: fare_charge
104/200 → Human: fare_charge | LLM: fare_charge
105/200 → Human: fare_charge | LLM: fare_charge
106/200 → Human: support_followup | LLM: driver_issue
107/200 → Human: uber_eats | LLM: lost_item
108/200 → Human: driver_issue | LLM: driver_issue
109/200 → Human: account_access_security | LLM: account_access_security
110/200 → Human: account_access_security | LLM: account_access_security
111/200 → Human: uber_eats | LLM: benefits_other
112/200 → Human: driver_issue | LLM: driver_issue
113/200 → Human: uber_eats | LLM: benefits_other
114/200 → Human: uber_eats | LLM: uber_eats
115/200 → Human: driver_issue | LLM: driver_issue
116/200 → Human: fare_charge | LLM: fare_charge
117/200 → Human: ride_booking_cancellation | LLM: refund
118/200 → Human: support_followup | LLM: support_followup
119/200 → Human: uber_eats | LLM: uber_eats
120/200 → Human: support_followup | LLM: support_followup
121/200 → Human: support_followup | LLM: support_followup
122/200 → Human: benefits_other | LLM: fare_charge
123/200 → Human: account_access_security | LLM: account_access_security
124/200 → Human: account_access_security | LLM: benefits_other
125/200 → Human: lost_item | LLM: lost_item
126/200 → Human: ride_booking_cancellation | LLM: driver_issue
127/200 → Human: driver_issue | LLM: driver_issue
128/200 → Human: support_followup | LLM: support_followup
129/200 → Human: support_followup | LLM: fare_charge
130/200 → Human: uber_eats | LLM: uber_eats
131/200 → Human: driver_issue | LLM: driver_issue
132/200 → Human: account_access_security | LLM: benefits_other
133/200 → Human: fare_charge | LLM: fare_charge
134/200 → Human: driver_issue | LLM: driver_issue
135/200 → Human: support_followup | LLM: benefits_other
136/200 → Human: support_followup | LLM: benefits_other
137/200 → Human: support_followup | LLM: support_followup
138/200 → Human: support_followup | LLM: benefits_other
139/200 → Human: account_access_security | LLM: driver_issue
140/200 → Human: driver_issue | LLM: driver_issue
141/200 → Human: driver_issue | LLM: driver_issue
142/200 → Human: driver_issue | LLM: benefits_other
143/200 → Human: account_access_security | LLM: account_access_security
144/200 → Human: support_followup | LLM: fare_charge
145/200 → Human: driver_metrics | LLM: driver_issue
146/200 → Human: driver_issue | LLM: driver_issue
147/200 → Human: support_followup | LLM: support_followup
148/200 → Human: uber_eats | LLM: benefits_other
149/200 → Human: support_followup | LLM: support_followup
150/200 → Human: uber_eats | LLM: uber_eats
151/200 → Human: driver_issue | LLM: driver_issue
152/200 → Human: uber_eats | LLM: uber_eats
153/200 → Human: lost_item | LLM: lost_item
154/200 → Human: support_followup | LLM: benefits_other
155/200 → Human: support_followup | LLM: support_followup
156/200 → Human: account_access_security | LLM: benefits_other
157/200 → Human: account_access_security | LLM: account_access_security
158/200 → Human: account_access_security | LLM: fare_charge
159/200 → Human: driver_issue | LLM: driver_issue
160/200 → Human: fare_charge | LLM: benefits_other
161/200 → Human: ride_booking_cancellation | LLM: driver_issue
162/200 → Human: support_followup | LLM: support_followup
163/200 → Human: driver_issue | LLM: driver_issue
164/200 → Human: account_access_security | LLM: location_app_issue
165/200 → Human: fare_charge | LLM: fare_charge
166/200 → Human: driver_issue | LLM: driver_issue
167/200 → Human: driver_issue | LLM: benefits_other
168/200 → Human: driver_metrics | LLM: driver_issue
169/200 → Human: account_access_security | LLM: account_access_security
170/200 → Human: account_access_security | LLM: location_app_issue
171/200 → Human: benefits_other | LLM: support_followup
172/200 → Human: refund | LLM: refund
173/200 → Human: benefits_other | LLM: benefits_other
174/200 → Human: driver_metrics | LLM: benefits_other
175/200 → Human: support_followup | LLM: support_followup
176/200 → Human: support_followup | LLM: benefits_other
177/200 → Human: fare_charge | LLM: fare_charge
178/200 → Human: account_access_security | LLM: account_access_security
179/200 → Human: driver_issue | LLM: driver_issue
180/200 → Human: uber_eats | LLM: account_access_security
181/200 → Human: benefits_other | LLM: benefits_other
182/200 → Human: ride_booking_cancellation | LLM: fare_charge
183/200 → Human: uber_eats | LLM: uber_eats
184/200 → Human: driver_issue | LLM: driver_issue
185/200 → Human: fare_charge | LLM: fare_charge
186/200 → Human: driver_issue | LLM: driver_issue
187/200 → Human: uber_eats | LLM: refund
188/200 → Human: driver_issue | LLM: driver_issue
189/200 → Human: uber_eats | LLM: driver_issue
190/200 → Human: support_followup | LLM: support_followup
191/200 → Human: driver_metrics | LLM: driver_issue
192/200 → Human: driver_issue | LLM: driver_issue
193/200 → Human: fare_charge | LLM: fare_charge
194/200 → Human: support_followup | LLM: support_followup
195/200 → Human: ride_booking_cancellation | LLM: support_followup
196/200 → Human: driver_issue | LLM: driver_issue
197/200 → Human: fare_charge | LLM: benefits_other
198/200 → Human: account_access_security | LLM: account_access_security
199/200 → Human: support_followup | LLM: account_access_security
200/200 → Human: location_app_issue | LLM: location_app_issue

Evaluation complete!

In [95]:
from sklearn.metrics import (
    accuracy_score,
    f1_score,
    classification_report,
    confusion_matrix
)

y_true = golden_eval["intent"]
y_pred = golden_eval["predicted_intent"]

accuracy = accuracy_score(y_true, y_pred)
macro_f1 = f1_score(
    y_true,
    y_pred,
    average="macro",
    zero_division=0
)

print(f"LLM Accuracy: {accuracy:.3f}")
print(f"LLM Macro-F1: {macro_f1:.3f}")

print("\nPer-intent performance:")
print(
    classification_report(
        y_true,
        y_pred,
        zero_division=0
    )
)

LLM Accuracy: 0.560
LLM Macro-F1: 0.464

Per-intent performance:
                           precision    recall  f1-score   support

  account_access_security       0.71      0.53      0.61        19
           benefits_other       0.12      0.62      0.21         8
             driver_issue       0.60      0.83      0.70        36
           driver_metrics       0.00      0.00      0.00         5
              fare_charge       0.50      0.80      0.62        15
       location_app_issue       0.11      0.50      0.18         2
                lost_item       0.71      1.00      0.83         5
                   refund       0.33      0.67      0.44         3
ride_booking_cancellation       1.00      0.10      0.17        21
         support_followup       0.91      0.53      0.67        60
                uber_eats       1.00      0.50      0.67        26

                 accuracy                           0.56       200
                macro avg       0.55      0.55      0.46       200
             weighted avg       0.75      0.56      0.57       200

In [97]:
import pandas as pd

labels = sorted(y_true.unique())

cm = confusion_matrix(
    y_true,
    y_pred,
    labels=labels
)

cm_df = pd.DataFrame(
    cm,
    index=labels,
    columns=labels
)

cm_df

,account_access_security,benefits_other,driver_issue,driver_metrics,fare_charge,location_app_issue,lost_item,refund,ride_booking_cancellation,support_followup,uber_eats
account_access_security,10,3,1,0,1,3,0,1,0,0,0
benefits_other,0,5,1,0,1,0,0,0,0,1,0
driver_issue,0,2,30,0,2,1,1,0,0,0,0
driver_metrics,0,1,3,0,1,0,0,0,0,0,0
fare_charge,0,2,0,0,12,0,0,1,0,0,0
location_app_issue,0,0,1,0,0,1,0,0,0,0,0
lost_item,0,0,0,0,0,0,5,0,0,0,0
refund,0,0,1,0,0,0,0,2,0,0,0
ride_booking_cancellation,0,1,8,0,4,3,0,1,2,2,0
support_followup,3,19,2,0,3,1,0,0,0,32,0
uber_eats,1,7,3,0,0,0,1,1,0,0,13

In [96]:
print(golden_eval["predicted_intent"].value_counts())

predicted_intent
driver_issue                 50
benefits_other               40
support_followup             35
fare_charge                  24
account_access_security      14
uber_eats                    13
location_app_issue            9
lost_item                     7
refund                        6
ride_booking_cancellation     2
Name: count, dtype: int64

In [98]:
golden_eval.to_csv(
    "../data/llm_golden_predictions.csv",
    index=False
)

print("Saved LLM evaluation results.")

Saved LLM evaluation results.

In [104]:
import importlib
import src.llm

importlib.reload(src.llm)

from src.llm import classify_escalation

In [105]:
message = """I had an awful experience with @115873 tonight, @Uber_Support.
A driver left me stood out in the rain for ages, ignored my attempts to
contact him and then cancelled my ride -- AND I GET A £4 BLOODY
CANCELLATION FEE?! Absolutely unfair."""

intent = classify_intent(message)

escalate = classify_escalation(message, intent)

print("Intent:", intent)
print("Escalate:", escalate)

Intent: driver_issue
Escalate: True

In [106]:
import time

escalation_predictions = []

for i, row in golden_eval.iterrows():

    try:
        prediction = classify_escalation(
            row["text_customer"],
            row["intent"]
        )

        escalation_predictions.append(prediction)

        print(
            f"{i+1}/200 → "
            f"Human: {row['escalate']} | "
            f"LLM: {prediction}"
        )

    except Exception as e:
        print(f"{i+1}/200 → ERROR: {e}")
        escalation_predictions.append(None)

    time.sleep(1)

golden_eval["predicted_escalate"] = escalation_predictions

golden_eval.to_csv(
    "../data/llm_golden_predictions.csv",
    index=False
)

print("\nEscalation evaluation complete!")

1/200 → Human: True | LLM: True
2/200 → Human: False | LLM: False
3/200 → Human: False | LLM: False
4/200 → Human: False | LLM: True
5/200 → Human: False | LLM: False
6/200 → Human: False | LLM: True
7/200 → Human: False | LLM: False
8/200 → Human: False | LLM: False
9/200 → Human: True | LLM: True
10/200 → Human: True | LLM: True
11/200 → Human: True | LLM: False
12/200 → Human: True | LLM: True
13/200 → Human: False | LLM: False
14/200 → Human: False | LLM: False
15/200 → Human: False | LLM: True
16/200 → Human: False | LLM: False
17/200 → Human: True | LLM: False
18/200 → Human: False | LLM: False
19/200 → Human: False | LLM: False
20/200 → Human: True | LLM: False
21/200 → Human: False | LLM: False
22/200 → Human: True | LLM: False
23/200 → Human: True | LLM: True
24/200 → Human: False | LLM: True
25/200 → Human: True | LLM: False
26/200 → Human: False | LLM: False
27/200 → Human: False | LLM: False
28/200 → Human: False | LLM: False
29/200 → Human: False | LLM: True
30/200 → Human: False | LLM: True
31/200 → Human: False | LLM: False
32/200 → Human: False | LLM: False
33/200 → Human: False | LLM: True
34/200 → Human: True | LLM: False
35/200 → Human: True | LLM: True
36/200 → Human: True | LLM: True
37/200 → Human: True | LLM: False
38/200 → Human: False | LLM: False
39/200 → Human: True | LLM: True
40/200 → Human: False | LLM: True
41/200 → Human: True | LLM: True
42/200 → Human: False | LLM: False
43/200 → Human: False | LLM: False
44/200 → Human: False | LLM: True
45/200 → Human: True | LLM: True
46/200 → Human: True | LLM: False
47/200 → Human: False | LLM: False
48/200 → Human: True | LLM: True
49/200 → Human: False | LLM: False
50/200 → Human: True | LLM: True
51/200 → Human: True | LLM: True
52/200 → Human: True | LLM: False
53/200 → Human: True | LLM: True
54/200 → Human: False | LLM: False
55/200 → Human: True | LLM: False
56/200 → Human: False | LLM: True
57/200 → Human: False | LLM: True
58/200 → Human: False | LLM: False
59/200 → Human: False | LLM: False
60/200 → Human: True | LLM: False
61/200 → Human: True | LLM: False
62/200 → Human: True | LLM: False
63/200 → Human: True | LLM: True
64/200 → Human: False | LLM: False
65/200 → Human: False | LLM: False
66/200 → Human: False | LLM: False
67/200 → Human: False | LLM: False
68/200 → Human: True | LLM: True
69/200 → Human: True | LLM: False
70/200 → Human: False | LLM: False
71/200 → Human: False | LLM: False
72/200 → Human: False | LLM: False
73/200 → Human: True | LLM: True
74/200 → Human: True | LLM: True
75/200 → Human: True | LLM: False
76/200 → Human: True | LLM: False
77/200 → Human: True | LLM: True
78/200 → Human: True | LLM: False
79/200 → Human: False | LLM: True
80/200 → Human: False | LLM: False
81/200 → Human: False | LLM: False
82/200 → Human: True | LLM: False
83/200 → Human: True | LLM: True
84/200 → Human: False | LLM: False
85/200 → Human: True | LLM: False
86/200 → Human: False | LLM: False
87/200 → Human: False | LLM: False
88/200 → Human: True | LLM: False
89/200 → Human: False | LLM: False
90/200 → Human: True | LLM: False
91/200 → Human: False | LLM: False
92/200 → Human: False | LLM: False
93/200 → Human: False | LLM: False
94/200 → Human: False | LLM: False
95/200 → Human: False | LLM: False
96/200 → Human: False | LLM: False
97/200 → Human: False | LLM: False
98/200 → Human: False | LLM: False
99/200 → Human: False | LLM: False
100/200 → Human: False | LLM: False
101/200 → Human: True | LLM: True
102/200 → Human: False | LLM: False
103/200 → Human: True | LLM: False
104/200 → Human: False | LLM: True
105/200 → Human: False | LLM: True
106/200 → Human: True | LLM: True
107/200 → Human: False | LLM: True
108/200 → Human: True | LLM: True
109/200 → Human: False | LLM: True
110/200 → Human: False | LLM: False
111/200 → Human: True | LLM: True
112/200 → Human: True | LLM: True
113/200 → Human: False | LLM: True
114/200 → Human: False | LLM: True
115/200 → Human: True | LLM: True
116/200 → Human: False | LLM: True
117/200 → Human: False | LLM: False
118/200 → Human: False | LLM: False
119/200 → Human: False | LLM: False
120/200 → Human: False | LLM: False
121/200 → Human: True | LLM: True
122/200 → Human: False | LLM: False
123/200 → Human: False | LLM: True
124/200 → Human: False | LLM: False
125/200 → Human: True | LLM: True
126/200 → Human: False | LLM: False
127/200 → Human: True | LLM: True
128/200 → Human: False | LLM: False
129/200 → Human: False | LLM: False
130/200 → Human: True | LLM: False
131/200 → Human: True | LLM: True
132/200 → Human: True | LLM: True
133/200 → Human: False | LLM: False
134/200 → Human: True | LLM: False
135/200 → Human: False | LLM: False
136/200 → Human: False | LLM: False
137/200 → Human: False | LLM: False
138/200 → Human: False | LLM: False
139/200 → Human: True | LLM: True
140/200 → Human: True | LLM: True
141/200 → Human: True | LLM: True
142/200 → Human: False | LLM: False
143/200 → Human: False | LLM: True
144/200 → Human: True | LLM: True
145/200 → Human: True | LLM: False
146/200 → Human: True | LLM: True
147/200 → Human: True | LLM: True
148/200 → Human: True | LLM: False
149/200 → Human: False | LLM: False
150/200 → Human: False | LLM: False
151/200 → Human: True | LLM: True
152/200 → Human: False | LLM: False
153/200 → Human: True | LLM: False
154/200 → Human: False | LLM: False
155/200 → Human: True | LLM: False
156/200 → Human: False | LLM: False
157/200 → Human: True | LLM: True
158/200 → Human: True | LLM: True
159/200 → Human: False | LLM: True
160/200 → Human: True | LLM: True
161/200 → Human: False | LLM: False
162/200 → Human: True | LLM: True
163/200 → Human: False | LLM: True
164/200 → Human: True | LLM: False
165/200 → Human: True | LLM: False
166/200 → Human: True | LLM: True
167/200 → Human: True | LLM: True
168/200 → Human: False | LLM: False
169/200 → Human: True | LLM: True
170/200 → Human: True | LLM: False
171/200 → Human: False | LLM: False
172/200 → Human: False | LLM: True
173/200 → Human: False | LLM: False
174/200 → Human: False | LLM: False
175/200 → Human: False | LLM: False
176/200 → Human: False | LLM: False
177/200 → Human: False | LLM: False
178/200 → Human: True | LLM: True
179/200 → Human: False | LLM: False
180/200 → Human: True | LLM: True
181/200 → Human: False | LLM: False
182/200 → Human: False | LLM: False
183/200 → Human: True | LLM: False
184/200 → Human: False | LLM: True
185/200 → Human: True | LLM: True
186/200 → Human: True | LLM: False
187/200 → Human: True | LLM: True
188/200 → Human: True | LLM: True
189/200 → Human: False | LLM: False
190/200 → Human: True | LLM: True
191/200 → Human: False | LLM: False
192/200 → Human: True | LLM: True
193/200 → Human: False | LLM: False
194/200 → Human: False | LLM: False
195/200 → Human: False | LLM: False
196/200 → Human: False | LLM: True
197/200 → Human: False | LLM: False
198/200 → Human: False | LLM: True
199/200 → Human: False | LLM: True
200/200 → Human: False | LLM: False

Escalation evaluation complete!

In [107]:
print(golden_eval["predicted_escalate"].value_counts(dropna=False))

predicted_escalate
False    120
True      80
Name: count, dtype: int64

In [108]:
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    classification_report
)

y_true = golden_eval["escalate"].astype(bool)
y_pred = golden_eval["predicted_escalate"].astype(bool)

accuracy = accuracy_score(y_true, y_pred)
precision = precision_score(y_true, y_pred, zero_division=0)
recall = recall_score(y_true, y_pred, zero_division=0)
f1 = f1_score(y_true, y_pred, zero_division=0)

print(f"Escalation Accuracy: {accuracy:.3f}")
print(f"Escalation Precision: {precision:.3f}")
print(f"Escalation Recall: {recall:.3f}")
print(f"Escalation F1: {f1:.3f}")

print("\nClassification Report:")
print(
    classification_report(
        y_true,
        y_pred,
        target_names=["No Escalation", "Escalate"],
        zero_division=0
    )
)

print("\nConfusion Matrix:")
print(confusion_matrix(y_true, y_pred))

Escalation Accuracy: 0.695
Escalation Precision: 0.650
Escalation Recall: 0.612
Escalation F1: 0.630

Classification Report:
               precision    recall  f1-score   support

No Escalation       0.72      0.76      0.74       115
     Escalate       0.65      0.61      0.63        85

     accuracy                           0.69       200
    macro avg       0.69      0.68      0.69       200
 weighted avg       0.69      0.69      0.69       200


Confusion Matrix:
[[87 28]
 [33 52]]

In [109]:
response_eval = golden_eval.sample(
    n=40,
    random_state=456
).copy()

response_eval = response_eval.reset_index(drop=True)

print("Response evaluation set:", response_eval.shape)

Response evaluation set: (40, 6)

In [110]:
import time

generated_responses = []
retrieved_evidence = []

for i, row in response_eval.iterrows():

    query = row["text_customer"]

    retrieved = retrieve_similar_cases(
        query,
        top_k=3
    )

    response = generate_grounded_response(
        query,
        retrieved
    )

    generated_responses.append(response)
    retrieved_evidence.append(retrieved)

    print(f"{i+1}/40 → generated")

    time.sleep(1)

response_eval["generated_response"] = generated_responses
response_eval["retrieved_evidence"] = retrieved_evidence

print("\nResponse generation complete!")

1/40 → generated
2/40 → generated
3/40 → generated
4/40 → generated
5/40 → generated
6/40 → generated
7/40 → generated
8/40 → generated
9/40 → generated
10/40 → generated
11/40 → generated
12/40 → generated
13/40 → generated
14/40 → generated
15/40 → generated
16/40 → generated
17/40 → generated
18/40 → generated
19/40 → generated
20/40 → generated
21/40 → generated
22/40 → generated
23/40 → generated
24/40 → generated
25/40 → generated
26/40 → generated
27/40 → generated
28/40 → generated
29/40 → generated
30/40 → generated
31/40 → generated
32/40 → generated
33/40 → generated
34/40 → generated
35/40 → generated
36/40 → generated
37/40 → generated
38/40 → generated
39/40 → generated
40/40 → generated

Response generation complete!

In [111]:
print(response_eval.loc[0, "text_customer"])

print("\n--- GENERATED RESPONSE ---\n")

print(response_eval.loc[0, "generated_response"])

print("\n--- RETRIEVED EVIDENCE ---\n")

print(
    response_eval.loc[0, "retrieved_evidence"][
        ["text_customer", "text_uber", "similarity"]
    ]
)

@115877 what’s the deal when they don’t deliver your full order? This has now happened twice to my Mrs with no refund ? A want fed mate

--- GENERATED RESPONSE ---

Sorry to hear about the troubles. Please send us a note using https://t.co

--- RETRIEVED EVIDENCE ---

                                           text_customer  \
14064     @115877 why don't you deliver in Wolverhampton
30714  @Uber_Support All I️ can show you mate https:/...
29840  @Uber_Support This happened twice! And I have ...

                                               text_uber  similarity
14064  @299021 We're working hard to expand our servi...    0.331660
30714  @505272 Sorry to hear about the troubles, Conn...    0.280511
29840  @493478 We're here to help! Send us a DM with ...    0.251660

In [112]:
human_eval = response_eval.head(20).copy()

human_eval["helpfulness"] = ""
human_eval["grounding"] = ""
human_eval["actionability"] = ""
human_eval["appropriateness"] = ""

human_eval.to_csv(
    "../data/human_response_eval.csv",
    index=False
)

print(human_eval.shape)

(20, 12)

In [2]:
import os
from dotenv import load_dotenv
from groq import Groq

load_dotenv()

groq_client = Groq(
    api_key=os.getenv("GROQ_API_KEY")
)

MODEL = "openai/gpt-oss-20b"

print("Groq client ready")

Groq client ready

In [3]:
test = groq_client.chat.completions.create(
    model=MODEL,
    messages=[
        {
            "role": "user",
            "content": """Write a short customer support response.

Customer:
@Uber_Support The link takes me to driver support?

Evidence:
Customer: @Uber_Support Which link?
Uber response: Sorry for the confusion! Please send us a note via the support link.

Respond directly to the customer."""
        }
    ],
    max_completion_tokens=600,
    reasoning_effort="low",
    include_reasoning=False,
    temperature=0.2
)

print("FINISH REASON:", test.choices[0].finish_reason)
print("CONTENT:", repr(test.choices[0].message.content))
print("FULL MESSAGE:", test.choices[0].message)

FINISH REASON: stop
CONTENT: 'Hi there! I’m sorry for the mix‑up. Please click the link below to open the **Passenger Support** page, where you can submit a note and we’ll get back to you right away:\n\n[Passenger Support – Submit a Note](https://help.uber.com/passenger)\n\nIf you’re still having trouble, let me know and I’ll walk you through it. Thanks for reaching out!'
FULL MESSAGE: ChatCompletionMessage(content='Hi there! I’m sorry for the mix‑up. Please click the link below to open the **Passenger Support** page, where you can submit a note and we’ll get back to you right away:\n\n[Passenger Support – Submit a Note](https://help.uber.com/passenger)\n\nIf you’re still having trouble, let me know and I’ll walk you through it. Thanks for reaching out!', role='assistant', annotations=None, executed_tools=None, function_call=None, reasoning=None, tool_calls=None)

In [6]:
import pandas as pd

golden_eval = pd.read_csv("../data/llm_golden_predictions.csv")

print(golden_eval.shape)
print(golden_eval.columns.tolist())

(200, 6)
['text_customer', 'text_uber', 'intent', 'escalate', 'predicted_intent', 'predicted_escalate']

In [7]:
response_eval = golden_eval.sample(
    n=40,
    random_state=456
).copy()

response_eval = response_eval.reset_index(drop=True)

print(response_eval.shape)

(40, 6)

In [8]:
golden_eval = pd.read_csv("../data/llm_golden_predictions.csv")

print(golden_eval.shape)
print(golden_eval.columns.tolist())

(200, 6)
['text_customer', 'text_uber', 'intent', 'escalate', 'predicted_intent', 'predicted_escalate']

In [9]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

# Load the original Uber pairs
uber_pairs = pd.read_csv("../data/uber_intent_sample.csv")

print(uber_pairs.shape)
print(uber_pairs.columns.tolist())

(300, 2)
['text_customer', 'text_uber']

In [10]:
twcs = pd.read_csv("../data/twcs.csv")

print(twcs.shape)
print(twcs.columns.tolist())

(2811774, 7)
['tweet_id', 'author_id', 'inbound', 'created_at', 'text', 'response_tweet_id', 'in_response_to_tweet_id']

In [12]:
print(
    twcs[twcs["text"].astype(str).str.contains(
        "Uber_Support",
        case=False,
        na=False
    )]["author_id"].value_counts().head(20)
)

author_id
658588    75
139533    65
316912    50
128445    48
131440    47
271774    42
325710    41
126107    38
198731    37
528154    36
146011    35
202742    31
170280    29
197483    29
276690    29
392017    27
505393    27
388171    26
158665    25
284340    25
Name: count, dtype: int64

In [13]:
# Look at non-inbound tweets that mention Uber/support language
uber_candidates = twcs[
    (twcs["inbound"] == False) &
    (twcs["text"].astype(str).str.contains(
        "send us a note|send us a DM|we're here to help|sorry to hear",
        case=False,
        na=False
    ))
]

print(uber_candidates["author_id"].value_counts().head(20))

author_id
Uber_Support       30235
AppleSupport       15906
AmazonHelp          8965
TMobileHelp         5521
AskPayPal           4133
sprintcare          3415
SpotifyCares        2968
comcastcares        2905
AirbnbHelp          2712
AskLyft             2582
Delta               2557
AldiUK              2333
British_Airways     2300
Tesco               2025
VirginTrains        1868
UPSHelp             1614
AskPlayStation      1558
SouthwestAir        1477
ATVIAssist          1453
hulu_support        1436
Name: count, dtype: int64

In [14]:
uber_tweets = twcs[twcs["author_id"].astype(str) == "Uber_Support"].copy()

print("Uber tweets:", len(uber_tweets))

Uber tweets: 56270

In [15]:
# Keep only Uber responses that have a parent customer tweet
uber_responses = uber_tweets[
    uber_tweets["in_response_to_tweet_id"].notna()
].copy()

print("Uber responses with parent:", len(uber_responses))

Uber responses with parent: 56261

In [17]:
print("tweet_id example:")
print(twcs["tweet_id"].head().tolist())

print("\nin_response_to_tweet_id example:")
print(twcs["in_response_to_tweet_id"].dropna().head().tolist())

print("\nTypes:")
print("tweet_id:", twcs["tweet_id"].dtype)
print("in_response_to_tweet_id:", twcs["in_response_to_tweet_id"].dtype)

tweet_id example:
[1, 2, 3, 4, 5]

in_response_to_tweet_id example:
[3.0, 1.0, 4.0, 5.0, 6.0]

Types:
tweet_id: int64
in_response_to_tweet_id: float64

In [18]:
# Convert the response-to ID to a nullable integer
uber_responses = uber_tweets[
    uber_tweets["in_response_to_tweet_id"].notna()
].copy()

uber_responses["in_response_to_tweet_id"] = (
    uber_responses["in_response_to_tweet_id"]
    .astype(int)
)

# Create a lookup of every tweet
tweet_lookup = twcs[["tweet_id", "text"]].copy()

# Match Uber responses to the customer tweet they replied to
uber_pairs = uber_responses.merge(
    tweet_lookup,
    left_on="in_response_to_tweet_id",
    right_on="tweet_id",
    how="inner"
)

# Rename the text columns
uber_pairs = uber_pairs.rename(
    columns={
        "text_x": "text_uber",
        "text_y": "text_customer"
    }
)

# Keep only what we need
uber_pairs = uber_pairs[
    ["text_customer", "text_uber"]
].dropna()

print("Usable Uber pairs:", len(uber_pairs))
print(uber_pairs.head())

Usable Uber pairs: 56193
                                       text_customer  \
0  @115873 you need to correct false charges from...
1  @115872 Happy to follow up! Contact us via htt...
2  @115873 my driver just drove me to the departm...
3  @Uber_Support I’m not getting your texts. http...
4  @115877 got this threw my door today went to o...

                                           text_uber
0  @115872 Happy to follow up! Contact us via htt...
1  @115872 We apologize for the trouble! Send us ...
2  @115874 We're here to help! Send us a note her...
3  @115875 We’re here to help, Travis! Send us a ...
4  @115876 For more info about UberEats availabil...

In [19]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

# Exclude golden-set customer messages to prevent evaluation leakage
golden_customers = set(golden_eval["text_customer"])

retrieval_corpus = uber_pairs[
    ~uber_pairs["text_customer"].isin(golden_customers)
].copy()

print("Original pairs:", len(uber_pairs))
print("Retrieval corpus:", len(retrieval_corpus))
print("Golden examples excluded:",
      len(uber_pairs) - len(retrieval_corpus))


# Build TF-IDF representation
retriever_vectorizer = TfidfVectorizer(
    lowercase=True,
    stop_words="english",
    ngram_range=(1, 2),
    max_features=50000
)

retriever_matrix = retriever_vectorizer.fit_transform(
    retrieval_corpus["text_customer"]
)


def retrieve_similar_cases(query, top_k=3):
    query_vector = retriever_vectorizer.transform([query])

    similarities = cosine_similarity(
        query_vector,
        retriever_matrix
    ).flatten()

    top_indices = similarities.argsort()[-top_k:][::-1]

    results = retrieval_corpus.iloc[top_indices].copy()

    results["similarity"] = similarities[top_indices]

    return results


print("Retriever ready!")

Original pairs: 56193
Retrieval corpus: 55989
Golden examples excluded: 204
Retriever ready!

In [20]:
import os
from dotenv import load_dotenv
from groq import Groq

load_dotenv()

client = Groq(
    api_key=os.getenv("GROQ_API_KEY")
)

MODEL = "openai/gpt-oss-20b"


def generate_grounded_response(customer_message: str, retrieved_cases) -> str:

    evidence = ""

    for i, (_, row) in enumerate(retrieved_cases.iterrows(), start=1):
        evidence += f"""
Case {i}:
Customer: {row["text_customer"]}
Historical Uber response: {row["text_uber"]}
Similarity: {row["similarity"]:.3f}
"""

    prompt = f"""
You are an Uber customer support assistant.

Your task is to draft a helpful support response to the customer using
ONLY the information supported by the historical cases provided below.

Customer message:
"{customer_message}"

Historical cases:
{evidence}

Rules:
- Use the historical cases as evidence of how similar issues were handled.
- Do not invent Uber policies, refunds, credits, compensation, guarantees,
  investigations, or actions that are not supported by the evidence.
- Do not claim that you personally performed an investigation or took an action.
- If the historical evidence does not provide enough information to resolve
  the customer's issue, acknowledge the issue and direct the customer to
  contact Uber Support through the appropriate support channel.
- Do not mention the historical cases or similarity scores.
- Keep the response concise, professional, and empathetic.
- Respond directly to the customer.

Return ONLY the support response.
"""

    response = client.chat.completions.create(
        model=MODEL,
        messages=[
            {
                "role": "user",
                "content": prompt
            }
        ],
        max_completion_tokens=600,
        reasoning_effort="low",
        include_reasoning=False,
        temperature=0.2
    )

    content = response.choices[0].message.content

    if not content:
        return "Unable to generate a response."

    return content.strip()


print("Response generator ready!")

Response generator ready!

In [21]:
test_customer = golden_eval.loc[0, "text_customer"]

test_retrieved = retrieve_similar_cases(
    test_customer,
    top_k=3
)

test_generated = generate_grounded_response(
    test_customer,
    test_retrieved
)

print("CUSTOMER:")
print(test_customer)

print("\nGENERATED RESPONSE:")
print(test_generated)

print("\nRETRIEVED CASES:")
print(test_retrieved[["text_customer", "text_uber", "similarity"]].to_string(index=False))

CUSTOMER:
@Uber_Support Yo what’s with this $300 charge? I needed an Uber and this Uber driver never even showed to pick me up? How am I getting charged for 1. A ride I never took &amp; 2. A mess I couldn’t have made. Tried to make a simple correction and then y’all charged me more?? https://t.co/DUtC7SKKut

GENERATED RESPONSE:
@Uber_Support I’m sorry to hear about the charge. Please send us a note at https://t.co/dInR3racif so we can look into this for you.

RETRIEVED CASES:
                                                                                                                               text_customer                                                                                                             text_uber  similarity
@Uber_Support just charged me for a ride that I never took. I waited for the driver, called the driver - he never showed up, but charged me. @199206 That's not okay, Michelle. Please send us a note at https://t.co/593jusCquh so we can look into this for you.    0.261816
                                                @115873 your a bitch. You charged me for a ride I️ never took. 🤬 always some shit with uber.                               @482626 Here to help! Send us a note via https://t.co/dInR3racif and we'll be in touch.    0.231821
                                                                    @115873 got charged for a ride I never took....how can I get reimbursed?                  @491019 Here to help! Follow up here; https://t.co/dInR3racif, and our team will connect right away.    0.221760

In [22]:
response_eval = golden_eval.sample(
    n=40,
    random_state=456
).copy().reset_index(drop=True)

response_eval["generated_response"] = ""
response_eval["retrieved_evidence"] = None

for i in range(len(response_eval)):
    customer_message = response_eval.loc[i, "text_customer"]

    retrieved = retrieve_similar_cases(
        customer_message,
        top_k=3
    )

    generated = generate_grounded_response(
        customer_message,
        retrieved
    )

    response_eval.loc[i, "generated_response"] = generated
    response_eval.loc[i, "retrieved_evidence"] = retrieved

    print(f"Generated {i+1}/40")

response_eval.to_pickle("../data/response_eval.pkl")

print("\nResponse generation complete!")

Generated 1/40
Generated 2/40
Generated 3/40
Generated 4/40
Generated 5/40
Generated 6/40
Generated 7/40
Generated 8/40
Generated 9/40
Generated 10/40
Generated 11/40
Generated 12/40
Generated 13/40
Generated 14/40
Generated 15/40
Generated 16/40
Generated 17/40
Generated 18/40
Generated 19/40
Generated 20/40
Generated 21/40
Generated 22/40
Generated 23/40
Generated 24/40
Generated 25/40
Generated 26/40
Generated 27/40
Generated 28/40
Generated 29/40
Generated 30/40
Generated 31/40
Generated 32/40
Generated 33/40
Generated 34/40
Generated 35/40
Generated 36/40
Generated 37/40
Generated 38/40
Generated 39/40
Generated 40/40

Response generation complete!

In [23]:
human_eval = response_eval.head(20).copy()

human_eval["helpfulness"] = ""
human_eval["grounding"] = ""
human_eval["actionability"] = ""
human_eval["appropriateness"] = ""

# Avoid pandas dtype issues when we later store integers
human_eval["helpfulness"] = human_eval["helpfulness"].astype(object)
human_eval["grounding"] = human_eval["grounding"].astype(object)
human_eval["actionability"] = human_eval["actionability"].astype(object)
human_eval["appropriateness"] = human_eval["appropriateness"].astype(object)

print(human_eval.shape)

(20, 12)

In [27]:
for i in range(len(human_eval)):
    human_eval.loc[i, "retrieved_evidence"] = retrieve_similar_cases(
        human_eval.loc[i, "text_customer"],
        top_k=3
    )

print("Retrieved evidence restored.")

print(type(human_eval.loc[0, "retrieved_evidence"]))

Retrieved evidence restored.
<class 'float'>

In [28]:
# ============================================================
# HUMAN EVALUATION OF GENERATED SUPPORT RESPONSES
# ============================================================

import pandas as pd

# ------------------------------------------------------------
# 1. Load the 40 generated response examples
# ------------------------------------------------------------

response_eval = pd.read_pickle("../data/response_eval.pkl")

print("Response evaluation set:", response_eval.shape)
print(
    "Empty generated responses:",
    response_eval["generated_response"].isna().sum()
    + (response_eval["generated_response"].astype(str).str.strip() == "").sum()
)

# ------------------------------------------------------------
# 2. Select 20 examples for human evaluation
# ------------------------------------------------------------

human_eval = response_eval.head(20).copy()

# Add human scoring columns
human_eval["helpfulness"] = ""
human_eval["grounding"] = ""
human_eval["actionability"] = ""
human_eval["appropriateness"] = ""

# Use object dtype so integers can be stored later
for col in [
    "helpfulness",
    "grounding",
    "actionability",
    "appropriateness"
]:
    human_eval[col] = human_eval[col].astype(object)

print("\nHuman evaluation set:", human_eval.shape)

# ------------------------------------------------------------
# 3. Human labeling loop
# ------------------------------------------------------------

for i in range(len(human_eval)):

    required = [
        "helpfulness",
        "grounding",
        "actionability",
        "appropriateness"
    ]

    # Skip examples that have already been completely labeled
    if all(
        str(human_eval.loc[i, col]).strip() in {"1", "2", "3"}
        for col in required
    ):
        continue

    customer_message = human_eval.loc[i, "text_customer"]

    # Retrieve the evidence fresh.
    # We do NOT store the DataFrame inside human_eval.
    evidence = retrieve_similar_cases(
        customer_message,
        top_k=3
    )

    print("\n" + "=" * 90)
    print(f"EXAMPLE {i + 1}/20")
    print("=" * 90)

    # --------------------------------------------------------
    # Customer
    # --------------------------------------------------------

    print("\nCUSTOMER:")
    print(customer_message)

    # --------------------------------------------------------
    # Generated response
    # --------------------------------------------------------

    print("\nGENERATED RESPONSE:")
    print(human_eval.loc[i, "generated_response"])

    # --------------------------------------------------------
    # Retrieved evidence
    # --------------------------------------------------------

    print("\nRETRIEVED EVIDENCE:")

    for j, (_, row) in enumerate(
        evidence.iterrows(),
        start=1
    ):
        print(f"\nCase {j}:")
        print("Customer:", row["text_customer"])
        print("Uber response:", row["text_uber"])
        print("Similarity:", round(row["similarity"], 3))

    # --------------------------------------------------------
    # Human scores
    # --------------------------------------------------------

    print("\n--- LABEL THIS RESPONSE ---")

    # Helpfulness
    while True:
        helpfulness = input(
            "Helpfulness (1=poor, 2=partial, 3=good): "
        ).strip()

        if helpfulness in {"1", "2", "3"}:
            break

        print("Please enter 1, 2, or 3.")

    # Grounding
    while True:
        grounding = input(
            "Grounding (1=unsupported, 2=mostly grounded, 3=fully grounded): "
        ).strip()

        if grounding in {"1", "2", "3"}:
            break

        print("Please enter 1, 2, or 3.")

    # Actionability
    while True:
        actionability = input(
            "Actionability (1=none, 2=generic, 3=useful): "
        ).strip()

        if actionability in {"1", "2", "3"}:
            break

        print("Please enter 1, 2, or 3.")

    # Appropriateness
    while True:
        appropriateness = input(
            "Appropriateness (1=inappropriate, 2=acceptable, 3=good): "
        ).strip()

        if appropriateness in {"1", "2", "3"}:
            break

        print("Please enter 1, 2, or 3.")

    # --------------------------------------------------------
    # Save labels
    # --------------------------------------------------------

    human_eval.loc[i, "helpfulness"] = int(helpfulness)
    human_eval.loc[i, "grounding"] = int(grounding)
    human_eval.loc[i, "actionability"] = int(actionability)
    human_eval.loc[i, "appropriateness"] = int(appropriateness)

    # Save after EVERY example
    human_eval.to_csv(
        "../data/human_response_eval.csv",
        index=False
    )

    print(f"\n✅ Saved example {i + 1}/20")


print("\n" + "=" * 90)
print("HUMAN EVALUATION COMPLETE")
print("=" * 90)

print(
    human_eval[
        [
            "helpfulness",
            "grounding",
            "actionability",
            "appropriateness"
        ]
    ]
)

Response evaluation set: (40, 8)
Empty generated responses: 0

Human evaluation set: (20, 12)

==========================================================================================
EXAMPLE 1/20
==========================================================================================

CUSTOMER:
@115877 what’s the deal when they don’t deliver your full order? This has now happened twice to my Mrs with no refund ? A want fed mate

GENERATED RESPONSE:
I’m sorry to hear that your order was incomplete and that you haven’t received a refund yet. Please send us a direct message with your email address and the details of the order so we can look into this for you. Thank you.

RETRIEVED EVIDENCE:

Case 1:
Customer: @115877 why don't you deliver in Wolverhampton
Uber response: @299021 We're working hard to expand our service area. Stay tuned to our website for updates: https://t.co/Mf9vzZ0uru
Similarity: 0.332

Case 2:
Customer: @Uber_Support All I️ can show you mate https://t.co/DWVDq0qWFi
Uber response: @505272 Sorry to hear about the troubles, Connor. Please send us a note using https://t.co/s9SVm1UzLa so we can look into this for you.
Similarity: 0.281

Case 3:
Customer: @Uber_Support This happened twice! And I have been charged twice, can you please credit me twice!
Uber response: @493478 We're here to help! Send us a DM with your email address and more details so we can follow up.
Similarity: 0.252

--- LABEL THIS RESPONSE ---

✅ Saved example 1/20

==========================================================================================
EXAMPLE 2/20
==========================================================================================

CUSTOMER:
@115873 does one get a small refund when your drivers cancel the trip? Waited 7mins and the trip got cancelled! We normally get charged for cancelling a trip 3mins after it’s booked! #daylightrobbery #getyouracttogether

GENERATED RESPONSE:
Hi there! I’m sorry to hear about the inconvenience. Please send us a note at https://t.co/593jusCquh so our team can review the situation and get back to you.

RETRIEVED EVIDENCE:

Case 1:
Customer: @Uber_Support I had a driver cancel my trip after I waited for him last night, I was charged.
After disputing it I was told I'll still be chartered. I didn't cancel the trip AT ALL.
Uber response: @250928 Here to help. Send us a note at https://t.co/593jusCquh so our team can connect.
Similarity: 0.315

Case 2:
Customer: If @115873 wants to charge me $16 for cancelling a trip, I should also get $16 added to my acc when a drivers cancel my trip.Just not cricket😠
Uber response: @720691 Hi there! Please write in your suggestion to https://t.co/zUe0dj6yoX and fill out the 4 boxes at the bottom so we can get in touch.
Similarity: 0.292

Case 3:
Customer: @115873 Why I am charged for this trip?? I had requested the trip but didn't travel and the trip got cancelled automatically with the charges levied to me. https://t.co/YxGdsBlIpO
Uber response: @218667 So sorry for the trouble! Please send us a note here; https://t.co/1xM0TILvAI so our team can connect.
Similarity: 0.26

--- LABEL THIS RESPONSE ---

✅ Saved example 2/20

==========================================================================================
EXAMPLE 3/20
==========================================================================================

CUSTOMER:
@Uber_Support The link takes me to driver support?

GENERATED RESPONSE:
@Uber_Support We’re sorry for the confusion. Please send us a DM with your email address so we can look into the link issue and help you get the correct support page.

RETRIEVED EVIDENCE:

Case 1:
Customer: @Uber_Support This link again takes me to sign in page https://t.co/PLzQBVQIJ6
Uber response: @373397 We can definitely take a look! Send us a DM with your email address so we can assist.
Similarity: 0.478

Case 2:
Customer: @Uber_Support Which link?
Uber response: @815682 Sorry for the confusion! Please send us a note via https://t.co/3h8wdQ4EJK so we can assist further.
Similarity: 0.444

Case 3:
Customer: @Uber_Support What is that link ?
Uber response: @316912 Hello, Mashanda. Please do those following steps and you will be able to see the link we provided. We made some adjustments to your account.
Similarity: 0.444

--- LABEL THIS RESPONSE ---

✅ Saved example 3/20

==========================================================================================
EXAMPLE 4/20
==========================================================================================

CUSTOMER:
@115873 can someone please explain to me how I can get ahold of uber I tried to email I'm not getting any responses back at all

GENERATED RESPONSE:
Hi there! I’m sorry you’re having trouble getting a response. Please send us a direct message with your account email address and a brief description of the issue, and we’ll connect you with a member of our support team right away. Thank you for your patience.

RETRIEVED EVIDENCE:

Case 1:
Customer: @Uber_Support I really need help. please contact me. i haven't gotten ahold of my driver and my purse is in there. he has not voicemail set up. i can't get ahold of anyone at uber . PLEASE email me or call me . please.
Uber response: @682782 Find out more about contacting your driver here; https://t.co/oY5vj3NqP3
Similarity: 0.3

Case 2:
Customer: @Uber_Support tried to email uber support but can't seem to get anything except auto responses back-Can I please get in contact w/ a human?
Uber response: @480164 Happy to help, Lauren. Please send us a DM with your account email address + details and we'll connect.
Similarity: 0.283

Case 3:
Customer: @Uber_Support I've been sending messages in app as well as via email and I'm getting no responses.
Uber response: @135858 Thanks for reaching out. A member of our specialized team will be in touch with you shortly to discuss this matter further via email. We appreciate your patience.
Similarity: 0.271

--- LABEL THIS RESPONSE ---

✅ Saved example 4/20

==========================================================================================
EXAMPLE 5/20
==========================================================================================

CUSTOMER:
@Uber_Support what's the support email?

GENERATED RESPONSE:
@Uber_Support Here to help! Send us a note at https://t.co/Md7v036OoC so we can assist.

RETRIEVED EVIDENCE:

Case 1:
Customer: @Uber_Support what’s the # to call support?
Uber response: @484907 Simply click on the 'Help' button in the app to contact us and we'll be in touch.
Similarity: 0.701

Case 2:
Customer: @Uber_Support @399519 What is the support email Adresse ? I sent you a message on here.
Uber response: @399520 We're here to help! Send us a note at https://t.co/Md7v036OoC so we can assist.
Similarity: 0.572

Case 3:
Customer: @Uber_Support:  Do you have a customer support email?
Uber response: @117521 Here to help! Connect with us through https://t.co/zUe0dj6yoX and we'll be in touch.
Similarity: 0.549

--- LABEL THIS RESPONSE ---

✅ Saved example 5/20

==========================================================================================
EXAMPLE 6/20
==========================================================================================

CUSTOMER:
My uber app is an asshole. The pick up address shows up correctly on my end, but it sends the driver to a place down the street 🙃

GENERATED RESPONSE:
Hi there! I’m sorry you’re having trouble with the pickup location. Please send us a direct message with your email address so we can look into this for you. Thank you!

RETRIEVED EVIDENCE:

Case 1:
Customer: @Uber_Support No sorry not for a current order, but all the time. My address shows a street but my house comes off the alley at the back
Uber response: @735357 We're here to help! Send us a DM with your email address so we can follow up.
Similarity: 0.267

Case 2:
Customer: @Uber_Support  I booked a trip...  the driver could never find my place i watched him on the app on the and he circling around my place
Uber response: @193862 Hello, Titus. We've gone ahead and followed up with you via DM regarding this matter.
Similarity: 0.262

Case 3:
Customer: When @115873 sends your driver to the wrong place and so you miss your train....yea.....great
Uber response: @208346 Here to help. Send us a note at https://t.co/K05RdmK3t4 so our team can connect.
Similarity: 0.247

--- LABEL THIS RESPONSE ---

✅ Saved example 6/20

==========================================================================================
EXAMPLE 7/20
==========================================================================================

CUSTOMER:
@Uber_Support check dms please

GENERATED RESPONSE:
@YourUsername We’ve just sent you a message via DM. Please check your inbox for further details.

RETRIEVED EVIDENCE:

Case 1:
Customer: @Uber_Support Check DMs
Uber response: @128700 We just got back to you via DM, Nita.
Similarity: 1.0

Case 2:
Customer: @Uber_Support check your dms!!!
Uber response: @244444 Hi, Chris. We've followed up via DM.
Similarity: 1.0

Case 3:
Customer: @Uber_Support check your DMs please
Uber response: @244453 We're sorry to hear this was your experience. Kindly contact us via https://t.co/QsI1vsvcif and we'll be in touch.
Similarity: 1.0

--- LABEL THIS RESPONSE ---

✅ Saved example 7/20

==========================================================================================
EXAMPLE 8/20
==========================================================================================

CUSTOMER:
- Thanks @Uber_Support , my account is activated now.

GENERATED RESPONSE:
Thanks for letting us know! If you need anything else, just let us know.

RETRIEVED EVIDENCE:

Case 1:
Customer: @Uber_Support How can i do to get my account activated? Email couldnt work. I got email that @115873 activated my account but its not activated.
Uber response: @404868 Sorry to hear you're having trouble logging into your account, Ahmed. DM us your email address/phone number and our team can follow up.
Similarity: 0.628

Case 2:
Customer: @Uber_Support I need my account activated back
Uber response: @133604 We're not able to make changes to accounts via social media due to privacy reasons, Vishaul. Please continue to follow up with your in-app support messages regarding this issue. We appreciate your patience and understanding thus far.
Similarity: 0.562

Case 3:
Customer: @Uber_Support Thanks @Uber_Support. Have done so now.
Uber response: @528852 Thanks, Liz! We've just responded to your DM, please check there for more information.
Similarity: 0.478

--- LABEL THIS RESPONSE ---
Please enter 1, 2, or 3.

✅ Saved example 8/20

==========================================================================================
EXAMPLE 9/20
==========================================================================================

CUSTOMER:
Its nt a cab service,its an extortion service.Driver refuses to come,talkes in vulgar way,n they charges fee for that.
@119983 @115873

GENERATED RESPONSE:
I’m sorry you’re having trouble with the driver. Please send us a note here so we can look into the situation: https://t.co/JyzdtQmyxT. We’ll review the issue and get back to you as soon as possible.

RETRIEVED EVIDENCE:

Case 1:
Customer: @119983 @115873 @80107 @Uber_Support
Uber response: @589106 Hey, Noora. Go ahead and DM us your account email anytime. We look forward to your reply so we can assist you further.
Similarity: 0.298

Case 2:
Customer: Trying to figure out why @115873 charges me a fee for trying to cancel when the driver refuses to move their car in attempt to get more people
Uber response: @294201 We're so sorry this was your experience. Please send us a note here; https://t.co/JyzdtQmyxT so our team can connect.
Similarity: 0.291

Case 3:
Customer: @Uber_Support And it always charges me a fee. Boo.
Uber response: @515564 If we need to review a cancellation fee for you, please let us know at https://t.co/QsI1vsvcif so we can follow up.
Similarity: 0.277

--- LABEL THIS RESPONSE ---

✅ Saved example 9/20

==========================================================================================
EXAMPLE 10/20
==========================================================================================

CUSTOMER:
@Uber_Support we need a way to complain about drivers who accept the trip, talk to us and don't turn up

GENERATED RESPONSE:
I’m sorry you’re experiencing this. Please let us investigate by contacting Uber Support directly. You can reach us through the support link in the app or by sending a note here: https://t.co/e8HVoseGiP. We’ll be in touch as soon as possible.

RETRIEVED EVIDENCE:

Case 1:
Customer: #Uber please train your cab drivers how to accept the trip. They accept and ask us to cancel the trip and we will be charged for that.
Uber response: @426285 Here to help! Connect with us through https://t.co/zUe0dj6yoX and we'll be in touch.
Similarity: 0.299

Case 2:
Customer: Hey @115873 tell your drivers to get it together. On two separate occasions, I’ve had drivers accept my trip and drive the OPPOSITE way.
Uber response: @338036 Sorry for the trouble! Send us a note here, https://t.co/e8HVoseGiP, and our team will be in touch.
Similarity: 0.26

Case 3:
Customer: @Uber_Support Just tell your drivers not to accept a trip if they can’t complete the first. It’s not rocket science
Uber response: @638794 We're here to help! Send us a DM with your email address so we can connect.
Similarity: 0.255

--- LABEL THIS RESPONSE ---

✅ Saved example 10/20

==========================================================================================
EXAMPLE 11/20
==========================================================================================

CUSTOMER:
@115877 - customer service number please your driver took 35 min and delivered half my order.

GENERATED RESPONSE:
Hi @115877, I’m sorry to hear about the delay and missing items. Please DM us with the email address linked to your account and the order details so we can look into this for you. Thank you.

RETRIEVED EVIDENCE:

Case 1:
Customer: @115877 And only delivered half my order.
Uber response: @168463 Send us a DM with your email and phone number linked to your account. Along with the details on what items were missing.
Similarity: 0.498

Case 2:
Customer: @115877 what’s up with your customer service?
Uber response: @628882 Here to help! Can you please send us a DM with your email address and additional details of your concern, so we can follow up?
Similarity: 0.407

Case 3:
Customer: Driver was super late and delivered half the order. Never using @115877 again 👿
Uber response: @352283 Oh No! This doesn't seem right. Please DM us with your email and order details so we can take a deeper look.
Similarity: 0.354

--- LABEL THIS RESPONSE ---

✅ Saved example 11/20

==========================================================================================
EXAMPLE 12/20
==========================================================================================

CUSTOMER:
@Uber_Support its ok if you cannot provide me the driver details... i just wanted the exact pick up point from Rajokri to the airport this evening... it wasnt very clear on the ETA.. could you kindly help with just that...

GENERATED RESPONSE:
Hi! I’m sorry I don’t have the exact pickup point details available here. Please reach out to Uber Support directly through the app or the help center so we can provide the precise location for your ride from Rajokri to the airport. Thank you for understanding.

RETRIEVED EVIDENCE:

Case 1:
Customer: @Uber_Support Ok
Uber response: @140699 We've been in touch via DM. Please check your inbox for updates! Thanks.
Similarity: 0.289

Case 2:
Customer: @Uber_Support ok
Uber response: @371188 Thanks! We look forward to your reply so we can assist you further.
Similarity: 0.289

Case 3:
Customer: @Uber_Support Ok
Uber response: @454454 Hi, Suraj! Go ahead and check your DM for further details.
Similarity: 0.289

--- LABEL THIS RESPONSE ---

✅ Saved example 12/20

==========================================================================================
EXAMPLE 13/20
==========================================================================================

CUSTOMER:
Highly disappointed with @115873 @Uber_Support. This is the third time, I filed a complaint against their driver but never got any support/help/reply.
 Yesterday I stucked with the wrong driver who allowed someone to accompany him &amp; took wrong route to GNH, Gurgaon.

GENERATED RESPONSE:
I’m sorry to hear you’ve had a frustrating experience. To help us look into this, please send a direct message to @698394 with your email address and a brief description of the incident. They’ll be able to review your complaint and get back to you. If you need immediate assistance, you can also reach out through the Uber app’s Help section. Thank you for bringing this to our attention.

RETRIEVED EVIDENCE:

Case 1:
Customer: Filed a complaint against an @115873 driver. Let’s see how they will respond.
Uber response: @698394 We're here to help! Send us a DM with your email address so we can connect.
Similarity: 0.214

Case 2:
Customer: Hii @115873 @Uber_Support need a help please reply
Uber response: @530570 Hi there! Please reach out to https://t.co/zUe0dj6yoX and fill out the boxes at the bottom so we can get in touch.
Similarity: 0.202

Case 3:
Customer: Highly disappointed in @115873 lately. Strongly considering deleting my account and only using @115879
Uber response: @746933 Here to help! Send us a DM with your email address and more info so we can assist.
Similarity: 0.2

--- LABEL THIS RESPONSE ---

✅ Saved example 13/20

==========================================================================================
EXAMPLE 14/20
==========================================================================================

CUSTOMER:
@Uber_Support But he is not on tweeter

GENERATED RESPONSE:
Hi there! I’m sorry for the confusion. To keep your details private, we’ll need to move this conversation to a direct message. Please DM us your email address and phone number so we can look into the issue securely. Thank you!

RETRIEVED EVIDENCE:

Case 1:
Customer: @Uber_Support Then why do you have an account in Tweeter and why is it called Uber Support
Uber response: @226510 Happy to explain, Sailesh. We're Uber Support and we're always here to help, but sometimes there is personal and sensitive information that we cannot discuss publicly. This is why we ask you to DM us your email address and phone number so no one else can see it but us.
Similarity: 0.573

Case 2:
Customer: @Uber_Support I have sent you message on tweeter please check those messages, I have explained everything there
Uber response: @714120 Let's take a closer look! Send us a DM with your email address so we can connect.
Similarity: 0.485

Case 3:
Customer: @Uber_Support @205142 Where will i get the answer to my problem from tweeter or email. My email is __email__
Uber response: @205143 We see you've been in touch and are looking into this now. We'll be following up momentarily.
Similarity: 0.418

--- LABEL THIS RESPONSE ---

✅ Saved example 14/20

==========================================================================================
EXAMPLE 15/20
==========================================================================================

CUSTOMER:
@Uber_Support I'm a driver and I can't seem to get request on my phone

GENERATED RESPONSE:
@Uber_Support Here to help! Send us a note here: https://t.co/xMxswVLBKT and our team will assist you.

RETRIEVED EVIDENCE:

Case 1:
Customer: @Uber_Support  can't get request on my phone but the map shows it is busy. What's up ?
Uber response: @638799 Here to help! Send us a note here; https://t.co/xMxswVLBKT and our team will be able to assist!
Similarity: 0.431

Case 2:
Customer: @Uber_Support I have a problem when I finish the driver’s request telling me there is a mistake in the process

In [29]:
import json
import re


def llm_judge_response(
    customer_message: str,
    generated_response: str,
    retrieved_cases
):
    # Build the evidence shown to the judge
    evidence = ""

    for i, (_, row) in enumerate(
        retrieved_cases.iterrows(),
        start=1
    ):
        evidence += f"""
Case {i}:
Customer: {row["text_customer"]}
Historical Uber response: {row["text_uber"]}
"""

    prompt = f"""
You are evaluating an AI-generated Uber customer support response.

You must score the GENERATED RESPONSE using the CUSTOMER MESSAGE
and RETRIEVED EVIDENCE below.

CUSTOMER MESSAGE:
{customer_message}

GENERATED RESPONSE:
{generated_response}

RETRIEVED EVIDENCE:
{evidence}

Score the generated response on four dimensions.

HELPFULNESS:
1 = Does not meaningfully address the customer's problem
2 = Partially addresses the problem
3 = Clearly addresses the problem

GROUNDING:
1 = Makes important claims or promises unsupported by the retrieved evidence
2 = Mostly grounded but contains some questionable assumptions
3 = Fully supported by the retrieved evidence

ACTIONABILITY:
1 = Provides no useful next step
2 = Provides a generic next step
3 = Provides a clear and useful next step

APPROPRIATENESS:
1 = Inappropriate, unsafe, or unsuitable
2 = Acceptable but weak
3 = Professional, appropriate, and suitable

Important:
- Judge the GENERATED RESPONSE, not the historical responses.
- A generated response can be better written or more helpful than the
  historical responses and still receive a grounding score of 3.
- For grounding, determine whether the claims and actions in the generated
  response are supported by the retrieved evidence.
- Do not penalize a response merely because the historical response is
  generic.
- Do not reward a response merely because it sounds professional.
- Return exactly one JSON object.
- Do not include explanations outside the JSON.

Return:
{{
  "helpfulness": 1,
  "grounding": 1,
  "actionability": 1,
  "appropriateness": 1
}}
"""

    response = client.chat.completions.create(
        model=MODEL,
        messages=[
            {
                "role": "user",
                "content": prompt
            }
        ],
        max_completion_tokens=600,
        reasoning_effort="low",
        include_reasoning=False,
        temperature=0
    )

    content = response.choices[0].message.content

    if not content:
        raise ValueError("LLM judge returned an empty response.")

    # Extract JSON in case the model adds surrounding text
    match = re.search(r"\{.*\}", content, re.DOTALL)

    if not match:
        raise ValueError(
            f"Could not find JSON in judge response:\n{content}"
        )

    scores = json.loads(match.group())

    # Validate scores
    dimensions = [
        "helpfulness",
        "grounding",
        "actionability",
        "appropriateness"
    ]

    for dimension in dimensions:
        if dimension not in scores:
            raise ValueError(
                f"Missing score: {dimension}"
            )

        if scores[dimension] not in [1, 2, 3]:
            raise ValueError(
                f"Invalid {dimension} score: {scores[dimension]}"
            )

    return scores


print("LLM judge ready!")

LLM judge ready!

In [30]:
# Get Example 1
customer = human_eval.loc[0, "text_customer"]
generated = human_eval.loc[0, "generated_response"]

# Retrieve the same evidence again
evidence = retrieve_similar_cases(
    customer,
    top_k=3
)

# Ask the LLM judge to score it
judge_scores = llm_judge_response(
    customer,
    generated,
    evidence
)

print("LLM JUDGE SCORES:")
print(judge_scores)

LLM JUDGE SCORES:
{'helpfulness': 3, 'grounding': 3, 'actionability': 3, 'appropriateness': 3}

In [31]:
import time

judge_results = []

for i in range(len(human_eval)):

    customer = human_eval.loc[i, "text_customer"]
    generated = human_eval.loc[i, "generated_response"]

    # Retrieve the same evidence used for evaluation
    evidence = retrieve_similar_cases(
        customer,
        top_k=3
    )

    try:
        scores = llm_judge_response(
            customer,
            generated,
            evidence
        )

        judge_results.append(scores)

        print(
            f"Judged {i+1}/20: "
            f"{scores}"
        )

    except Exception as e:
        print(f"Error on example {i+1}: {e}")
        judge_results.append({
            "helpfulness": None,
            "grounding": None,
            "actionability": None,
            "appropriateness": None
        })

    time.sleep(1)


# Add judge scores to human_eval
human_eval["judge_helpfulness"] = [
    x["helpfulness"] for x in judge_results
]

human_eval["judge_grounding"] = [
    x["grounding"] for x in judge_results
]

human_eval["judge_actionability"] = [
    x["actionability"] for x in judge_results
]

human_eval["judge_appropriateness"] = [
    x["appropriateness"] for x in judge_results
]


# Save everything
human_eval.to_csv(
    "../data/human_vs_llm_judge.csv",
    index=False
)

print("\nLLM judging complete!")

Judged 1/20: {'helpfulness': 3, 'grounding': 3, 'actionability': 3, 'appropriateness': 3}
Judged 2/20: {'helpfulness': 2, 'grounding': 3, 'actionability': 3, 'appropriateness': 3}
Judged 3/20: {'helpfulness': 2, 'grounding': 3, 'actionability': 2, 'appropriateness': 3}
Judged 4/20: {'helpfulness': 3, 'grounding': 3, 'actionability': 3, 'appropriateness': 3}
Judged 5/20: {'helpfulness': 3, 'grounding': 3, 'actionability': 3, 'appropriateness': 3}
Judged 6/20: {'helpfulness': 2, 'grounding': 3, 'actionability': 3, 'appropriateness': 3}
Judged 7/20: {'helpfulness': 3, 'grounding': 3, 'actionability': 3, 'appropriateness': 3}
Judged 8/20: {'helpfulness': 2, 'grounding': 3, 'actionability': 2, 'appropriateness': 3}
Judged 9/20: {'helpfulness': 2, 'grounding': 3, 'actionability': 3, 'appropriateness': 3}
Judged 10/20: {'helpfulness': 2, 'grounding': 3, 'actionability': 3, 'appropriateness': 3}
Judged 11/20: {'helpfulness': 3, 'grounding': 3, 'actionability': 3, 'appropriateness': 3}
Judged 12/20: {'helpfulness': 2, 'grounding': 3, 'actionability': 2, 'appropriateness': 3}
Judged 13/20: {'helpfulness': 2, 'grounding': 3, 'actionability': 3, 'appropriateness': 3}
Judged 14/20: {'helpfulness': 1, 'grounding': 3, 'actionability': 2, 'appropriateness': 3}
Judged 15/20: {'helpfulness': 1, 'grounding': 3, 'actionability': 2, 'appropriateness': 3}
Judged 16/20: {'helpfulness': 2, 'grounding': 3, 'actionability': 3, 'appropriateness': 3}
Error on example 17: Error code: 429 - {'error': {'message': 'Rate limit reached for model `openai/gpt-oss-20b` in organization `org_01m2mk0xfhepn9ryykezta35em` service tier `on_demand` on tokens per day (TPD): Limit 200000, Used 199620, Requested 946. Please try again in 4m4.512s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error on example 18: Error code: 429 - {'error': {'message': 'Rate limit reached for model `openai/gpt-oss-20b` in organization `org_01m2mk0xfhepn9ryykezta35em` service tier `on_demand` on tokens per day (TPD): Limit 200000, Used 199617, Requested 899. Please try again in 3m42.911999999s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error on example 19: Error code: 429 - {'error': {'message': 'Rate limit reached for model `openai/gpt-oss-20b` in organization `org_01m2mk0xfhepn9ryykezta35em` service tier `on_demand` on tokens per day (TPD): Limit 200000, Used 199615, Requested 840. Please try again in 3m16.56s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error on example 20: Error code: 429 - {'error': {'message': 'Rate limit reached for model `openai/gpt-oss-20b` in organization `org_01m2mk0xfhepn9ryykezta35em` service tier `on_demand` on tokens per day (TPD): Limit 200000, Used 199612, Requested 802. Please try again in 2m58.848s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

LLM judging complete!

In [32]:
print(
    human_eval[
        [
            "judge_helpfulness",
            "judge_grounding",
            "judge_actionability",
            "judge_appropriateness"
        ]
    ]
)

    judge_helpfulness  judge_grounding  judge_actionability  \
0                 3.0              3.0                  3.0
1                 2.0              3.0                  3.0
2                 2.0              3.0                  2.0
3                 3.0              3.0                  3.0
4                 3.0              3.0                  3.0
5                 2.0              3.0                  3.0
6                 3.0              3.0                  3.0
7                 2.0              3.0                  2.0
8                 2.0              3.0                  3.0
9                 2.0              3.0                  3.0
10                3.0              3.0                  3.0
11                2.0              3.0                  2.0
12                2.0              3.0                  3.0
13                1.0              3.0                  2.0
14                1.0              3.0                  2.0
15                2.0              3.0                  3.0
16                NaN              NaN                  NaN
17                NaN              NaN                  NaN
18                NaN              NaN                  NaN
19                NaN              NaN                  NaN

    judge_appropriateness
0                     3.0
1                     3.0
2                     3.0
3                     3.0
4                     3.0
5                     3.0
6                     3.0
7                     3.0
8                     3.0
9                     3.0
10                    3.0
11                    3.0
12                    3.0
13                    3.0
14                    3.0
15                    3.0
16                    NaN
17                    NaN
18                    NaN
19                    NaN

In [33]:
print("Current model:", MODEL)

Current model: openai/gpt-oss-20b

In [34]:
models = groq_client.models.list()

for model in models.data:
    print(model.id)

whisper-large-v3-turbo
openai/gpt-oss-safeguard-20b
qwen/qwen3.8-27b
meta-llama/llama-prompt-guard-2-22m
groq/compound
groq/compound-mini
whisper-large-v3
allam-2-7b
canopylabs/orpheus-arabic-saudi
openai/gpt-oss-120b
canopylabs/orpheus-v1-english
meta-llama/llama-prompt-guard-2-86m
openai/gpt-oss-20b

In [35]:
i = 16  # Example 17

customer = human_eval.loc[i, "text_customer"]
generated = human_eval.loc[i, "generated_response"]

evidence = retrieve_similar_cases(
    customer,
    top_k=3
)

scores = llm_judge_response(
    customer,
    generated,
    evidence
)

print("Example 17 judge scores:")
print(scores)

Example 17 judge scores:
{'helpfulness': 1, 'grounding': 3, 'actionability': 2, 'appropriateness': 3}

In [36]:
for i in range(17, 20):  # Examples 18, 19, 20

    customer = human_eval.loc[i, "text_customer"]
    generated = human_eval.loc[i, "generated_response"]

    evidence = retrieve_similar_cases(
        customer,
        top_k=3
    )

    try:
        scores = llm_judge_response(
            customer,
            generated,
            evidence
        )

        human_eval.loc[i, "judge_helpfulness"] = scores["helpfulness"]
        human_eval.loc[i, "judge_grounding"] = scores["grounding"]
        human_eval.loc[i, "judge_actionability"] = scores["actionability"]
        human_eval.loc[i, "judge_appropriateness"] = scores["appropriateness"]

        print(f"Example {i+1}: {scores}")

    except Exception as e:
        print(f"Example {i+1} FAILED: {e}")

    import time
    time.sleep(2)

# Save
human_eval.to_csv(
    "../data/human_vs_llm_judge.csv",
    index=False
)

print("\nSaved judge results.")

Example 18: {'helpfulness': 1, 'grounding': 3, 'actionability': 2, 'appropriateness': 3}
Example 19 FAILED: Error code: 429 - {'error': {'message': 'Rate limit reached for model `openai/gpt-oss-20b` in organization `org_01m2mk0xfhepn9ryykezta35em` service tier `on_demand` on tokens per day (TPD): Limit 200000, Used 199828, Requested 903. Please try again in 5m15.792s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Example 20 FAILED: Error code: 429 - {'error': {'message': 'Rate limit reached for model `openai/gpt-oss-20b` in organization `org_01m2mk0xfhepn9ryykezta35em` service tier `on_demand` on tokens per day (TPD): Limit 200000, Used 199823, Requested 865. Please try again in 4m57.216s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

Saved judge results.

In [37]:
for i in [18, 19]:  # Examples 19 and 20

    customer = human_eval.loc[i, "text_customer"]
    generated = human_eval.loc[i, "generated_response"]

    evidence = retrieve_similar_cases(
        customer,
        top_k=3
    )

    try:
        scores = llm_judge_response(
            customer,
            generated,
            evidence
        )

        human_eval.loc[i, "judge_helpfulness"] = scores["helpfulness"]
        human_eval.loc[i, "judge_grounding"] = scores["grounding"]
        human_eval.loc[i, "judge_actionability"] = scores["actionability"]
        human_eval.loc[i, "judge_appropriateness"] = scores["appropriateness"]

        print(f"Example {i+1}: {scores}")

    except Exception as e:
        print(f"Example {i+1} FAILED: {e}")

    import time
    time.sleep(3)

human_eval.to_csv(
    "../data/human_vs_llm_judge.csv",
    index=False
)

print("Saved.")

Example 19: {'helpfulness': 2, 'grounding': 3, 'actionability': 3, 'appropriateness': 3}
Example 20 FAILED: Error code: 429 - {'error': {'message': 'Rate limit reached for model `openai/gpt-oss-20b` in organization `org_01m2mk0xfhepn9ryykezta35em` service tier `on_demand` on tokens per day (TPD): Limit 200000, Used 199169, Requested 843. Please try again in 5.184s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Saved.

In [38]:
i = 19  # Example 20

customer = human_eval.loc[i, "text_customer"]
generated = human_eval.loc[i, "generated_response"]

evidence = retrieve_similar_cases(
    customer,
    top_k=3
)

scores = llm_judge_response(
    customer,
    generated,
    evidence
)

# Save the judge scores
human_eval.loc[i, "judge_helpfulness"] = scores["helpfulness"]
human_eval.loc[i, "judge_grounding"] = scores["grounding"]
human_eval.loc[i, "judge_actionability"] = scores["actionability"]
human_eval.loc[i, "judge_appropriateness"] = scores["appropriateness"]

human_eval.to_csv(
    "../data/human_vs_llm_judge.csv",
    index=False
)

print("Example 20 judge scores:")
print(scores)

Example 20 judge scores:
{'helpfulness': 3, 'grounding': 3, 'actionability': 3, 'appropriateness': 3}

In [40]:
print(
    human_eval[
        [
            "helpfulness",
            "grounding",
            "actionability",
            "appropriateness",
            "judge_helpfulness",
            "judge_grounding",
            "judge_actionability",
            "judge_appropriateness"
        ]
    ]
)

   helpfulness grounding actionability appropriateness  judge_helpfulness  \
0            3         2             3               3                3.0
1            2         2             2               3                2.0
2            3         3             3               3                2.0
3            2         2             2               3                3.0
4            1         2             2               2                3.0
5            3         2             2               3                2.0
6            2         3             3               2                3.0
7            2         2             3               3                2.0
8            2         2             2               3                2.0
9            3         3             3               3                2.0
10           2         1             2               3                3.0
11           2         2             2               3                2.0
12           3         3             3               3                2.0
13           2         2             2               3                1.0
14           2         3             2               3                1.0
15           2         3             3               3                2.0
16           3         2             3               3                NaN
17           2         3             2               3                1.0
18           3         3             2               3                2.0
19           2         2             2               3                3.0

    judge_grounding  judge_actionability  judge_appropriateness
0               3.0                  3.0                    3.0
1               3.0                  3.0                    3.0
2               3.0                  2.0                    3.0
3               3.0                  3.0                    3.0
4               3.0                  3.0                    3.0
5               3.0                  3.0                    3.0
6               3.0                  3.0                    3.0
7               3.0                  2.0                    3.0
8               3.0                  3.0                    3.0
9               3.0                  3.0                    3.0
10              3.0                  3.0                    3.0
11              3.0                  2.0                    3.0
12              3.0                  3.0                    3.0
13              3.0                  2.0                    3.0
14              3.0                  2.0                    3.0
15              3.0                  3.0                    3.0
16              NaN                  NaN                    NaN
17              3.0                  2.0                    3.0
18              3.0                  3.0                    3.0
19              3.0                  3.0                    3.0

In [41]:
human_eval.loc[15, "helpfulness"] = 2

In [42]:
print(human_eval.loc[15, ["helpfulness", "judge_helpfulness"]])

helpfulness            2
judge_helpfulness    2.0
Name: 15, dtype: object

In [44]:
judge_cols = [
    "judge_helpfulness",
    "judge_grounding",
    "judge_actionability",
    "judge_appropriateness"
]

for col in judge_cols:
    missing = human_eval[human_eval[col].isna()]
    if len(missing) > 0:
        print(f"\n{col} has {len(missing)} missing value(s)")
        print("Example numbers:", [i + 1 for i in missing.index.tolist()])

judge_helpfulness has 1 missing value(s)
Example numbers: [17]

judge_grounding has 1 missing value(s)
Example numbers: [17]

judge_actionability has 1 missing value(s)
Example numbers: [17]

judge_appropriateness has 1 missing value(s)
Example numbers: [17]

In [45]:
print(human_eval.loc[16, [
    "judge_helpfulness",
    "judge_grounding",
    "judge_actionability",
    "judge_appropriateness"
]])

judge_helpfulness       NaN
judge_grounding         NaN
judge_actionability     NaN
judge_appropriateness   NaN
Name: 16, dtype: float64

In [46]:
idx = 16

row = human_eval.loc[idx]

retrieved_cases = retrieve_similar_cases(
    row["text_customer"],
    top_k=3
)

scores = llm_judge_response(
    row["text_customer"],
    row["generated_response"],
    retrieved_cases
)

print(scores)

{'helpfulness': 2, 'grounding': 3, 'actionability': 2, 'appropriateness': 3}

In [47]:
human_eval.loc[idx, "judge_helpfulness"] = scores["helpfulness"]
human_eval.loc[idx, "judge_grounding"] = scores["grounding"]
human_eval.loc[idx, "judge_actionability"] = scores["actionability"]
human_eval.loc[idx, "judge_appropriateness"] = scores["appropriateness"]

human_eval.to_csv("../data/human_response_eval.csv", index=False)

In [48]:
from sklearn.metrics import cohen_kappa_score

dimensions = {
    "helpfulness": ("helpfulness", "judge_helpfulness"),
    "grounding": ("grounding", "judge_grounding"),
    "actionability": ("actionability", "judge_actionability"),
    "appropriateness": ("appropriateness", "judge_appropriateness")
}

agreement_results = {}

for name, (human_col, judge_col) in dimensions.items():
    human_scores = human_eval[human_col].astype(int)
    judge_scores = human_eval[judge_col].astype(int)

    kappa = cohen_kappa_score(
        human_scores,
        judge_scores,
        weights="quadratic"
    )

    exact_agreement = (human_scores == judge_scores).mean()

    agreement_results[name] = {
        "weighted_kappa": kappa,
        "exact_agreement": exact_agreement
    }

    print(
        f"{name}: "
        f"weighted κ = {kappa:.3f}, "
        f"exact agreement = {exact_agreement:.1%}"
    )

helpfulness: weighted κ = -0.118, exact agreement = 30.0%
grounding: weighted κ = 0.000, exact agreement = 40.0%
actionability: weighted κ = -0.038, exact agreement = 45.0%
appropriateness: weighted κ = 0.000, exact agreement = 90.0%

In [49]:
response_dimensions = [
    "helpfulness",
    "grounding",
    "actionability",
    "appropriateness"
]

for col in response_dimensions:
    print(
        f"{col}: "
        f"mean = {human_eval[col].mean():.2f}, "
        f"distribution = {human_eval[col].value_counts().sort_index().to_dict()}"
    )

helpfulness: mean = 2.30, distribution = {1: 1, 2: 12, 3: 7}
grounding: mean = 2.35, distribution = {1: 1, 2: 11, 3: 8}
actionability: mean = 2.40, distribution = {2: 12, 3: 8}
appropriateness: mean = 2.90, distribution = {2: 2, 3: 18}

In [50]:
response_eval_remaining = response_eval.iloc[20:40].copy().reset_index(drop=True)

print("Examples to evaluate:", len(response_eval_remaining))

Examples to evaluate: 20

In [51]:
import pandas as pd
import os

remaining_eval = response_eval.iloc[20:40].copy().reset_index(drop=True)

human_eval_remaining = remaining_eval.copy()

human_eval_remaining["helpfulness"] = pd.NA
human_eval_remaining["grounding"] = pd.NA
human_eval_remaining["actionability"] = pd.NA
human_eval_remaining["appropriateness"] = pd.NA

for i in range(len(human_eval_remaining)):

    print("\n" + "=" * 80)
    print(f"EXAMPLE {i + 21}/40")
    print("=" * 80)

    row = human_eval_remaining.iloc[i]

    print("\nCUSTOMER:")
    print(row["text_customer"])

    print("\nGENERATED RESPONSE:")
    print(row["generated_response"])

    print("\nRETRIEVED EVIDENCE:")
    retrieved_cases = retrieve_similar_cases(
        row["text_customer"],
        top_k=3
    )

    for j, (_, case) in enumerate(retrieved_cases.iterrows(), start=1):
        print(f"\n--- Case {j} ---")
        print("Customer:", case["text_customer"])
        print("Historical response:", case["text_uber"])
        print("Similarity:", round(case["similarity"], 3))

    print("\nSCORING:")
    print("Helpfulness:      1/2/3")
    print("Grounding:        1/2/3")
    print("Actionability:    1/2/3")
    print("Appropriateness:  1/2/3")

    def get_score(name):
        while True:
            value = input(f"{name}: ").strip()
            if value in ["1", "2", "3"]:
                return int(value)
            print("Please enter only 1, 2, or 3.")

    human_eval_remaining.loc[i, "helpfulness"] = get_score("Helpfulness")
    human_eval_remaining.loc[i, "grounding"] = get_score("Grounding")
    human_eval_remaining.loc[i, "actionability"] = get_score("Actionability")
    human_eval_remaining.loc[i, "appropriateness"] = get_score("Appropriateness")

    human_eval_remaining.to_csv(
        "../data/human_response_eval_remaining.csv",
        index=False
    )

    print(f"\n✓ Example {i + 21} saved.")

print("\nDONE — all 20 remaining examples evaluated.")

================================================================================
EXAMPLE 21/40
================================================================================

CUSTOMER:
@Uber_Support my friend lost his phone in an uber last night and he has no way to contact the driver

GENERATED RESPONSE:
I’m sorry to hear about the loss. According to our privacy policy, we’ll need the account holder to reach out directly. Please have your friend contact us through this link: https://t.co/rOtqyWzf0B so our team can assist.

RETRIEVED EVIDENCE:

--- Case 1 ---
Customer: @Uber_Support friend lost her phone in her uber
Historical response: @823497 Happy to help! Send us a note here, https://t.co/rOtqyWzf0B, and our team will follow up.
Similarity: 0.689

--- Case 2 ---
Customer: @115873 @Uber_Support My friend lost his phone in Uber. Unable to contact the driver. Please help us contact the driver
Historical response: @821781 According to our privacy policy, we will have to speak directly to the account holder. Please have them contact us via https://t.co/rOtqyWzf0B so our team can assist you!
Similarity: 0.566

--- Case 3 ---
Customer: @Uber_Support friend lost her phone in an Uber. Plz help
Historical response: @179876 We've followed up with your DM, Matt. Please check back there for further details.
Similarity: 0.529

SCORING:
Helpfulness:      1/2/3
Grounding:        1/2/3
Actionability:    1/2/3
Appropriateness:  1/2/3

✓ Example 21 saved.

================================================================================
EXAMPLE 22/40
================================================================================

CUSTOMER:
Dear @115877 I am getting SOOOOO tired of your drivers getting the order wrong. #nycarea #ubereatsfail #eighthtimeisacharm

GENERATED RESPONSE:
Hi there! I’m sorry to hear that this has happened again. Please send us the details of the order at https://t.co/xLLG6cfrJA so we can look into it and help you resolve the issue.

RETRIEVED EVIDENCE:

--- Case 1 ---
Customer: Are @115877 bantering?! Tonight was not the time to be getting my order wrong!!! 😩😩😩😩😩😩😩😩
Historical response: @204482 Oh no! Please reach out to us here and we'll get you sorted: https://t.co/xLLG6cfrJA.
Similarity: 0.38

--- Case 2 ---
Customer: im so tired of @115877 getting my order wrong... also sitting in my office for almost an hour waiting for my food that is 10 mins away
Historical response: @777983 Oh no, Sean! Please send us the details at https://t.co/xLLG6cfrJA so we can help.
Similarity: 0.372

--- Case 3 ---
Customer: @Uber_Support there’s needs to be a toll free option to select. I’m tired of the drivers getting on the freeway in Melbourne
Historical response: @608416 We don't offer phone support in your city yet - we're working on it! In the meantime, can you give us more details about your concern?
Similarity: 0.312

SCORING:
Helpfulness:      1/2/3
Grounding:        1/2/3
Actionability:    1/2/3
Appropriateness:  1/2/3

✓ Example 22 saved.

================================================================================
EXAMPLE 23/40
================================================================================

CUSTOMER:
@Uber_Support Nobody reply on app it's more than 2 days now

GENERATED RESPONSE:
@Uber_Support I’m sorry you’re still waiting. Could you please DM us the email on your account so we can check the status of your message? Thanks!

RETRIEVED EVIDENCE:

--- Case 1 ---
Customer: @Uber_Support still no reply.
Historical response: @520098 Can you please DM us the email on your account so we can check on the status of your message? Thanks!
Similarity: 0.517

--- Case 2 ---
Customer: @Uber_Support Can I get a reply
Historical response: @320545 Hi Santosh, please reach out at https://t.co/41EELWKjnd so we can take a look.
Similarity: 0.517

--- Case 3 ---
Customer: @Uber_Support can you reply then
Historical response: @194799 We've been in touch via DM!
Similarity: 0.517

SCORING:
Helpfulness:      1/2/3
Grounding:        1/2/3
Actionability:    1/2/3
Appropriateness:  1/2/3

✓ Example 23 saved.

================================================================================
EXAMPLE 24/40
================================================================================

CUSTOMER:
So my @115873 driver just got a tude with me bc I have the window down. It smells of shit in here. &amp; I didn’t even complain

GENERATED RESPONSE:
I’m sorry to hear about your experience. Please reach out to Uber Support directly so we can look into this for you. You can do so through the app or by emailing support@uber.com.

RETRIEVED EVIDENCE:

--- Case 1 ---
Customer: .@115873 my driver just got hit by another car :/
Historical response: @357946 We take this very seriously. Kindly send us your email address so our team can assist.
Similarity: 0.325

--- Case 2 ---
Customer: Our uber driver just got pulled over :-)
Historical response: @198373 We want to follow up ASAP. Can you please send us a DM with your email address and additional details so we can connect?
Similarity: 0.312

--- Case 3 ---
Customer: OUR UBER DRIVER JUST GOT PULLED OVER. @630848
Historical response: @633069 We take this very seriously. Please send us a DM with your email address so we can connect.
Similarity: 0.312

SCORING:
Helpfulness:      1/2/3
Grounding:        1/2/3
Actionability:    1/2/3
Appropriateness:  1/2/3

✓ Example 24 saved.

================================================================================
EXAMPLE 25/40
================================================================================

CUSTOMER:
@Uber_Support I've been charged in cash a couple of times despite having INR 300 Uber credits in my account. I'm obliged to tweet here as your in-app support team is giving dumb replies that I don't have any Uber credits in my account. Makes no sense! https://t.co/z7KZqYF2eZ

GENERATED RESPONSE:
Hi there! I’m sorry you’re having trouble seeing your Uber credits. Please send us a direct message with your email address and any details about the rides where the credits didn’t apply, and we’ll look into it right away. Thank you for your patience.

RETRIEVED EVIDENCE:

--- Case 1 ---
Customer: .@Uber_Support Its been 6 days you guys promised to give me the Uber Credits.. But I can't see any credits in my Account ..plzz see to it
Historical response: @119136 We're here to help! Send us a DM with your email address so we can follow up.
Similarity: 0.369

--- Case 2 ---
Customer: @115873 this email makes no sense https://t.co/ly8ORocbDE
Historical response: @409027 We're so sorry about that! Can you please send us a DM with your email address and additional details so we can assist?
Similarity: 0.289

--- Case 3 ---
Customer: @Uber_Support hi I have a question I have rs credits in my account can I use them in $ ?
Historical response: @549710 Hi Vanisha! Please reach out to https://t.co/zUe0dj6yoX and fill out the 4 boxes at the bottom so we can get in touch.
Similarity: 0.279

SCORING:
Helpfulness:      1/2/3
Grounding:        1/2/3
Actionability:    1/2/3
Appropriateness:  1/2/3

✓ Example 25 saved.

================================================================================
EXAMPLE 26/40
================================================================================

CUSTOMER:
No @115873. You cannot tell me there is a car 3 minutes away while I’m in Times Square and then assign me a car that’s on the upper west side and say it’s 15 minutes away when any New Yorker knows it’s 30 minutes. That’s not how this works.

GENERATED RESPONSE:
I’m sorry you’re having trouble with the pickup times. Please send us a note at https://t.co/e8HVorX5rh so our team can look into this for you.

RETRIEVED EVIDENCE:

--- Case 1 ---
Customer: @115873 be 5 minutes away for 30 minutes 🤔
Historical response: @341383 Here to help. Send us a note at https://t.co/e8HVorX5rh so our team can connect.
Similarity: 0.422

--- Case 2 ---
Customer: @Uber_Support why do I always get a car 6 minutes away or more when I see 5 or more available 1 minute away ?
Historical response: @387007 Here to help. Send us a note at https://t.co/e8HVorX5rh so our team can connect.
Similarity: 0.399

--- Case 3 ---
Customer: @115873 Now it’s 9 minutes away.
Historical response: @464634 Here to help! Send us a note at https://t.co/e8HVorX5rh so our team can connect right away.
Similarity: 0.389

SCORING:
Helpfulness:      1/2/3
Grounding:        1/2/3
Actionability:    1/2/3
Appropriateness:  1/2/3

✓ Example 26 saved.

================================================================================
EXAMPLE 27/40
================================================================================

CUSTOMER:
Wow. The cops pull my Uber over right when he pulls up

GENERATED RESPONSE:
I’m sorry to hear that happened. Please send us a direct message with your email address so we can connect you with the right team to look into this.

RETRIEVED EVIDENCE:

--- Case 1 ---
Customer: This Uber pulls over to let us in and these cops come out of nowhere to harass the driver for not "pulling into a more sensible spot."
Historical response: @690736 We take this very seriously. Please send us a DM with your email address so we can connect ASAP.
Similarity: 0.308

--- Case 2 ---
Customer: @Uber_Support lost phone in uber right now ... please help!
Historical response: @250093 Here to help! Get in contact with your driver here: https://t.co/rOtqyWzf0B
Similarity: 0.268

--- Case 3 ---
Customer: @115873 I’m in an Uber right now and the driver is absolutely bollocking me for choosing somewhere hard to pick up from.
Historical response: @503948 Oh no! This doesn't sound right, Christian. Please send us a note at https://t.co/z1ptRNSg0z and a member of our team will follow up.
Similarity: 0.251

SCORING:
Helpfulness:      1/2/3
Grounding:        1/2/3
Actionability:    1/2/3
Appropriateness:  1/2/3

✓ Example 27 saved.

================================================================================
EXAMPLE 28/40
================================================================================

CUSTOMER:
@Uber_Support issues logging in. Your team member Eevin from support emailed asking for a screenshot of my number. Sent. “You’ve sent us a reply from a different email address” - replied by system. Can you help?

GENERATED RESPONSE:
I’m sorry you’re still having trouble. Please send us the email address you used to contact us so we can locate your request and get it resolved. Thank you.

RETRIEVED EVIDENCE:

--- Case 1 ---
Customer: @Uber_Support I’ve sent two and had no reply.
Historical response: @375325 Sorry about the trouble, Chrisie. Please DM us your email address so we can follow up immediately.
Similarity: 0.411

--- Case 2 ---
Customer: @Uber_Support I sent another please reply
Historical response: @215674 Happy to help - our team has received your support message and followed up. Please connect with us there if you have any questions.
Similarity: 0.341

--- Case 3 ---
Customer: @Uber_Support Sent still no reply
Historical response: @181542 Thanks! Support requests are responded to in the order they are received. We will follow up with you soon. Thanks for your patience.
Similarity: 0.341

SCORING:
Helpfulness:      1/2/3
Grounding:        1/2/3
Actionability:    1/2/3
Appropriateness:  1/2/3

✓ Example 28 saved.

================================================================================
EXAMPLE 29/40
================================================================================

CUSTOMER:
.@115873 you should give loyal customers a free ride on their birthdays #uber

GENERATED RESPONSE:
Hi there! I’m sorry we don’t have a birthday‑ride promotion available at the moment. If you’d like to discuss this further or have any other questions, please reach out to Uber Support through the app or our help center. We’re here to help!

RETRIEVED EVIDENCE:

--- Case 1 ---
Customer: @115877 why do you never have promo codes for loyal customers!!!!
Historical response: @237278 Here to help! For more info on how to get free food, please visit; https://t.co/M2oCDvGYgt
Similarity: 0.528

--- Case 2 ---
Customer: You know @115877 , it would be nice, if for once, you could give out a free delivery promo to loyal customers. 😒
Historical response: @537077 Thanks for reaching out, Katlyn! You can always share your referral code with friends so you can rack up free codes when they sign up.
Similarity: 0.488

--- Case 3 ---
Customer: @Uber_Support This is how you handle real time requests of your loyal customers. Shame on you
Historical response: @417060 We're here to help! Send us a DM with your email address so we can assist.
Similarity: 0.416

SCORING:
Helpfulness:      1/2/3
Grounding:        1/2/3
Actionability:    1/2/3
Appropriateness:  1/2/3

✓ Example 29 saved.

================================================================================
EXAMPLE 30/40
================================================================================

CUSTOMER:
@Uber_Support I left my glasses in the car last night and I just can't get through to the driver. Please help. I can't see 😭😭😭😭

GENERATED RESPONSE:
@Uber_Support Sorry to hear about your glasses! Please send us a note here: https://t.co/Sy2fWIhhC2 and our team will reach out to help you retrieve them.

RETRIEVED EVIDENCE:

--- Case 1 ---
Customer: @Uber_Support I left my glasses in an Uber last night. How can I get them back?
Historical response: @758766 Sorry for the trouble! Send us a note here, https://t.co/Sy2fWIhhC2 and our team will be in touch.
Similarity: 0.532

--- Case 2 ---
Customer: . @Uber_Support hey i think i left my glasses in a car and i cant get a hold of the driver and i need them 2 see SOS
Historical response: @734155 Here to help! Send us a note at https://t.co/oY5vj3NqP3 so our team can connect right away.
Similarity: 0.317

--- Case 3 ---
Customer: hey @115873 - left my iphone in the car last night and still have not heard back from the driver. PLEASE help ASAP.
Historical response: @446626 Here to help! Find out more about contacting your driver here; https://t.co/rOtqyWzf0B.
Similarity: 0.313

SCORING:
Helpfulness:      1/2/3
Grounding:        1/2/3
Actionability:    1/2/3
Appropriateness:  1/2/3

✓ Example 30 saved.

================================================================================
EXAMPLE 31/40
================================================================================

CUSTOMER:
@115873 @Uber_Support @116288 The total fare what is being shown in app is 1208.69. . how can you cheat like this ..

GENERATED RESPONSE:
Hi there! I’m sorry you’re seeing a discrepancy in the fare. Let’s get this sorted out. Please send us a note through this link: https://t.co/1xM0TILvAI so our team can take a closer look and help resolve the issue.

RETRIEVED EVIDENCE:

--- Case 1 ---
Customer: @115873 total fare &amp;amount reflecting in receipt both are different for 3 rides, got virtual credits which were never deducted from total fare
Historical response: @723209 We're here to help! Please send us a note via https://t.co/1xM0TILvAI so we can take a closer look.
Similarity: 0.349

--- Case 2 ---
Customer: @Uber_Support @115873 Do i need to pay fare shown in my app+ toll from Banglore airport to yelahanka?
Reply soon i am in cab
Historical response: @137929 Hi, here to help! Send us a note at; https://t.co/50PlssKWjo so our team can assist.
Similarity: 0.338

--- Case 3 ---
Customer: Does we have to pay toll charges extra for ride or it's included in fare shown in app. @115873 @Uber_Support @390
Historical response: @463769 Here to help! Check out https://t.co/nvJx2zGPV5 for more information.
Similarity: 0.286

SCORING:
Helpfulness:      1/2/3
Grounding:        1/2/3
Actionability:    1/2/3
Appropriateness:  1/2/3

✓ Example 31 saved.

================================================================================
EXAMPLE 32/40
================================================================================

CUSTOMER:
@148768 @115877 Can we get some free donughnuts in W11? Were close to the westfield store!

GENERATED RESPONSE:
Hi @148768 @115877, we’re sorry you’re having trouble finding the store. The free donut promotion is currently limited and many locations have run out of stock. Please keep trying, and if you still can’t locate the store, let us know so we can help you find an alternative option. Thank you for your patience.

RETRIEVED EVIDENCE:

--- Case 1 ---
Customer: @148768 @115877 Was going to buy them from westfield then when it got to 2pm i cant find the store anymore....
Historical response: @695884 We've been overwhelmed by demand! Please try uninstalling and reinstalling the app. Supply is limited, but please keep trying.
Similarity: 0.533

--- Case 2 ---
Customer: @148768 @115877 Free offer but closed? @115877 @148768 https://t.co/AeTBpTO2gR
Historical response: @695263 We're so sorry you didn’t get your FREE Original Glazed Dozen box. Demand was through the roof and stocks ran out! Stay tuned for more fun promotions soon!
Similarity: 0.501

--- Case 3 ---
Customer: @148768 @115877 Still not finding the store ?
Historical response: @691288 We're working hard to get Krispy Kreme to as many people as possible! Keep trying.
Similarity: 0.478

SCORING:
Helpfulness:      1/2/3
Grounding:        1/2/3
Actionability:    1/2/3
Appropriateness:  1/2/3

✓ Example 32 saved.

================================================================================
EXAMPLE 33/40
================================================================================

CUSTOMER:
@Uber_Support Thanks for telling me what I already knew with that useless support reply &amp; uninformative link. Way to screw up your promo, @175881.

GENERATED RESPONSE:
I’m sorry to hear that the previous response didn’t address your concerns. Please reach out to us directly through the Uber app’s Help section so we can look into the promo issue for you. Thank you for your patience.

RETRIEVED EVIDENCE:

--- Case 1 ---
Customer: @Uber_Support thanks :)
Historical response: @327836 Thank you! We know how time-sensitive this issue is for you. Hang-tight for us!
Similarity: 0.29

--- Case 2 ---
Customer: @Uber_Support thanks :))))))
Historical response: @205200 Here to help. A member of our team has followed up via DM.
Similarity: 0.29

--- Case 3 ---
Customer: @Uber_Support Thanks!
Historical response: @262189 Hi Criena, here to help! Kindly confirm your email address or phone number via direct message so that we can look into this issue.
Similarity: 0.29

SCORING:
Helpfulness:      1/2/3
Grounding:        1/2/3
Actionability:    1/2/3
Appropriateness:  1/2/3

✓ Example 33 saved.

================================================================================
EXAMPLE 34/40
================================================================================

CUSTOMER:
@Uber_Support @356309 we should ban Uber in India. their driver takes their own route and waste your time. No safety for females. Moreover their female employees are not much concerned. they want this problem from drivers of Uber

GENERATED RESPONSE:
Hi there, I’m sorry to hear about your experience. To help us look into this, could you please DM us the email address linked to your Uber account? Once we have that, we’ll be able to review the situation and get back to you. Thank you.

RETRIEVED EVIDENCE:

--- Case 1 ---
Customer: @Uber_Support What if no driver takes the trip ?
Historical response: @705226 In the rare case a driver cannot be found, Gail, you'll be notified at the end of your selected time window. If we can help answer anything further, please simply let us know.
Similarity: 0.248

--- Case 2 ---
Customer: #Uber #Driver waste of time
Historical response: @606733 Hey, Suzanne. Please DM us the email linked to your account so we can check on the status of your support outreach and follow up.
Similarity: 0.246

--- Case 3 ---

In [52]:
# Load the first 20
human_eval_1 = pd.read_csv("../data/human_response_eval.csv")

# Load the remaining 20
human_eval_2 = pd.read_csv("../data/human_response_eval_remaining.csv")

# Combine
human_eval_40 = pd.concat(
    [human_eval_1, human_eval_2],
    ignore_index=True
)

print("Total evaluations:", len(human_eval_40))
print("\nColumns:")
print(human_eval_40.columns.tolist())

Total evaluations: 40

Columns:
['text_customer', 'text_uber', 'intent', 'escalate', 'predicted_intent', 'predicted_escalate', 'generated_response', 'retrieved_evidence', 'helpfulness', 'grounding', 'actionability', 'appropriateness', 'judge_helpfulness', 'judge_grounding', 'judge_actionability', 'judge_appropriateness']

In [53]:
dimensions = [
    "helpfulness",
    "grounding",
    "actionability",
    "appropriateness"
]

for col in dimensions:
    scores = human_eval_40[col].astype(int)

    print(
        f"{col}: "
        f"mean = {scores.mean():.2f}, "
        f"distribution = {scores.value_counts().sort_index().to_dict()}"
    )

helpfulness: mean = 2.40, distribution = {1: 1, 2: 22, 3: 17}
grounding: mean = 2.62, distribution = {1: 1, 2: 13, 3: 26}
actionability: mean = 2.40, distribution = {2: 24, 3: 16}
appropriateness: mean = 2.95, distribution = {2: 2, 3: 38}

In [54]:
human_eval_40.to_csv(
    "../data/human_response_eval_40.csv",
    index=False
)

print("Saved:", len(human_eval_40), "evaluations")

Saved: 40 evaluations

In [55]:
for col in [
    "helpfulness",
    "grounding",
    "actionability",
    "appropriateness"
]:
    scores = human_eval_40[col].astype(int)

    print(
        f"{col}: "
        f"mean = {scores.mean():.2f}, "
        f"distribution = {scores.value_counts().sort_index().to_dict()}"
    )

helpfulness: mean = 2.40, distribution = {1: 1, 2: 22, 3: 17}
grounding: mean = 2.62, distribution = {1: 1, 2: 13, 3: 26}
actionability: mean = 2.40, distribution = {2: 24, 3: 16}
appropriateness: mean = 2.95, distribution = {2: 2, 3: 38}

In [56]:
from sklearn.metrics import confusion_matrix, classification_report

print(classification_report(
    golden_eval["intent"],
    golden_eval["predicted_intent"],
    zero_division=0
))

                           precision    recall  f1-score   support

  account_access_security       0.71      0.53      0.61        19
           benefits_other       0.12      0.62      0.21         8
             driver_issue       0.60      0.83      0.70        36
           driver_metrics       0.00      0.00      0.00         5
              fare_charge       0.50      0.80      0.62        15
       location_app_issue       0.11      0.50      0.18         2
                lost_item       0.71      1.00      0.83         5
                   refund       0.33      0.67      0.44         3
ride_booking_cancellation       1.00      0.10      0.17        21
         support_followup       0.91      0.53      0.67        60
                uber_eats       1.00      0.50      0.67        26

                 accuracy                           0.56       200
                macro avg       0.55      0.55      0.46       200
             weighted avg       0.75      0.56      0.57       200

In [57]:
errors = golden_eval[
    golden_eval["intent"] != golden_eval["predicted_intent"]
].copy()

print("Total errors:", len(errors))

print(
    errors[
        ["text_customer", "intent", "predicted_intent"]
    ].head(30).to_string(index=False)
)

Total errors: 88
                                                                                                                                                                                                                                                                                             text_customer                    intent        predicted_intent
@Uber_Support Yo what’s with this $300 charge? I needed an Uber and this Uber driver never even showed to pick me up? How am I getting charged for 1. A ride I never took &amp; 2. A mess I couldn’t have made. Tried to make a simple correction and then y’all charged me more?? https://t.co/DUtC7SKKut               fare_charge                  refund
                                                                                                                                                                                                            @Uber_Support Cancellation is fine. He didn't even brother to notify me . I called him myself. ride_booking_cancellation            driver_issue
                                                                                                                                                                        @Uber_Support why is it that I get fined $5 if I cancel an Uber but get nothing in return when one wastes 15 minutes of my time... ride_booking_cancellation             fare_charge
                                                                                                                                                                                                                                                                   @115877 Justice https://t.co/paIRt3qAIf          support_followup          benefits_other
                                                                                                                                                        @Uber_Support Thats not an acceptable answer to an ongoing critical safety issue. This happens thousands of times a day just on the Boston region.                 uber_eats            driver_issue
                                                                                                                                                                                                    @115873 outrageous you have just charged me 5 pounds for a cancelled ride and we will waiting for you! ride_booking_cancellation             fare_charge
                                                                                                                                                                Wish I could give Uber drivers 5 stars while simultaneously giving the @Uber_Support app a 0 star rating for giving the wrong directions 🙄          support_followup      location_app_issue
                                                                                                                                                                                   @Uber_Support, Can't log into my or husband's account because neither your SMS or Voice 2 Factor are working. Now what?          support_followup account_access_security
                                                                                                                                                                                             @Uber_Support hi I received the Ride Pass email and have used it in the past but it is not showing in the app          support_followup          benefits_other
                                                                                                                                                                                                                        Waiting 15 min for an @115873 at LGA? Wtf?? Might as well just grab a taxi... #NYC ride_booking_cancellation            driver_issue
                                                                                                                                                                                                                         @Uber_Support We tried @9150 o'clock. Little upset it wasn't working for an hour.          support_followup          benefits_other
                                                                                                                           @Uber_Support \ni received an email saying my insurance I applied with is expired. Like i told the representative yesterday, that is the EFFECTIVE date not the expiration date          support_followup          benefits_other
                          @Uber_Support I tried going on the link and it's just very confusing and overwhelming for me... I've been online for FOUR hours destination set to the airport... last rider I got was going the complete opposite direction so I had to cancel for him. https://t.co/rJt0LGEHjX ride_booking_cancellation          benefits_other
                            @115873 did you decide to loot hyderabad today?have identified 3 cases where u over charged customers today..and what is this new trend of sending a message like u may be charged high and driver will inform?after the trip starts?no traffic jam no waiting no longer route              driver_issue             fare_charge
                                                                                                     @115873 @Uber_Support \n__email__\nNot able to book a ride. Always pop-up a message that visit https://t.co/7lQbjedBQa.\nIt didn't give me solution. Please aolve my issue asap.\nThanks Team @115873 ride_booking_cancellation      location_app_issue
                                                                                      @Uber_Support My @115877 order just arrived. When I sat down to eat it, another driver called telling me they had my order. Did the vendor fill the order twice or am I gonna be charged twice? What's up with that?                 uber_eats          benefits_other
                                                                                                                                                    @Uber_Support Thanks for telling me what I already knew with that useless support reply &amp; uninformative link. Way to screw up your promo, @175881.          support_followup          benefits_other
                                                                                                                                                                                                                                                        @Uber_Support can you guys just cancel that order?                 uber_eats          benefits_other
                                                                                                                                                                                                                                                                    @115877 The app and the site are down.   account_access_security      location_app_issue
                                                                                                                                                 @Uber_Support Does ride pass just show up on the app? I’ve used a considerable amount of rides, so I wonder if the criteria is not how much rides you use          support_followup          benefits_other
                                                                                                                                                                                 @Uber_Support Hi can you please let me know what happened to my Uber Pass ? I had it on auto renew and now it disappeared          support_followup          benefits_other
                                                                                                                                                                                                                                                        @Uber_Support when will the instant cash out work?          support_followup          benefits_other
                                                                            @Uber_Support its ok if you cannot provide me the driver details... i just wanted the exact pick up point from Rajokri to the airport this evening... it wasnt very clear on the ETA.. could you kindly help with just that...              driver_issue      location_app_issue
                                                                                                                                                                     @115873 driver stole my iphone. Tracked for a minute. He turned the phone off and wont answer his phone. Help https://t.co/OBg3jv0DkJ              driver_issue               lost_item
                                                                                                                                                                                                      @Uber_Support I live in Albuquerque, NM. How can I add Uber Español to my passenger options? Thanks!          support_followup          benefits_other
                                                                                                                                                                            Fuck Uber and everything they represent!! @115873 how does a 5 cancellations and supposedly 3mins away! You what fuck your app ride_booking_cancellation            driver_issue
                                                                                                                                                     @435368 @115873 Dont expect anything back from @115873 they said they were outside my house to pick me up when they clearly werent then charged me £6              driver_issue             fare_charge
                                                                                                                                                                                                                                           @Uber_Support See @1143  system there system is so transparent.          support_followup          benefits_other
                                                                                                                                                                                        @Uber_Support Unfortunately that's not quite it - can we ask about a particular driver? We got an unreasonable 2/5          support_followup            driver_issue
                                                                                                                                                                                  @115877 @64394 Ordered at 4 got a driver at 5 and cancelled shortly after what’s happening here? https://t.co/vaawOF9XzE ride_booking_cancellation            driver_issue

In [58]:
# Show representative errors for selected failure patterns

patterns = {
    "benefits_other_overprediction": (
        (golden_eval["predicted_intent"] == "benefits_other") &
        (golden_eval["intent"] != "benefits_other")
    ),
    
    "fare_charge_vs_cancellation": (
        (golden_eval["intent"] == "ride_booking_cancellation") &
        (golden_eval["predicted_intent"] == "fare_charge")
    ),
    
    "driver_vs_ride_confusion": (
        (golden_eval["intent"] == "ride_booking_cancellation") &
        (golden_eval["predicted_intent"] == "driver_issue")
    ),
    
    "context_ambiguous": (
        golden_eval["text_customer"].str.len() < 50
    ) & (
        golden_eval["intent"] != golden_eval["predicted_intent"]
    ),
    
    "multi_issue_errors": (
        golden_eval["intent"] != golden_eval["predicted_intent"]
    ) & (
        golden_eval["text_customer"].str.len() > 250
    )
}

for name, mask in patterns.items():
    print("\n" + "=" * 90)
    print(name)
    print("=" * 90)
    
    examples = golden_eval.loc[
        mask,
        ["text_customer", "intent", "predicted_intent"]
    ].head(5)
    
    print(examples.to_string(index=False))

==========================================================================================
benefits_other_overprediction
==========================================================================================
                                                                                                                                                                                                                                                                   text_customer                    intent predicted_intent
                                                                                                                                                                                                                                         @115877 Justice https://t.co/paIRt3qAIf          support_followup   benefits_other
                                                                                                                                                                   @Uber_Support hi I received the Ride Pass email and have used it in the past but it is not showing in the app          support_followup   benefits_other
                                                                                                                                                                                               @Uber_Support We tried @9150 o'clock. Little upset it wasn't working for an hour.          support_followup   benefits_other
                                                                                                 @Uber_Support \ni received an email saying my insurance I applied with is expired. Like i told the representative yesterday, that is the EFFECTIVE date not the expiration date          support_followup   benefits_other
@Uber_Support I tried going on the link and it's just very confusing and overwhelming for me... I've been online for FOUR hours destination set to the airport... last rider I got was going the complete opposite direction so I had to cancel for him. https://t.co/rJt0LGEHjX ride_booking_cancellation   benefits_other

==========================================================================================
fare_charge_vs_cancellation
==========================================================================================
                                                                                                                                                                                                                                                              text_customer                    intent predicted_intent
                                                                                                                                         @Uber_Support why is it that I get fined $5 if I cancel an Uber but get nothing in return when one wastes 15 minutes of my time... ride_booking_cancellation      fare_charge
                                                                                                                                                                     @115873 outrageous you have just charged me 5 pounds for a cancelled ride and we will waiting for you! ride_booking_cancellation      fare_charge
                                                                                                                              So you get charged for cancelling if a driver is on the way, but it's alright for a driver to cancel on you if you've been waiting? @115873 🤔 ride_booking_cancellation      fare_charge
.@115873 I understand the need for cancellation fees, but I literally tried to cancel my accidental uber pool choice as it was searching for a driver. Canceled less than 5 seconds after being connected and was still charged because “my driver was already en route”... ride_booking_cancellation      fare_charge

==========================================================================================
driver_vs_ride_confusion
==========================================================================================
                                                                                                                                                                    text_customer                    intent predicted_intent
                                                                                   @Uber_Support Cancellation is fine. He didn't even brother to notify me . I called him myself. ride_booking_cancellation     driver_issue
                                                                                               Waiting 15 min for an @115873 at LGA? Wtf?? Might as well just grab a taxi... #NYC ride_booking_cancellation     driver_issue
                                                   Fuck Uber and everything they represent!! @115873 how does a 5 cancellations and supposedly 3mins away! You what fuck your app ride_booking_cancellation     driver_issue
                                                         @115877 @64394 Ordered at 4 got a driver at 5 and cancelled shortly after what’s happening here? https://t.co/vaawOF9XzE ride_booking_cancellation     driver_issue
Why even bothering scheduling a pick-up on @115873 when they’re going to give you a 20 minute window that you then have to wait for a driver to accept #notcool #35minuteslater 🖕 ride_booking_cancellation     driver_issue

==========================================================================================
context_ambiguous
==========================================================================================
                            text_customer                  intent   predicted_intent
  @115877 Justice https://t.co/paIRt3qAIf        support_followup     benefits_other
   @115877 The app and the site are down. account_access_security location_app_issue
@115877 thank you for ruining my night 😊.          benefits_other       driver_issue
  @115877 fuck you, give me my McDonald’s               uber_eats     benefits_other
   @Uber_Support But he is not on tweeter        support_followup     benefits_other

==========================================================================================
multi_issue_errors
==========================================================================================
                                                                                                                                                                                                                                                                                             text_customer                    intent predicted_intent
@Uber_Support Yo what’s with this $300 charge? I needed an Uber and this Uber driver never even showed to pick me up? How am I getting charged for 1. A ride I never took &amp; 2. A mess I couldn’t have made. Tried to make a simple correction and then y’all charged me more?? https://t.co/DUtC7SKKut               fare_charge           refund
                          @Uber_Support I tried going on the link and it's just very confusing and overwhelming for me... I've been online for FOUR hours destination set to the airport... last rider I got was going the complete opposite direction so I had to cancel for him. https://t.co/rJt0LGEHjX ride_booking_cancellation   benefits_other
                            @115873 did you decide to loot hyderabad today?have identified 3 cases where u over charged customers today..and what is this new trend of sending a message like u may be charged high and driver will inform?after the trip starts?no traffic jam no waiting no longer route              driver_issue      fare_charge
                                 @Uber_Support I honestly haven't experienced worse customer service: 18 fraudulent journeys in India were made from from Oct 2 to 4 (I was in France at the time) means that £162.18 has been debited. Still no refund despite 10 emails to Uber CS. @76474 can you help?   account_access_security           refund
                                     @uber_support Do you have a customer service phone number? I can't deal with your email support anymore. They are completely ignoring my concerns and question and not giving me any explaination as to why I'm being charged for tolls on routes that have no tolls.          support_followup      fare_charge

In [60]:
examples = {
    "benefits_other_overprediction": (
        (golden_eval["predicted_intent"] == "benefits_other") &
        (golden_eval["intent"] != "benefits_other")
    ),

    "fare_charge_vs_cancellation": (
        (golden_eval["intent"] == "ride_booking_cancellation") &
        (golden_eval["predicted_intent"] == "fare_charge")
    ),

    "driver_vs_cancellation": (
        (golden_eval["intent"] == "ride_booking_cancellation") &
        (golden_eval["predicted_intent"] == "driver_issue")
    ),

    "rare_intent_errors": (
        golden_eval["intent"].isin([
            "driver_metrics",
            "location_app_issue",
            "refund"
        ]) &
        (golden_eval["intent"] != golden_eval["predicted_intent"])
    ),

    "ambiguous_or_multi_issue": (
        (golden_eval["intent"] != golden_eval["predicted_intent"]) &
        (
            (golden_eval["text_customer"].str.len() < 60) |
            (golden_eval["text_customer"].str.len() > 250)
        )
    )
}

for name, mask in examples.items():
    print("\n" + "=" * 90)
    print(name)
    print("=" * 90)

    result = golden_eval.loc[
        mask,
        ["text_customer", "intent", "predicted_intent"]
    ].head(1)

    print(result.to_string(index=False))

==========================================================================================
benefits_other_overprediction
==========================================================================================
                          text_customer           intent predicted_intent
@115877 Justice https://t.co/paIRt3qAIf support_followup   benefits_other

==========================================================================================
fare_charge_vs_cancellation
==========================================================================================
                                                                                                                     text_customer                    intent predicted_intent
@Uber_Support why is it that I get fined $5 if I cancel an Uber but get nothing in return when one wastes 15 minutes of my time... ride_booking_cancellation      fare_charge

==========================================================================================
driver_vs_cancellation
==========================================================================================
                                                                                 text_customer                    intent predicted_intent
@Uber_Support Cancellation is fine. He didn't even brother to notify me . I called him myself. ride_booking_cancellation     driver_issue

==========================================================================================
rare_intent_errors
==========================================================================================
                                                                 text_customer             intent predicted_intent
@Uber_Support  it says my car is not eligible for rides in Harrisburg PA.????? location_app_issue     driver_issue

==========================================================================================
ambiguous_or_multi_issue
==========================================================================================
                                                                                                                                                                                                                                                                                             text_customer      intent predicted_intent
@Uber_Support Yo what’s with this $300 charge? I needed an Uber and this Uber driver never even showed to pick me up? How am I getting charged for 1. A ride I never took &amp; 2. A mess I couldn’t have made. Tried to make a simple correction and then y’all charged me more?? https://t.co/DUtC7SKKut fare_charge           refund

In [61]:
# Escalation errors
escalation_errors = golden_eval[
    golden_eval["escalate"] != golden_eval["predicted_escalate"]
].copy()

print("Total escalation errors:", len(escalation_errors))

print("\nFALSE NEGATIVES — Human said YES, model said NO")
fn = escalation_errors[
    (escalation_errors["escalate"] == True) &
    (escalation_errors["predicted_escalate"] == False)
]

print(
    fn[
        ["text_customer", "intent", "escalate", "predicted_escalate"]
    ].head(10).to_string(index=False)
)

print("\nFALSE POSITIVES — Human said NO, model said YES")
fp = escalation_errors[
    (escalation_errors["escalate"] == False) &
    (escalation_errors["predicted_escalate"] == True)
]

print(
    fp[
        ["text_customer", "intent", "escalate", "predicted_escalate"]
    ].head(10).to_string(index=False)
)

Total escalation errors: 61

FALSE NEGATIVES — Human said YES, model said NO
                                                                                                                                                                                                                                                                   text_customer                    intent  escalate  predicted_escalate
                                                                                                                                        @Uber_Support My black food bag got stolen. Went all the way to remote roseville mn greenlight and greeter said they never carried them.                 lost_item      True               False
                                                                                                                                                                                              Waiting 15 min for an @115873 at LGA? Wtf?? Might as well just grab a taxi... #NYC ride_booking_cancellation      True               False
                                                                                                 @Uber_Support \ni received an email saying my insurance I applied with is expired. Like i told the representative yesterday, that is the EFFECTIVE date not the expiration date          support_followup      True               False
@Uber_Support I tried going on the link and it's just very confusing and overwhelming for me... I've been online for FOUR hours destination set to the airport... last rider I got was going the complete opposite direction so I had to cancel for him. https://t.co/rJt0LGEHjX ride_booking_cancellation      True               False
                                                                           @115873 @Uber_Support \n__email__\nNot able to book a ride. Always pop-up a message that visit https://t.co/7lQbjedBQa.\nIt didn't give me solution. Please aolve my issue asap.\nThanks Team @115873 ride_booking_cancellation      True               False
                                                                                                                                                                                                       @Uber_Support Already raised a case there..pls chk and revert on priority          support_followup      True               False
                                                                                                                                                                                                                              @Uber_Support can you guys just cancel that order?                 uber_eats      True               False
                                                                                                                                                                                                                        Hey @Uber_Support , how long should i wait for a reply??          support_followup      True               False
                                                                                                                                                      @115873 Can you please make sure your drivers understand how GPS works. My one hour and 30 min ride turn into 3 hours.😭😭😭😡              driver_issue      True               False
                                                                                                                                                  Fuck Uber and everything they represent!! @115873 how does a 5 cancellations and supposedly 3mins away! You what fuck your app ride_booking_cancellation      True               False

FALSE POSITIVES — Human said NO, model said YES
                                                                                                                                                                                                       text_customer                    intent  escalate  predicted_escalate
                                                                                     @115873 can someone please explain to me how I can get ahold of uber I tried to email I'm not getting any responses back at all          support_followup     False                True
                                                                                                                                     @162763 @115877 @148768 same!!! three ppl in my office have had it cancelled :/ ride_booking_cancellation     False                True
                                                                                             @Uber_Support, Can't log into my or husband's account because neither your SMS or Voice 2 Factor are working. Now what?          support_followup     False                True
                                                             @Uber_Support Ok I have done, but last time I was hacked that support team didn't get back to me for over a week, whilst someone ubered around Glasgow.   account_access_security     False                True
                                                                                     So my @115873 driver just got a tude with me bc I have the window down. It smells of shit in here. &amp; I didn’t even complain              driver_issue     False                True
@Uber_Support My @115877 order just arrived. When I sat down to eat it, another driver called telling me they had my order. Did the vendor fill the order twice or am I gonna be charged twice? What's up with that?                 uber_eats     False                True
                                    @Uber_Support Account holder does not know too much about Internet or technology. Doesn’t remember password or have access to e-mail account. I am assisting her as her brother.   account_access_security     False                True
                                                                                           @Uber_Support hi there, can I please put a request in for a refund as the uber driver charged me when I wasn't in the car                    refund     False                True
                                                                                           @Uber_Support Hi can you please let me know what happened to my Uber Pass ? I had it on auto renew and now it disappeared          support_followup     False                True
                                                                                                             @Uber_Support we need a way to complain about drivers who accept the trip, talk to us and don't turn up              driver_issue     False                True

In [64]:
import sys
from pathlib import Path

PROJECT_ROOT = Path.cwd().parent

if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from src.llm import (
    classify_intent,
    generate_grounded_response,
    classify_escalation
)

In [65]:
result = classify_escalation(
    "My driver left me stranded alone late at night and drove away.",
    "driver_issue"
)

print(result)

{'escalate': True, 'reason': 'The driver abandoned the passenger late at night, posing a safety concern that requires human investigation.'}